# Introduction {#intro}

Welcome to this book about starting a prayer practice, an awakening of the soul’s inner statues and icons to bring the Gods into one’s life. Its title is a reference to a speech in Plato’s *Symposium*, one of many dialogues that Plato wrote starring his deceased teacher, Socrates. In ancient world for straying from the path of self-discovery and love of wisdom for a disastrous career in politics — bursts into a drinking party where each attendee has been giving a speech on Eros. He describes Socrates as the statue of a woodland spirit (a satyr), hollow and filled with small icons of Gods. Socrates drives Alcibiades to evaluate his actions and attempt at being better, a jolt every time they encounter each other. Alcibiades is acutely aware that he can be so much more despite his powerlessness in the face of the strong vices and emotions that throw him into bad situations.

Like Alcibiades, we are all divided into many pieces, from work to family to society, our awareness cast about from thing to thing like a tiny vessel trying not to capsize on a tumultuous ocean. We struggle to know *where* we are, let alone *who* we are; forgetting our intrinsic wholeness, we seek to be whole. Coming to see the statues hidden within ourselves and the divine beings they represent — and anchoring ourselves to these divine ones in the quest to flourish as human beings — can go a long way to securing our inner calm, even in the face of grueling challenges, calamities, or the daily grind of work and life. Unlike Alcibiades, whose life story had long been set by the time Plato started writing the *Symposium*, we each also have opportunities to grow and change for the better in this lifetime.

*The Soul’s Inner Statues* aims at being a small guidebook: a collection of tips and practices that can withstand the ocean’s sprays of water and stinging salt. It is intended to be a systemic synthesis useful to those of us in current times, especially we who live in cultural melting pots like the United States, as we ponder what allures us about the dazzling statues of Gods and the strange stories hidden beneath the husk of commercialization and popular entertainment.

Finally, it is a hymn, both to the Gods and the underlying unity of all things that cannot be named, let alone conceived — to the ones whose images are nestled within our souls like jewels awaiting discovery and reunion with our everyday selves. “All things are full of Gods,” the ancient Greek statesman Thales once said. Iamblichus, a Syrian philosopher writing in the early common era, wrote that acknowledging that the Gods exist is “not the right way to put it”; he continued that “an innate knowledge about the gods is coexistent with our nature, and is superior to all judgment and choice, reasoning and proof” and “[t]his knowledge is united from the outset with its own cause and exists in tandem with the essential striving of the soul towards the Good” (De Mysteriis, trans. Clarke et al., 2013, I.3). Unpacking what Iamblichus said — the assumptions we may make on first reading it, the necessity of casting off misguided beliefs, and the joyous reality that unfolds as we open ourselves to the constellations of statues and the worlds within ourselves — can guide us to the inner calm of correct opinion and to the threshold of a fulfilling spiritual practice.

## The Basics

This is a book about honoring Gods, and it is designed to be a practical work grounded in theory. While writing it, I had in mind an individual — perhaps spiritual-but-not-religious, maybe religious-but-looking-for-more, even not religious at all — who wants a connection to something greater than themselves and who is curious about Gods writ large. This person is not planning to join a group right now, nor are they committed to a specific cultural tradition that worships Gods. Maybe they grew up in a monotheistic faith or atheism and are trying something new, or perhaps they grew up in a continuous, Gods-venerating tradition that feels out-of-sync with where they are in life right now. Maybe they are somewhere in between. This work could also be useful for anyone who is looking to refresh an existing practice, especially those struggling with work-life balance.

This primer will give you generic resources and tools you need to get started with prayer, and it prioritizes what I believe will do that in a healthy way: small systems and small actions that, when taken together and approached mindfully, can create a sustainable engagement with the Gods. The word choice I have opted for in this book is intentionally uplifting and positive, as starting up or changing a spiritual regimen can be daunting for even the most motivated, not to mention those of us juggling intense periods at the office with our desire to meditate and light some incense every now and then. Deciding to do something about our desire for spiritual wholeness means that any reader has likely already encountered an overwhelming amount of information — some good, some misinformed, some wrong. You may think you need to be a specific type of person to pray or that it requires building specialist knowledge, when in fact most people who pray are not religious specialists — we’re ordinary people. Let’s embrace that.

Anyone, no matter what our background, can develop a fulfilling private spiritual practice, and that is why this primer exists. We will refer tothis fulfilling practice as *ritual*, and we will direct that ritual focus at the Gods.

Much as exercise is good for the body and meditation is good for the mind, revering the Gods is good for the soul. As with activities to strengthen the body and mind, establishing habitual ritual is good for its own sake — you do not need to pursue initiation, become a theologian, or seek leadership. A prayer practice is also not about magic spells or flashy Hollywood special effects. While a person may occasionally pray and ask for something specific, the primary purpose of venerating and praying to a higher power is to establish and deepen a relationship with them, a sacred dance between the devotee (in this case, you) and the holy.

Ritual practice and contemplation are simple: you set aside time, and ideally a small amount of space, to take pause and acknowledge the divine. A ritual can be something as simple as lighting an electric or flame-based candle before murmuring a prayer of gratitude for waking up to another day. It could be pouring cool water into a bowl or sharing a few sips of one’s morning coffee on the way out the door. It could be taking a few grounding breaths in front of an image of a God and spending that quiet, brief meditation cultivating fondness for and a desire to live up to the God’s good qualities — all before one’s young kids awaken.

For the purposes of this book, the divine consists of divine persons — Gods — who are each unique individuals. Often, when the average person thinks about Gods, the term “unique” becomes a proxy for “segmented into distinct offices” like Tupperware in the fridge after a big meal prep. Commonly-used resources online, including major dictionaries, encyclopedias, and so on, will tell you that we have a God for luck, a God for love, a God for healing, you name it. It is only after plunging into worship that we learn that many of these labels are inaccurate and overly simplistic, often applied by outsiders attempting to grapple with a system that is as dazzling and varied as nature itself. Every God is simply complicated, and as described by polytheistic philosophers and theologians, each of them is a boundary-less, unique window on the universe. Completely simple, each is an inner sanctum, a God who proceeds forth from that absolute unity. I pray to Apollon, for example, whose offices ultimately express that this God’s perspective is one related to harmony. The entire universe can be viewed through that lens, and the God can encompass everything. A devotee of another God may say the same thing about the one they follow, and our perspectives can coexist in mutual acknowledgment because we have the same foundational many-Gods outlook on the world. A devotee of Oðinn, for example, is focused on a God who shares many divination attributes with Apollon, and indeed is also connected to poetry, but they have very different contexts for their behavior. They are different *individuals*.

The Gods flow forth with abundance. Like floodwaters bringing life to a desert, they give rise to intermediary spirits whose identities are often preserved in folklore, folk practices, and habitual rituals. Beyond that, the dizzyingly complex interpolation of a myriad Gods into the receptive beauty of matter causes everything around us. Coming into harmony with the Gods, as Iamblichus taught, is the foundation of human happiness. This connection is something that cannot be taken away from any of us because it is innate. Like the image of Socrates as an artisanal sculpture filled with Gods’ statues, each of us *is* a unique window on divine reality. This uniqueness can be our anchor even as it emphasizes that we will each develop our perspective and connection differently. We can adapt how we live our lives through ritual, contemplation, and mindfully tuning into the seasons of the year and our lives. Becoming conscious of our connection to the Gods is a lifelong process, a dance around that anchor. Regular practice enriches our awareness of it no matter how much the winds howl when we check the news.

Despite calling a spiritual practice *simple*, I know that it can be very daunting to start one. Speaking as an American, many of us are taught that spiritual practice is something you start by paying money to attend a yoga class in a chic studio or filling a seat in a church beside other people who may or may not actually want to be there. Additionally, we think we each must declare ourselves to *be something*, and we pile label after label upon ourselves, mistaking the labels for a sense of meaning and belonging.

We may even feel anxious about praying at all: here, doing a prayer or small ritual every day can be viewed as strange or over-the-top because most spiritual communities that do that are not very visible. However, is far from uncommon among spiritual and religious traditions. Zen practitioners, if they want to move from casual to proficient, are expected to do at least two hours of zazen practice each day as a *layperson* (see note 16 at the end of Hidden Zen by Meido Moore). Muslims pray five times each day, and it is expected of everyone who is capable of it. In Shinto, those who keep kamidana (a type of household shrine for Kami, a word that describes a wide range of spiritual beings) give offerings daily, at least aspirationally (Chart, 2020).

In this broader context, taking two to ten minutes a day to devote to one’s spiritual practice is achievable to most people.

This primer will take that statement — again, *two to ten minutes is achievable* — and provide guidance to *make* it achievable.

## Recommended Supplies

Each of these chapters contains small exercises designed to connect you to an aspect of the topic under investigation. Sometimes, you will benefit from using ritual objects. I recommend having a small bowl on hand, a vessel (like a jar) that contains water, and a slip of paper with the God’s name written on it. If you can clear off a part of one shelf, that is ideal. If not, just use a clean surface and store your prayer materials in a clean box when you’re not using them.

Sometimes, no matter what, we run into challenges setting aside space. If you live in a college town, May is a great time to find tables and shelves cheaply (or for free), as students are leaving, and many of them are on tight move-out deadlines. FreeCycle and other no-buy groups are other options. If this is not possible, or if you are waiting for the right time to find a place for your shrine, make space on your floor or wall that you can dedicate to the Gods. I found [an online article about young South Asians coming to the United States and how they set up their sacred areas to be particularly inspiring for thinking about what one can do with limited space](https://web.archive.org/web/20220103123537/https://religionnews.com/2021/10/13/millennial-hindus-get-creative-with-home-temples-in-cramped-apartments/). IKEA recently came out with a cutting board with legs. It is inexpensive and is perfect for elevating an offering space ever-so-slightly, whether you are placing it on the ground or on part of a table or desk. There are also various places online that sell specialized “altar”/shrine furniture or tabletop devotional rests, ranging from items like imported Butsudan-style closed boxes (great for people with allergies; just choose something plain, without out-of-your-context Buddhist symbols, unless you honor the Buddha, to ensure that you are being respectful — the nice thing about these is the practical retracting table for incense and other offerings), items that look like hutches (also great for allergies), tabletop shelves, console tables and secretary's desks, and curio/trinket shelves.

If you are unable to establish a permanent shrine space, create a folder on your smartphone with images of the hearth Goddesses and divinities of interest to you. Turn on the phone feature that keeps the phone screen on when you’re looking at it. Put the phone on a stand on a clean surface, full-screen the image after going into Airplane Mode and hitting Do Not Disturb on your phone, and offer prayers in front of the image.

You can, of course, be more elaborate. Once we get going with the exercises, you will have opportunities to offer items like incense. When we move from talking about many Gods in the generic to actually choosing which God(s) to honor, you may want to purchase icons of those Gods or do research on Etsy or Redbubble or another online market to ballpark what you need to save up for one. There are also specialized shrine furniture items.

This book is open access for a reason: I am aware that we have a variety of economic situations. Cultivating your inner light — and connecting to the Gods — is something that is accessible no matter how simple your prayer space is. A set of small bowls and a pitcher for pouring will likely cost \$3-5 at Goodwill; used sauce jars will cost you nothing more than the time spent cleaning them out.

Many people end up engaging in spiritual consumerism, and they fill their prayer spaces up with material items to make themselves feel more spiritual. Everything you put in this space is a tool or a vessel to help you connect to God(s). Some parts of these spaces — particularly the images of Gods — are extremely sacred. If a fire or other disaster came, how many of these precious images could we put in our go bags? Probably not many. Be reasonable about your space and ask yourself questions about ergonomics, durability, and maintenance whenever you consider adding an icon.

## Starting Prayer

Let’s take a quick pause.

Be in a space where you will not be disturbed for two minutes. (It’s OK if this is your car, but the bathroom is not appropriate.) Close your eyes and take a few deep breaths. Silently count to four while breathing in and four while breathing out.

After a few cycles of breath, hold out your hands, with bent elbows, palms up. Your palms may either be together or apart.

At this point, you may either pray from the heart or use the words I am providing below. It is okay to open your eyes unless that is distracting for you.

> I honor and acknowledge the Gods I know, the Gods I do not know, and the good divinities willing to guide me. Please grant me what I need, and as I embark on a new beginning to study how best to approach you, may the actions I undertake guide me serendipitously to the place where I can be steady, happy, and truly free.

## Dedication

As one seeker of truth to another, I hope that the words in this book will be useful to your own voyage through life.

I will end the introduction with part of a prayer that I give every morning: 

Please, Apollon, let me find the still heart of truth at the core of all things. Please cultivate within me skill — in my poetry, in my prose, and in all of my actions, let all that I do flow forth from you. 

I will add to this a prayer to the Goddess Aletheia: 

May you, Aletheia, guide the reader towards truth and grant them a sip from your compassionate, abiding nectar, and may my words in this open access book be good enough to give them what they need for their journey.

This book is dedicated to Apollon and Aletheia.


