# Foundations

This chapter is called *Foundations* because we will dive a bit deeper into thinking about Gods — after all, they are the bedrock of everything in this book. It is also titled *Foundations* because the main practice at the end of the chapter involves the cleared-off section of shelf and small bowl from the end of the introduction.

We will look at what Gods actually are, and we will use Plato’s *Laws* to unpack some common pitfalls that happen when we think about them — mindsets that most of us may have slipped into at some point or other in our lives. We will then walk through the foundations of contemplative practices, rituals, and household observances. Finally, you will have an opportunity to do some brief veneration on your own. I encourage you to go through this chapter at your own pace and to take notes.

The advice in this book is *advice* — as long as you keep the fundamental point of respect towards the Gods in mind, you will be fine. You also have the opportunity to answer questions that I will occasionally ask. They are designed to open you up to possibilities and to brainstorm ways to apply what is under discussion to your life.

One option for you when encountering these questions — or, indeed, at any point at all in your reading — is to write, either in a journal or on your phone. However, if you are a busy parent, beholden to one or more demanding jobs with no work-life balance, or writing is just not accessible right now, that’s okay — modify as needed. Real life is not a stylized “what I do in a day” video, and it is definitely not a curated social media photograph. Think about these questions while you are in the shower, during your commute, or when completing tasks that don’t require a heavy cognitive load, like folding laundry. If something comes up that you want to keep hold of for later, use a note-taking app on your phone or create a draft email that you will send to yourself. 

## What Is a God, Anyway?

In the introduction, I quoted from two philosophers who were operating in a similar cultural context to each other. Thales, a Greek philosopher who was active before Socrates’ lifetime (and is thus called a “Pre-Socratic“), said that the world is full of Gods; Iamblichus, a Syrian fluent in both his native culture and Greek culture of the late third century of our common era, described a God’s existence as a given, but strangely so.

Not once did I bring up the predominant understanding of the word *God* in current times, which is often regarded as a *specific* someone — a singular omnipotent, omnipresent, omniscient being who is tied to the initiatory rites of revealed religions, a being only accessible when someone adheres to the correct holy book and doctrines. Sometimes in spiritual circles, people pray to the Source, Spirit, or the One as a way of being “generic” and “accessible,” referring to a single God while trying to avoid salvific baggage and bad memories. My reluctance to discuss this broader cultural material is partly related to my own background — my outlook on the Gods is Platonizing, which means that I do not believe that the first principle is capable of being described in that way. Even before my outlook was Platonizing, I grew up Neopagan, and my perspective on the Gods has always been very positive. I admit that I had significant misgivings about the theology I was first taught in the late 90s and early 00s: We collapsed Gods into one God and Goddess, ultimately Spirit, which never felt right. I hungered for more weighty theology, and that is what led me to Plato. This book is grounded in my perspective (although it’s designed to be accessible and useful to people who do *not* identify as Platonists or Platonizing). My second reason for *not* bringing it up in the introduction was that doing so would set an inappropriate tone for this work — this work is not a defense of Gods, but in praise of them. My third reason is that I want to push back against the totalizing understanding of words like *god*, *deity*, or *divinity*. Many of us assume what these words mean based on tacit things we learned as children, not on anything systematic.

*God* is used as a class term for a wide range of divine persons, sometimes accurately, sometimes imprecisely. Often, the term is used when translating indigenous terms for divine beings. The word *spirit* is used just as often. The Shinto term *Kami*, for example, describes a range of beings, many of them more reminiscent of divinities like nymphs, river spirits and Gods of place, or house wights. The words *theos* and *daimon* in Greek are equally problematic. A daimon is an intermediary spirit that carries out specific functions, but sometimes, a God is called a daimon in surviving writings from Ancient Greece! River divinities are usually referred to with *theos*, but are they a *theos* in the same way the Goddess Athene is? Are planetary Gods similar to other Gods even though most planetary bodies will perish when their stars go nova, or are they more like extremely long-lived nature spirits? Which, if any, beings from another language receive the term “God”? “Spirit”? “Wight”?

Ultimately, the answers to those questions depend on the biases of who is translating and if they have a specific set of beings in mind when they choose a word. This is one reason why Wikipedia is often not as good as going to a religious organization’s website (or, for decentralized religions, a few sites put together by different practitioners, ideally ones who are not in the same communication bubbles) to learn what its adherents believe. One helpful resource for comparative theology, including information about terminology and how cultures’ diverse views on what deities are and how to worship them inform their cosmologies, is Edward Butler’s *The Way of the Gods: Polytheism(s) Around the World*, based on a course he taught in 2021 (Butler, 2022).

Theological and philosophical exercises can help us narrow down what these categories mean. In Platonism, my theological framework, these elastic terms have been refined into four classes: gods, angels, daimons, and heroes. The final three classes are sometimes grouped under “daimons.” Each of the daimonic classes has less contact with the ultimate divine reality and more contact with variability and change. Divinities of the natural world and household inhabit the spaces “closest” to us. You and I are located at the level just below heroes — we are souls that incarnate in material bodies according to a long, regular cycle; a small sliver of us is permanent and godlike like the beings closer to godhood than us, and that is what we want to cultivate as *I* in a spiritual practice. Other philosophical schools, like Yogic philosophy, Stoicism, or Daoist philosophy, have different takes on this. Generally speaking, though, we are all trying to become as godlike as possible, to pull from Plato’s *Theaetetus* (176a-b).

The *strict* definition of God I will take — and the one I mean when I discuss our inner core of happiness and the statues within us — are those individual divine persons who ground the entirety of reality. They slip and slide into one another, boundary-free because they preexist both limit and unlimitedness. They are the ones whom we ultimately uncover in our practices. What is visible in breathtaking photographs from a space telescope or witnessed in the powerful fury of the world around us, or even the small actions of our daily lives, are all ultimately grounded in *their* astonishing foundation.

It is no wonder that Iamblichus wrote that “an innate knowledge about the gods is coexistent with our nature” and that they just *are*, but strangely so. All of the beings following from the Gods are nourished by their divinity, including the material world.

Most of the time, I will refer to other categories of divine beings as spirits, daimons, or divinities. I will also occasionally refer to ancestors. There may even be a triad of *Gods, spirits/daimon(e)s, and ancestors* in some of these materials, although ancestor worship is not the primary focus of this book. The spellings of *daimones* and *daimons* are interchangeable and simply note differences in how people shift the term from Ancient Greek to English during transliteration and adaptation.

* What are the definitions you have heard for the term *God*? How do they differ from what I have said?

* Try looking up the divine beings in a variety of traditions. What are the similarities? Differences? How well does the term *God* fit what you see?

## Mindset Lessons from Plato

One passage from Plato’s *Laws* can ground our understanding of the Gods even more. Plato’s *Laws* is a long city-soul analogy that describes how parts of the soul function in an embodied context, and it was questionably complete when Plato died — some parts of it seem rushed, and some analogies that are stridently hammered through by the speakers in later books are not as deftly scaffolded into earlier sections of the *Laws* as they are in Plato’s other works, especially when compared to the care he took in his other long city-soul analogy, the *Republic*. The *Laws* is said to have still been “on the wax” when he died, meaning that it had not been transferred to a more lasting medium like his finished pieces. In the Platonic tradition, Plato’s writings are approached somewhat like puzzles or myths to be interpreted by someone with skill, usually after years of preparation. A successful interpretation or commentary is inspired by the Muses and other Gods, identifying the signatures of truth within the words. Commentaries can be very different from one another while still communicating the same truth. It is the inspiration that matters, which leads to a successful weaving of Platonic concepts as an interpreter works through each piece’s components. These facts about how the *Laws* was transmitted make it a particularly tricky text to interpret.

Plato’s works (apart from his letters) take the form of dialogues — dramatic vignettes in which speakers encounter one another and ask questions, Socrates often one of the primary interlocutors. The *Laws* does not include Socrates as a character, but an unidentified old man called the Athenian Stranger, who is doing a pilgrimage hike with two other elderly men. Like the *Republic*, it is long and broken up into many sections. Book 10 of the *Laws* contains a conversation on atheism and piety, and most followers of Plato will, at some point, work this section of the *Laws* into a commentary, treatise, lecture, blog post, or social media thread to illustrate what proper and respectful conduct towards the Gods actually means. Now is the perfect opportunity for us to take a look at it.

The Athenian Stranger says:

> People [commit offenses] in one of three frames of mind: either lacking the belief [in the Gods] I mentioned; or second, believing that there *are* gods, but that they care nothing for human beings; or third, that they are easily won over by inducements in the form of sacrifice and prayer. (Laws 10, 885b)

In Platonism, an embodied rational soul has three parts: our thinking part, which can connect to the Gods and which survives death, and an irrational soul divided in two, the emotional and appetitive parts. The irrational soul perishes because our feelings and appetites are contingent on our specific embodiment (although depending on the person one asks, some aspects of the irrational soul can persist across several lifetimes; additionally, which traits are intrinsic to a partial soul and which ones depend on the body are still a lively area of debate). Our consciousness, and our self, is lasting. The three types of atheism correspond roughly to the three parts of the soul. A lack of belief in Gods is an intellectual atheism. Believing the Gods do not care or influence us is an atheism of care, an alienation from our own emotionality. Believing they can be swayed by offerings is an atheism of appetite. Proper piety requires unlearning these three traps so we can get out of our own way.

In the *Laws*, the Athenian Stranger discusses the lack of belief in Gods by referencing the planetary bodies and other types of natural phenomena as a way to jolt someone into reverence. In the present day, as someone with a love of modern astronomy, it was dissatisfying for me at first to read the discussion. At face value, his argument relies on outmoded ways of looking at the cosmos. We do not believe that the Earth is at the center — the planets orbit the Sun, and the Sun orbits the center of the Milky Way, which inhabits a local group of galaxies that is in a region of galaxies called the Virgo Supercluster. Our robots have been to the surface of Mars, and they probe the secrets of Venus. We may even have dedicated scientific probes orbiting Europa soon. Of course, in Late Antiquity, it was recognized by many religious people that the planets and the Gods were not the same. Each of the Gods is connected to every planet, and how we assign Gods to parts of the cosmos has a significant cultural component — it’s based on a God’s “conversation” with a culture as the culture and the God get to know one another, usually via bursts of inspiration and serendipity mixed with logical insights. Ishtar is associated with the planet Venus because that association expresses something about the Goddess and about the cultures who call that planet hers.

What bothered me is rooted in a common problem among many of us in the United States — our culturally-specific baggage. The dominant form of religion here has a strong anti-science contingent. When we think about Gods, especially in America, we are living in the shadow of the way Christian religious rhetoric operates in the public sphere. We are living in the wake of that religion’s Great Awakenings, most recently in the charismatic and evangelical waves of the mid-20th century with their prosperity gospel, cultivated distrust of science, and weaponized piety. While some of the televangelists, like Jim Bakker, have diminished in cultural relevance due to scandals and/or jail time, this remains a very vocal American subculture, and some of its ideas diffuse into the broader culture without us realizing it. For example, we are encouraged to view jobs as *callings*, a jargon word from Christianity for divine service, to prevent burnout when work gets rough. Often, our reluctance to engage with the divine is based on an inner fear that we will end up exactly like those toxic people, organizations, and cultural zeitgeists, or we are driven by the desire for social approval to not investigate Gods at all because “there are many Gods” is not a common position for someone to have in the United States right now, and we feel shame about our impulse to do so.

I was born in the late 1980s and experienced American public schooling in the 1990s and early 2000s. When I was in 9th grade, our biology teacher told the class — a rural school filled with students who had been taught that evolution was hubristic sin against their sacred texts — that he didn’t believe in evolution, but he was obligated to teach it, and we had better fill out the state exams in a way that the graders of the exams liked so our school could continue to get funding. I had been taught a non-Christian form of intelligent design by my parents — the divine created the cosmos, but science describes how the cosmos actually operates. In 2001, intelligent design was *also* a hubristic sin to many Christians. It wasn’t until a few years later that it became a tool for ultra-conservative Christians to sneak Biblical creationism into school curricula. For a few years, it was very possible to believe in a divine origin for the cosmos *and* to love and appreciate science, and to do so publicly in intellectual circles, without anyone caring.

I choose to read Plato’s Athenian Stranger as trying to jolt people into contextualizing their feelings of awe at the natural world. A deep, connected feeling in prayer is very similar to the feeling one gets when seeing the night sky in a place with very little light pollution or when we witness sunlight pierce through summer foliage in a breathtaking way. When it rains, I sometimes think of the diamond rain on Neptune, Uranus, and (possibly) Jupiter and fall into silence — it is that smallness, that sense of being tuned into what is common between the worlds, that makes me feel connected to the cosmos and in awe of all that is. The same patterns exist everywhere. Nothing is exotic, and the Gods and daimons fill everything, even the space between celestial bodies.

Let’s look at the Iamblichus I quoted in the introduction again. Conceding the Gods’ existence is “not the right way to put it” — but why? He continues with “an innate knowledge about the gods is coexistent with our nature, and is superior to all judgment and choice, reasoning and proof” and “[t]his knowledge is united from the outset with its own cause and exists in tandem with the essential striving of the soul towards the Good” (Iamblichus, *De Mysteriis*, I.3) — but how? And do all of us really feel that way, deep down? If we become quiet, if we progress from the turbulence of our daily lives to rest in that stillness, will knowledge of Gods just flow forth? Yes — in the quiet of sublime moments, when our defenses slip, we know that inner steadiness and connection to them.

The Gods are not their myths, and they crown the totality of the cosmos, not just Earth. They are the preface to existence, and what they have lain down forms the scaffolding of everything we see in the universe. The universe itself is a Goddess. She expresses her order in a beautiful array of mathematical brilliance, in both the mundane everyday of our lives and the half-grasped dreams of theoretical physicists. Looking to a physical object like the Moon or a planet (or contemplating a story about diamond expolanets) anchors us in a distant, still-corporeal thing — unless we use that knowledge of other worlds to jostle ourselves out of our subjective experience. It is that intellectual flight that we want to cultivate.

Beyond that discussion of how contemplating the natural world can draw us up to contemplating the Gods, the logic of belief and the Gods depends on several factors, ranging from philosophical schools’ doctrines to deep, indescribable personal experiences. Proclus’ *Platonic Theology*, Book I, explains how the Gods fit into the emanative system of Platonism and how they transcend existence itself, and he uses language that is most accessible to those who have already studied Platonic dialogues and doctrines. Were this book to dive deeper into Platonic doctrines, I might answer those questions by focusing my attention on the types of divine inspiration and the way that the structure of the Gods’ unfolding from ultimate unity underpins all that is, the Divided Line of the *Republic*, and what Socrates says about madness in the *Phaedrus*. I would also turn to Proclus’ *Elements of Theology* and explore a few of its propositions. Similar arguments occur in Stoic, yogic, and other works using the schema of each system — if you have a school in mind and are curious about it, I encourage you to jot down notes to remember for when we get to the Lifelong Learning chapter, and indeed I recommend you do that anytime I write about how I think about ritual from a Platonic standpoint. Spiritual and philosophical schools have different names because they have different positions on these things! What these diverse schools’ doctrines all come down to, though, is that looking for a “god of the gaps” or saying “god works in mysterious ways” are not correct statements.

Setting the Gods as the *base layer* of reality that gives rise to our material heterogeneity, regardless of the details of the specific philosophical and theological system, harmonizes all of existence with our unique personal experiences, or lack thereof; in each system, we are trying to reach a place where we can see both the forest and the trees without dissociating from either perspective. There are no gaps. Everything around us is produced by the Gods’ activity, a direct result of *them*. Learning about the Gods may be complicated, and exploring how their beautiful unity unfolds is a daunting and frustrating task at times. We don’t always agree with others on the details. What we uncover through deep thought and experience, though, is ineffable, an understanding that defies reduction into words. This is not mysterious — just challenging to communicate.

The second type of error, *believing that the Gods do not care*, comes from several roots. It is a way of cutting off our feelings and our emotional investment — insulating ourselves from everyday disappointments and coping with the seemingly random horrors that come to pass in our lives. Sometimes, we cultivate this mindset because we believe it is the best way to be realistic and logical. It is certainly true that the universe is enormous. We are each very small in comparison.

Plato’s Athenian Stranger said:

> The gods are on our side — as also are the guardian spirits — and we in turn are the property of the gods and guardian spirits. What is fatal for us is injustice, and arrogance allied to folly; our salvation is justice, and self-control allied to wisdom, and these are to be found dwelling in the living powers of the gods — though they can also be seen dwelling in us, just a bit — or something very like them.
>
> *Laws*, Book 10, 906b

In the system that Plato built, we are part of the organizational structure of the cosmos. We may be small, but we are each capable of developing agency and learning how to be as good and godlike as possible. Everything we see and touch, including ourselves, is part of the universe and the Gods’ collaborative creation of it. Gods, intermediary spirits, and our guardian spirits look after the whole and the parts within the whole. It is not conceited for a rose in a garden to know that its caretaker is checking its roots, pruning its leaves, and ensuring it grows well.

Sometimes, it’s admittedly hard to think about the whole. We are living on a small planet in a vast universe. Even considering Earth alone, the climate crisis touches each of us. Many of us live in less than perfect circumstances. We learn of new horrors near and far every day.

One challenge of the material world is that it has spatial and temporal extent, unlike the levels of reality that ground everything. The cosmos must unfold in time, and the way the pre-cosmic levels — whose components overlap and interpenetrate without spatiality or conflict — “freeze” into the material world introduces interference patterns. The evils we experience, the conflicts that devastate us, and the imperfections of the material world are all produced by this. When we incarnate, we make the best choice of life we can based on the options available to us and our disposition — and, like deciding between a tooth extraction and a root canal, sometimes having a healthy tooth is just not on the table. We can possess realistic awareness of our material surroundings while holding the Gods as good. Once embodied, we do possess some level of agency. We can make the options better or worse for the souls choosing lives on this planet in the future, including our own, through deliberate effort to tackle challenges and create the societies we want. This requires cultivating virtue and discipline, and it also requires cultivating the self-compassion that is crucial for taking care of ourselves as we strive to be better people.

Now, let’s talk about appetitive atheism, or the belief we can sway the Gods with offerings. Many of us who have looked at *National Geographic* or who have taken any world history class know that offerings to Gods are a huge component of many societies. When I originally learned about Ancient Greece and Rome, for example, it was explained that the elaborate systems of offerings were used to goad the Gods into granting us favor — and this idea was backed up in plays, epics, and other written pop culture works from the ancient Mediterranean. To this day, there are people who attempt to bribe the Gods to “offset” immoral behavior, like lies and theft. Believing this is possible means believing that the Gods are *not* good or stable. It means believing that they are vulnerable to appetites. Anything that has an appetite lacks something, which means it is not complete or perfect. People like that do not possess divine favor.

This apparent paradox is most apparent when we look at myth. In myths, Gods can have very strong appetites, with good or disastrous impacts. Many of these stories are violent. The stories force us to look deeper at what the myth is actually saying about how a God impacts the world. I will only touch on this briefly here, but I recommend reading Sallust/Sallustius’ “On the Gods and the World,” Chapter IV. In that chapter, Sallust discusses how myths operate and how we interpret them. He breaks down the levels of operation of myths into theological, physical, soul-oriented, and natural processes or materially-oriented. Additionally, there are “mixed” myths that operate at multiple levels simultaneously.

For anyone who has done literary criticism, the practice of mythic exegesis is very similar. For example, in one myth, Medusa is transformed and exiled by Athene after being raped by Poseidon in Athene’s temple. Athene then has a champion hero, Perseus, go to the lair of Medusa to kill her and bring back the head. Athene then uses this head to adorn her body. Athene is an intellectual Goddess — philosophical and wisdom-filled, virginal and separated from generative actions like sex. In the Platonic tradition, the soul begins its journey in contact with the wisdom, beauty, truth, and love in the highest places our souls can access. At some point, we lose our stability and plunge into generation, the term for the material cosmos of “coming-to-be,” and we lose access to that nourishment in the discordant fall. This descent is a necessary thing for us — our souls do it to complete the universe and bring the providence of the Gods into contact with what is always changing. However, there is a heavy price. The descent into generation is a descent into what is alien to us, a place where we can never exist without violence or pain. Poseidon is the Lord of the World of Becoming and is the ruler of generation — his violence is a symbol of how our soul experiences our alienating, violating descent. Medusa here represents the soul. She is depicted with wings, reminiscent of the metaphorical wings we lost during our descent. The serpents represent renewal, the many incarnations the soul must go through, all attached to her reasoning core. Her petrifying gaze renders every living thing around her stone, much as we all fail, in some way or other, to truly see the living beings around us. Instead, we transform them into objects and fail to see them for what they are — a monstrous disaster for both ourselves and others. Perseus, as a heroic spiritual intermediary, liberates Medusa from the body and returns the head (symbolizing the immortal part of the soul) to Athene, her proper guardian, completing the soul’s cycle. Medusa becomes harmonious with the Goddess once again through directing her petrifying activity in tandem with the warlike Goddess’ motions.

This interpretative analysis has several further implications that I could ponder: What does it mean to view the descent into generation as negative, given that the above interpretation includes elements of violence and loss? How do we view Medusa’s older sisters, who are both *wholly* immortal in some stories, unlike the mortal Medusa? Does the presence of these sisters preserve or present problems to the interpretation? If every God is good, how do we interpret the violence of descent, as a God (Poseidon) presides over that violence?

The *Prolegomena to Platonic Philosophy* clarifies that this approach to myth is far from uncommon — in fact, it is what is necessary, as stories that have been handed down for so long (like most myths) are a chaotic bag of symbols that is frequently overwhelming for any newcomer to unpack.

> [W]hereas the poets spun their tales at random, Plato says that anyone who is going to make up a myth concerning the deity should observe certain standards that will secure his readers from error. He should know that [the] God is good and never guilty of falsehood, neither through ignorance of the truth nor from deceitfulness; and that every deity is changeless and inflexible, since they can neither change for the worse nor for the better, the one being against their nature, the other impossible; it is against [the God’s] nature to change for the worse, and they cannot change for the better, being by their very essence superior to all things. This is what we mean by the propriety of his myths. Readers of myths should bear this in mind, to prevent the children from suffering harm: as soon as they plunge into the story, the good purpose should be immediately obvious from the contents, without their having to wait for the moral [...] if these rules are neglected, it will be difficult for the children to get rid of their misunderstandings. 
>
> Anonymous Prolegomena to Platonic Philosophy, β’ 7.20-33, trans. Westerink

If we think of our reactions to many of the myths when we first hear them — an example often used by Platonists is the one of Kronos eating his children — it is clear that we are like those children mentioned in the *Prolegomena*. For many myths, deriving insight is like making lemonade. We must squeeze out the potent, bitter-sour juice of what the poets wrote and use interpretation to sweeten it into a refreshing, nourishing beverage. We are often not exposed to myths in an environment that helps us understand what they are, which harms a seeker’s ability to think about the Gods in the terms Plato emphasizes here in the *Laws*. Even today, philosophers trying to help people through difficult interpretative work like this provide models for people to consult when they think about violent myths (Butler, 2019; Addey, 2000).

Contemplating and wrestling with what myths mean is something that anyone can do, even without a ritual space. It becomes easier to think through these things with time and attentiveness, and depending on which Gods one worships, one may have intricate puzzles to work through — it may take months or years of thinking about a myth before you feel like you’ve cracked it open. And then you discover that there is a completely new layer to the myth that you hadn’t considered! The process is *rewarding*, though, for overcoming a shallow view of myths and coming to a better understanding of how appetites are not what they seem in these stories.

Establishing that the Gods are not swayed by sacrifices and that the appetites they display in myths are not to be taken at face value can (and should!) lead us to wonder about prayer. Why do we pray to the Gods, then, if they cannot be swayed and if the stories *about* them being swayed are all to be interpreted allegorically?

Proclus is fond of saying that everything prays innately, each in its own way, simply by being what it is — like a sunflower following the sun. Every one of your actions since birth has been a prayer following some God or other, whether you are aware of that or not. Earlier, I wrote that our souls are at a level below the Gods and daimons (angels, daimons proper, and heroes). In this system, we are called “rational souls” — not in the sense of Vulcans on *Star Trek*, but as a jargon term that indicates our conscious awareness and ability to achieve dialectic and intuitive reasoning, which I like to refer to as *deliberative awareness* even though the adjective *deliberative* usually means something slightly different. Our rational soul, the summit of *who* we are, is immortal, attached to worldly garments that are not immortal. We are the lowest extremity of divinity, and part of how we express our nature is by incarnating in cycles.

We spend part of the soul’s cycle in close contact with the Gods, and we spend part of it down here. We are each brought down into the material world in a unique way based on our nature — to help others, perhaps, or to work through things until we regain a clear head. I will say more about this later, but we are each in the “series” of a specific God, and we thus inherit intrinsic attributes from them that impacts the choices of lives we make and what types of lives are going to be fulfilling for us.

Each of us could, in any incarnation, choose to wing it and go with the flow. Chances are, if you’ve picked up this book, that is not something that you want to do, but you can always close this and go live your life. Prayer — the *intentional* focus on the Gods — keeps our awareness anchored in our close, foundational contact with divinity. Physical tools we might use in prayer — the statues, the incense, the chants, whatever — support cultivating awareness and connection when used *wisely*. This is true regardless of how enormous and multi-pronged the challenges we face are. Prayer, and the spiritual impact of that intentional connection, keeps us rooted. It builds our resilience and invites us to contextualize *this specific life* — both the good and the rough times. It keeps us in contact with virtue and gives us a compassionate reality check that living lives is a process. It solidifies a growth mindset and nourishes our souls. The more mindfully we engage, the more we can adapt to what the world throws at us and bring forth good things of our own.

Additionally, the Gods still care about everything within the realm of generation. While writing about the ancient world, Andrej and Ivana Petrovic, in *Inner Purity and Pollution in Greek Religion*, quote the beliefs of Pythagoras about prayer as recorded by Diodorus Siculus:

> For he himself [Pythagoras] disclosed that wise men should pray to the gods for the good things for the benefit of the unwise, since the unwise are incapable of understanding what in life is truly good. (10.9.8) **He used to say that it was necessary in prayers to pray simply for the good things, and not to name them individually, such as for instance to pray for power, beauty, wealth, and other similar things. For often each of these things, when those who desired them acquire them, turning against them, totally ruins them.** 
>
> p. 63, emphasis added

Pythagoras’ mindset still rings true today. Because the Gods care for us, and because they are more expansive than us, they have more secure knowledge of what is good for us. I could pray to the Gods for money, power, and fame, but if it were granted, would it actually be the best thing for me? Probably not. Studies have shown that there are hard limits on the amount of happiness and fulfillment we can achieve through material and social wealth. Many millionaires, celebrities, and rulers are absolutely miserable, moreso than the general population. A good life is a life with enough hardship to avoid complacency and to encourage learning, but with enough stability to be able to thrive. Once a person has met their basic needs, it’s hard to know where that line is.

In another dialogue, the *Phaedrus*, Socrates and Phaedrus pray at the end for good things — a generic prayer that leaves the specifics of what happens up to the God, one that expresses humility about the limits of human knowledge. We do not know about the future.

You will find that many theological and philosophical systems have similar features — (often) multi-part souls, a complex relationship with mythic corpora, and a belief in the goodness of the Gods. If you have ideas about who you want to worship and which philosophical systems draw you, I encourage you to see how they handle these things. For example, traditional Nordic ideas about the soul involve many more parts than the Platonic version.

Now that we have discussed both the Gods and some common misconceptions about them, let’s get into contemplative practices. As the section above may have been a lot to read through, feel free to set this primer down and stretch, take a walk, do some dishes, or whatever else helps you digest ideas.

## Contemplative Practices

With or without setting aside physical space for spiritual practices, we can ground ourselves in the Gods through contemplative techniques. The title of this primer, *The Soul’s Inner Statues*, likely appeals to many who have tried some form of contemplation or breathwork before, as it names the soul and evokes some kind of interior spiritual experience. You may have tried a form of meditation using the Headspace or Calm apps, pranayama techniques in a yoga class, or the practice of taking a few deep breaths before or after engaging with something difficult.

### Foundations

If you haven’t tried meditation techniques, or if your experiences have not been what you wanted, here is some good news: There are many types of contemplative techniques, not all of which require sitting down and focusing on the breath, and online instructional materials are widely available for many types of practices. Breathwork techniques, chanting guidance, and guided meditations on focal-point-based mindfulness are some of the most widespread options.

Here are a few resources to get started:

* Anusha Wijeyakumar’s *Meditation with Intention: Quick and Easy Ways to Create Lasting Peace* seeks to provide useful foundations for anyone, including those who have experienced challenges when meditating. I took note of her book when I saw praise from people who have had difficulty meditating with other guidance.
* Headspace, Calm, Healthy Minds, or another meditation app. Calm and Headspace offer free trials, and Healthy Minds is free. Core features of these apps center on mindfulness meditation. You may also have access to mental wellness apps like Sanvello (which includes meditation timers) through your workplace or insurance benefits.
* For people interested in Stoicism, try out [Donald Robinson’s four Stoic meditation exercises](https://donaldrobertson.name/2018/03/27/four-stoic-meditation-exercises/) [(and here’s an archival link)](https://web.archive.org/web/2021*/https://donaldrobertson.name/2018/03/27/four-stoic-meditation-exercises/) or [the meditation app Stoa](https://stoameditation.com/).
* If you’re curious about contemplative activities in Platonism, I recommend Mindy Mandell’s *Discovering the Beauty of Wisdom*, which contains some contemplative techniques.
* David Nowakowski has made [a primer on techniques available on his website](https://davidnowakowski.net/meditation/), and I recommend I recommend those resources, which include both Stoic and general passage contemplation meditations. [(Here’s an archival link.)](https://web.archive.org/web/2021*/https://davidnowakowski.net/meditation/) 

To time a meditation, you can use a dedicated phone app, the timer on your watch or fitness tracker, the timer function in your clock app (with a non-jarring timer noise), or even a classic physical timer. Calm, Headspace, and other paid apps have trials that you can use if you want some guided direction when just starting out. 

When starting a contemplative practice, I recommend having a plan: Know when you will do it, which tool you will use to time it, and the technique(s) you will use during the brief period.

### Contemplating the Divine

I do daily meditation as basic mental hygiene, as do many people — ten-minute shower, ten minute-meditation, and my body and mind are ordered and ready to face the world. If we want to reach inside and open the gate to the statues within — and rest in the Gods who wait just beyond our breath — we need a divine set of focal points in addition to general mental wellness practices.

#### Contemplating the Divine Being

Instead of focusing on your breath, you might focus on a deity, household spirit, or ancestor you want to connect with — and don’t worry if you don’t know *who* quite yet.

This can be made a bit easier by using an image. If you have a smartphone, put your phone in airplane mode and make sure you have a few images saved in your photos. Create a dedicated folder so you can find them easily. My Android phone has a feature that keeps the phone on when I’m looking at it, and if yours can do similar, all you have to do is pull up one of those photos and make sure your phone can see you. You could also purchase a bookmark or postcard featuring the deity, use a printout image, or invest in artisanal divine images. (Do not go overboard on Etsy, especially if you are just starting out and don’t know which deities you want to worship. That said, I have found some excellent wood bookmarks of Gods — both Norse and Hellenic. A few shops have excellent wood icons available, too.) It works well if the deity is looking out of the image towards you because you have the illusion of eye contact.

While focusing on the deity, just breathe. You can close your eyes if you like while holding the image in your mind. Using your meditation or phone timer is useful here.

Often, when I meditate on a God, I start with prayer beads. Because I am not a crafter, I have usually purchased these beads, often from sellers on Etsy or another site for small businesses and artisans. The beads that work best for me for most contemplations are short strings with between nine and twenty beads. I have selected short phrases from content I have come across for various Gods, and I have pored through other texts to find short snippets that I want to use in some other cases. Some examples of phrases I use are:

* Οἰγνύσθω ψυχῆς βάθος ἄμβροτον· ὄμματα πάντα ἄρδην ἐκπετάννυμι ἄνω. “Let the immortal depths of my soul be opened. May all of my eyes stretch completely upward on high.” This is from the *Chaldean Oracles* fragments, a slight modification of a translation by Ruth Majercik of Fragment 112.
* Βίος Βίος Ἀπόλλων Ἀπόλλων Ἥλιος Ἥλιος Κόσμος Κόσμος Φῶς Φῶς. “Life Life Apollon Apollon Helios Helios Cosmos Cosmos Light Light.” This is an inscription [from the Boreikean Society, circa 300 BCE](http://philipharland.com/greco-roman-associations/dedication-to-bios-life-by-the-boreikian-society-300-bce/) [(archival link)](https://web.archive.org/web/20210508170106/http://philipharland.com/greco-roman-associations/dedication-to-bios-life-by-the-boreikian-society-300-bce/), which is used by several of us in the modern worship of Gods in completely different ways. I personally use it to get closer to Apollon, whom I associate with black holes.
* There is a chant, Oὐδὲν ἄρα οὕτως βεβαίως δεδήσεται, οὐ νόσῳ, οὐκ ὀργῇ, οὐ τύχῃ οὐδεμιᾷ, ὃ μὴ οἷόν τ'ἔσται λῦσαι τῷ Διονύσῳ, that is used to request the encosmic ruler, Dionysos, for cleansing and a release from bonds. It translates to, “Nothing can be so firmly bound by illness, wrath, or fortune, that cannot be released by Dionysos.” It is highly effective in prayers and rituals [and was originally shared here](https://krasskova.wordpress.com/2017/12/05/public-service-announcement/).
* Drew Campbell, who published a book in 2000 about the adoption of theistic practice centered around Hellenic Gods in the United States, [created several chants for Gods, including Zeus, Artemis, Athene, and Hera](https://web.archive.org/web/20120506135235/https://www.ecauldron.net/dc-mousike.php), drawing from inspiration and ancient texts. I sing the one to Artemis when I pray to her, although I use a different melody.

Keep in mind that the Gods I worship are primarily Hellenic, so I have been drawn to phrases in Greek or translated from Greek into English. You can identify chants and prayers for your own practice that draw from the sources that make the most sense to you. The author of *Ásatrú for Beginners* recommends several phrases from Norse source texts to use in ritual; he suggests them as prayers, but they are short enough to use for chanting, too (Nordvig, 2020, p. 63). A few sets of prayer beads I purchased came with prayers, and I use those prayers (with modifications) for Eir, Belesama, Apollon, Hermes, and several other Gods. After chanting for several minutes, I come into stillness while maintaining mental focus on the God. When focus is very hard, I visualize the actual words of the chant, which makes a big difference for me.

Sometimes, I don’t start with prayer beads. I start by reading a poem — a hymn translation from the ancient world or a more recent composition — for the God or thinking about aspects of the God in epithets and culture before I drop into stillness. Epithets, or devotional titles, are common in many cultures. Fpr example, Apollon can be called the Far-Shooter or He Who Wards From Afar. They often come from place-names, mythic associations, or something that the God is considered to be especially good at, and they can be chanted in either the original language or something else. I find that this is grounding — like the image, it improves my focus. Depending on when I do this during the day, I may light incense or give the God a libation.

You may want to take some notes on chants you want to investigate based on the God(s) you are considering praying to. Hold onto this for the chapter on doing research or go ahead and get started — it’s up to you.

#### Contemplating a Text

Contemplating a text is a classic in many religious and spiritual traditions. It can be done in a traditional meditation; with a pen and paper at a desk; or at a computer — airplane your phone, turn off all notifications, and ensure that you are difficult to contact while you’re working through your thoughts. Spending a few minutes with a task before you go on a walk or bringing a reading with you to the gym are also great options. While I sometimes contemplate passages from Platonic texts immediately after my morning prayers, my days are too hectic to do that all of the time, so I usually think about passages from what I’m reading while doing dishes or commuting. You know if you are a restless thinker who needs to be doing something tactile while your mind is working.

To start, say a small, heartfelt prayer to the God(s) in the myth or text. Read the passage you want to work with and jot down what comes to mind. Highlight any passages you want to spend extra attention on, and pause whenever inspiration strikes. You can come back to the same text many times. You can use specific passages from your notes as seeds for a seated meditation. Sometimes, if you alternate between taking notes on myths and contemplating a divine image, elements of the myth will arise spontaneously in the mind while you are doing the seated meditation on the God.

#### Breathwork and Adapted Meditation Techniques

For those who have exposure to and practice with other forms of meditation, doing pranayama/breathwork or using meditation techniques like body scans, noting, lovingkindness, and so on can sometimes be adapted to a contemplative spiritual practice like this.

Headspace, Calm, and other meditation apps have guided tutorials on these techniques, and YouTube is another option. Pranayama techniques are from South Asian religious traditions, and people most frequently pick them up from attending a yoga class in person or online. Look up local opportunities in your area if possible.

There are also techniques called “grounding and centering” that I learned growing up. A person envisions that they are rooted into the ground like a tree, drawing up nourishment from the Earth, and drawing down energy from the sun or sun and stars as the central point of this structure. It can be beneficial to do techniques like that if one is feeling scattered and distracted. Grounding and centering techniques are used in a variety of modern spiritual and religious traditions because they work well. You can find guided exercises made by people from a variety of backgrounds on YouTube. Local pagan and polytheist groups may also teach these techniques during open-to-the-public rituals, if they have any.

Sometimes, I do breath of fire (a pranayama technique, kapalbhati) before contemplating a God. I do meditative visualizations in which sunlight, starlight, or moonlight are filling the body, depending on the context — honoring the solstice or full moon, for example.

## Ritual Practices

Ritual practices are everywhere in contemporary culture — glossy checkout magazines, online-only publications offering the gamut of self-care options, pop culture spirituality blogs, mainstream occult practices, corporate cultish bonding exercises, and so on. One app I have used in the past for personal development sometimes called my morning, workday, and evening routines “rituals” — and there wasn’t even a preexisting option for adding prayer to a routine.

In *The Soul’s Inner Statues*, we will use “ritual” for any activities we do to connect with Gods, divinities, and those who have come before us. A ritual in this context is a set of routine practices we use in this context.

It is possible to pray without something being a ritual. Sometimes, when I am outside after work in the winter, I see the rising full moon, and I often murmur a quick prayer or press my fingertips to my lips and forehead to acknowledge the lunar Gods. There is no ritual involved in that spontaneous reverence, and honestly, it’s fine to keep some practices simple.

## Hearth, home, and ancestors

Who you pray to out of affinity — this God, that Goddess, someone else — are often like friendships that change and fade over time. A few are continuous, and many are transient. Household worship is very different because you live somewhere. Even if you are in a liminal space — without a home, living in a dorm, or traveling — there are Gods who preside over liminal spaces who can be deeply enriching to pray to.

The core of household worship is making offerings to household Gods, often a hearth Goddess and one or more divinities who preside over things like property, storerooms, and abundance. (Indeed, we could characterize the reverence of many Gods *as* connected to and anchored in our homes. A stylized hearthfire symbol is the perfect symbol to characterize what *The Soul’s Inner Statues* aims to achieve, as it symbolizes the hearth and the divine flame within us.) Examples of household divinities are the Penates (Roman), house wights (various places), Agathos Daimon (Greek, meaning “good spirit/intermediary“), Tykhe or Fortuna (Greek and Roman), the Kitchen God (Chinese folk religion), or a household-focused aspect of a God. Every God technically is a unique perspective on the entirety of everything, so you *could* worship any of them as your household God. However, the specific preexisting associations people have made between a God and a set of activities are powerful expressions of how that God operates in the world. They are also easiest to “tap into” for people who have never worshipped Gods before. Some Gods with well-established household aspects, like Apollon, Zeus, and Hermes, have specific household functions — Zeus of the Storeroom, for example, is literally the God who keeps your cozy duvet inserts and tea safe; Apollon of the Streets protects public spaces and harmonizes the home with the exterior world through the threshold boundary. Hermes, as a liminal God, is highly relevant to boundaries. The Norse Goddess Frigg and the Goddesses associated with her (the Handmaidens) have associations with many domestic tasks.

Household worship can involve considerations of one’s ancestors of affinity, culture, or personal heritage. Depending on your ancestry and your relationship with said ancestors, this will likely cause mixing and matching. For most people, including me, it is not an instantaneous thing — it builds slowly over time, woven by synchronicity and effort and duty.

As an example, let me tell you about my own fact-finding mission. After deciding to bring my practice more in alignment with my values, for some months, I experimented with praying to Frigg (Nordic), Nantosuelta and Brigando (both Gaulish), and Hestia (Greek) as hearth Goddesses. I primarily worship the Hellenic Gods (but I am not Greek), and I started exploring what it would be like to pray to household deities related to my roots. While the Neopagan community I had grown up in had done a lot for Brigid (who is related to Brigando), that prayer practice wasn’t fruitful — it felt forced. I reevaluated what I was doing through a combination of thinking, ranting in journals, and divination. Ultimately, after a contemplative experience in which I felt Hestia’s presence very powerfully, and after months of not having that in the way I was trying to blend everything, I realized that Hestia, and her Roman counterpart Vesta, whom I identify with Hestia strongly (not everyone does), was the bedrock of my hearth. Frigg and Nantosuelta are also important to me — Frigg is the Goddess I think of when I think of my matrilineal ancestors’ strength, and Nantosuelta reminds me of the fecundity of the apple country close to my heart in Upstate New York, where my maternal family is from and where I spent my childhood. They are important household Goddesses for me, too. As a Platonizing polytheist, revering Hestia makes sense with where I am coming from. This is much more harmonious.

Now, what do I mean by *fact-finding mission*? It means deliberately putting yourself into a new situation and actually trying something, trusting that the Gods will lead you where you need to be. Whenever I make ritual changes, I usually give it a few weeks for me to settle into the new routine. New routines are always a bit awkward in the beginning! Then, I pay attention to signs in my body, emotions, mental impressions and experiences, and serendipitous things that happen during ritual and ask myself if these are signs that my spiritual practice is in a *good state* or if it’s not clicking. A persistent feeling of frustration is generally a sign that it isn’t working out well. Some will do divination or seek specialist help when working through this. As shown in the example, I usually do journaling and brainstorming, and I have a very deep spiritual reading practice that often illuminates what could work better right when I need it.

It is *perfectly fine* to do fact-finding or to not be sure about where one will land when one is just starting out — or even to revisit long-held practices that one never worked through systematically before.

For reflection:

1. Do you already know of any hearth deities? What about home divinities? 
2. Who interests you the most? Look them up. Alternatively, [look at this list of hearth deities from around the world](https://en.wikipedia.org/wiki/Household_deity#List) — just check the Talk page if you want to see what went into the contributors’ creation of the page.

### Home during college

Household worship, from a practical standpoint, can be very simple. I have maintained a sacred space in my living area since I was twelve or so. In eighth grade, I made a bench in shop class that became my small floor-level shrine until I went to college, when I lived in the dorms. Incense and candles were forbidden for fire safety reasons, but I often had a small space on my bookshelf that was marked as “sacred” — even if I often neglected it. As most young adult students do, I moved a lot: dorm room to dorm room, apartment to apartment, between my family’s home and transient student spaces, and my spiritual life was like an untamed, rowdy horse. You can *still* have hearth deities during this period of your life and keep a shrine, even if it is very simple. Libations and electric candles go a long way. You may, however, prefer to focus on deities related to education, especially if you are living in a dorm setting. There wasn’t much advice on how to be disciplined about a spiritual practice in new adulthood when I was young; hopefully this book helps future generations.

### Worship Without Being Creepy About Heritage

In Rumi’s “[The Guest House](https://www.scottishpoetrylibrary.org.uk/poem/guest-house/),” the poet frames our lives as transitory places:

>This being human is a guest house.  
>Every morning a new arrival.
>
>A joy, a depression, a meanness,  
>some momentary awareness comes  
>as an unexpected visitor.

Even before I encountered that poem, I had been contemplating the idea of our lives as temporary places. As someone who reads Plato and who holds to Platonic teachings about reincarnation, I know that our families, lineages, and personal contexts change from lifetime to lifetime. There is no steadiness in them. Parodoxically, in Plato and the Platonists, there is a strong emphasis on meeting the context of your current life where it is and paying your respect to Gods and ancestors. This dates back to Epictetus the Stoic and to Plato. However, this is ideally like being a guest in someone’s house: the family may last a long time, and so may your region’s people and/or culture, but *you* will not be there forever. You need to leave the family better than you found it, and you need to be mindful that the family is not *you* — you are an incarnating soul.

When I started to embark on incorporating ancestral practices, it was important to me to do it without being creepy — it’s contextual to this lifetime, so how does that translate into practice? The ultimate goal for anyone incorporating such practices is to ensure that one is not neglecting important divinities and Gods. Reaching out to ancestral deities is an act of repair for those of us whose ancestors ruptured ties to Gods by converting to an evangelizing, one-true-way religion. In the popular TV series *The Good Place*, interpersonal obligations were built up through the phrase “what do we owe each other?” — also the title of a philosophical book that presumably is working through what our web of connections and obligations mean. The way it played out on the TV show involved characters learning etiquette and mutual respect. If we want to set boundaries between ourselves and absolutism and intolerance, changing one’s worldview **from** one of either rootlessness or clinging attachment **to** a worldview of *repair* and *compassionate duty* can work wonders. Obviously, there are many times when the answer to “should I be worshipping you, Gods who may have been worshipped by my great-great-great-great-great grandparents?” is no, and that’s fine. There are plenty of people who have satisfying spiritual lives joining a tradition that has nothing to do with where they are from.

Because we are worshipping Gods and divinities who are individuals and not archetypes, an analogy can be drawn to reaching out to family after an estrangement you inherited from your parents — it may be awkward, it may fail, but it’s worth it to phone and see what happens. For example, if one’s ancestors lived in areas where they likely had a Lararium (a household shrine for the Lares) eighteen hundred years ago, trying that out again may be a useful first step. If your family now lives in an area where people had Lararia eighteen hundred years ago, but you ultimately trace your roots elsewhere, you should also feel empowered to explore having one — you live there now, regardless of your ancestors’ origins, so it’s part of your cultural history, too. I do not recommend basing something as important as your relationship with the Gods on 23andme results, with the caveat that some people whose ancestors experienced human trafficking or who were orphaned or adopted may find genetic data helpful for reflection when used responsibly — in a limited fashion and without neglecting other factors. Ancestry is an amalgam of personal heritage and cultural heritage: Thinking back to the example in 2.5, home and ambient/regional culture, family history narratives, and fondness for a set of Gods ultimately shape us the most (never underestimate the power of chance encounters and fondness-at-first-sight for a God). You will get much more out of exploring how your practice is in conversation with those elements than you will from slicing and dicing your genome. Real human beings are messy, and we do not fit into boxes. “Know thyself” is a difficult journey, and there are no shortcuts.

There are other ways our current incarnation can impact us. In the *Phaedrus* commentary taken down by Hermias during one of the Platonist Syrianus’ lectures fifteen hundred years ago, the text comments that someone will often reincarnate into a family to resolve injustices from generations ago. When we incarnate, we pick what is best for our soul given our options. What is best for us as souls could include repairing such ruptures and the harm caused by previous generations. *We are in a guest house:* Doing this is for the good of everyone, no strings attached, so the fact that we may not incarnate into the group benefitting from our hard work should not deter us from doing the correct thing now.

In other words, reaching for ancestral traditions is healthy when it comes out of a desire to do what is just and to repair what was broken or cast aside. We repair our relationship with the Gods and we commit to transmitting it to those who come after us. We should ask ourselves *how, why, and for whom* as prompts to deepen our practice without succumbing to hate, division, and false senses of superiority. Questions like these can also heal a disorienting sense of unplacing when they are approached from a place of compassion, fierce honesty, and care. While the answers may create some very personalized practices, the process will lead to a personalized ritual practice that is *solidly grounded in piety* according to what is most just in each person or family’s specific case.

Admittedly, in some cases, Gods were transmitted to us from another culture so many generations ago that they feel like ours, and we need to be mindful about recognizing that the living descendants of the ancient cultures they come from have their own histories and relationships to the same Gods — it’s part of being culturally and globally aware. In America, most of us, regardless of our background, trace our cultural history to what was going on in Britain four hundred to two hundred years ago when they were an imperial power taking everything from everybody. Those of us (non-Greek) Americans who worship Greek/Hellenic Gods do so because British people really liked them during the Renaissance and Early Modern period, and fluency in Greek literature and its motifs proved someone was cultured even after the texts started to be translated into English. Greece is 1800 miles away from England. It is a very different culture. The same goes for Britain’s Egypt craze and its impact on the accessibility of information about Egyptian Gods. Chaldeans, Assyrians, Hellenes, and other identifiers we read about in history books are the names of cultural and/or ethnic groups that still exist today.

### Today Is Not Yesterday

Iamblichus wrote in V.25 of *On the Mysteries* that the traditions are not “just a matter of human customs” driven by convention. Rather than originating from us, the “God is the initiator of these things, he who is called ’the god who presides over sacrifices,’ and there is also a great multitude of gods and angels in attendance upon him.” Every holy place, people, or sacrifice has a divine leader such that “when we perform our sacrifices to the gods with the backing of gods as supervisors and executives of the sacrificial procedure, we should on the one hand pay due reverence to the regulation of the sanctity of divine sacrifice, but on the other we may have due confidence in ourselves” because we are approaching the Gods as the Gods intended us to. Iamblichus cautioned against changing names and ritual elements.

Simplicius, when discussing the best way to venerate the Gods according to the Stoic Epictetus, echoes what Iamblichus said:

> We must perform everything that pertains to divine honour with purity, and not in a slovenly way [...]. Nor should we do any of these things without care, [Epictetus] says, so that we omit one of the necessary parts, or confuse things, or change them, through negligence. If you delete the letters of a word, or rearrange them, the form of the word does not occur; similarly in the case of divine words and deeds, if anything is left out, or rearranged, or confused, divine illumination does not occur — instead, the negligence of the one performing the ritual waters down the power of the events.
>
> Simplicius, *On Epictetus 27-53*, trans. Brennan and Brittain, p. 67.

When you read the words above, keep in mind that the situation in Late Antiquity when Iamblichus (who died in 325 CE) and Simplicius (alive in the 500s CE) were active was not the same as ours. Case in point: You are reading this book to figure out how to pray, but if we had had no disruption, you would have learned this from the adults around you when you were a toddler. That is one reason why this book is free (if you’re reading it online) or priced at the cost of materials and distribution (if you’re reading the print).

Whereas we only have the names and ephemeral archaeo- logical evidence for some Gods, our predecessors usually had access to a lot of contextual information. A person worship- ping back then had deep connections to the rites conducted in a region, rituals that often predated historical records. As Christianity spread throughout the Mediterranean and into Europe, the Middle East, and Africa, the destruction of temples, cultural heritage materials, divine images, and our connection with the Gods our ancestors worshipped has led to a colossal amount of knowledge destruction. This violent iconoclasm and loss is ongoing in places that are targeted by Christian missionaries for conversion, often upheld by toxic Western narratives about “primitive” people and practices.

To worship Gods, many of us are taking a look at fragments of what was once practiced — small traces of Gods’ worship in historical times — and using our best judgment to apply what we know about that to the present day. We are identifying how we can move forward. In addition, many of us encounter Gods in places very alien to the original context in which they were worshipped — how do we know Inanna after reading *Gilgamesh* or Artemis after perusing Callimachus when we have no other connection to them? We are starting fresh from our own context.

Sometimes, a person can get lost in the weeds of historical record and miss the object: connecting with a God. They view the words above as being directed at *us* and not at the contemporaries of the ancient philosophers. Simplicius continues:

> What is most important is the concentrated eagerness of the agent, along with [their] knowledge, as it is with the fulfilment and perfection of other things. But how can someone who is patently careless and negligent about things concerning [the] God be in earnest about anything that is necessary? Nor is it right for us to approach ‘impiously’, he says, — that is, without reverence. For the more honourable and worthy of reverence we consider the divine rituals to be, the more we participate in them as such; and if we subordinate ourselves, in so far as we are able, to the reverence of [the] God, then we too are magnified.
>
> Simplicius, *On Epictetus 27-53*, trans. Brennan and Brittain, p. 67

It is very clear that Simplicius’ main concern is people slackening away from the rites at the time in an environment where frequently only a few people retained the knowledge of what had, before Christianity, been widespread practices for Gods. It had been made illegal to engage in the worship of Gods in the Roman Empire, although many tenacious people risked their lives to preserve piety. This was also Iamblichus’ concern, albeit the situation had not reached a crisis point in his lifetime, and rites for Gods were still legal — his theological writing is a highly respected work for those interested in the theology of many Gods.

Ultimately, we are not the ancients, and our goal is to establish a connection to the Gods we want to worship *here*, in our own cultural contexts. We can draw what we can from the past, we can pray for insight from the Gods to find the right rituals and words for our liturgies and daily practices, and we can look to living cultures to get an idea of what adaptations to the modern world religions have.

The techniques I am providing for prayer in *The Soul’s Inner Statues* are grounded in today, in the *now* of the Gods. They are designed to be as general as possible (although I know that my Platonizing perspective has an impact on how I frame this advice) and to help you think about your own customized practice. We cannot go back. In the 21st century, it is important to look forward and adapt to our environments.

We are also given this by Simplicius to encourage us to think about our own lived context:

> ‘It is fitting’ for each of us to do these things according to the customs of one’s country. For [the] God is always simultaneously present everywhere, with all of his divine powers. But we are limited to one form among those many forms produced by [the] God, the human form, and within the human form are limited to one form of life for now and one choice of life, and are divided up into a little portion of the universe and of the earth itself. So different people partake in a different instances of divine goodness, and they do so in a different way at different times and places. You can at least see that when it is day with us, it is night for others, and when it is winter in one place, it is summer in another, and that these sorts of flora and fauna prevail here, and elsewhere other sorts: the earth and the things on it partake of divine goodness in a divided way. So, just as the places and lives of people differ, each person propitiates the divine through the rites which God revealed and which they themselves became aware of through experience, rites which differ in their occasions and methods, and in the variation of the objects sacrificed and offered. And when the affairs of [the] God are celebrated according to [the] God, a particular activity of divine illumination becomes evident on certain circumscribed days which is not at all evident on other days: the sick are cured, and sometimes some beneficial events are foretold. A difference of time, or the consonance of place and method with what is uttered, wrought and offered — all of these have a great effect on divine assimilation.
>
> Simplicius, *On Epictetus 27-53*, trans. Brennan and Brittain, p. 66-67

To adapt the worship of the Gods to today, we need to live the spirit of what Simplicius said about the need to revere and honor the divine rituals — we want to build something new that we can share forward as the new bedrock of the future.

-   Start by **researching** Gods — we will cover some tips on successful adult learning in a few chapters, but for now, pay attention to the traditional associations and symbols. As you work through the chapters of this book, if you jot down notes about any deities you want to worship, use that space to collect small pieces of information about their traditional festivals, the types of symbols they are shown with, any divine nicknames (epithets) they have, and so on. Check for information about how these Gods were culturally transmitted into your region. Was it in antiquity? The Renaissance? After World War II? Are they from your area? A combination?

-   Once you have researched, start **reflecting**. Brainstorm how those descriptors relate to your own lived experience. Think about new directions based on your region or the history of how the Gods became known to your area. Also consider specific customs you have in your culture and ways the God(s) could be brought into conversation with those.

-   Pray to the Gods for assistance in **designing** your home practice. Use this information to select the ritual elements and traditions you want to start with, what you will offer, and when you will do offerings.

-   Start **listening**. Establishing something from scratch is iterative. It is a conversation between you and the Gods. If you feel stuck, go back to the reflection and design stages. Writing this book helped me work through a lot in my own practice, and I have gone through five or six iterations of my daily household ritual in the past year! It’s okay to be a work in progress as long as your goal is authentic, open-hearted reverence of the Gods.

If you follow these bullet points, you will be well on your way to mitigating the problems with getting lost in the past. Focus on rootedness, and remember that trees’ roots are not deep the moment they sprout. Many things of deep value in this world take time and careful attention.

Please note that you are not expected to do all of the above immediately. Bookmark this section to glance at when you do the exercises at the end of the next few chapters.

#### What About the Awful Things?

While the initiator of rites is a God, human beings can never perfectly receive what is intended by the Gods. When we look at archaeological evidence, the written record, and other sources, we may notice that the ancient world was sometimes a brutal place, and this occasionally shows up in religious practice or the analogies that philosophers use when talking about first principles. Slavery, treating women like chattel, overly punitive legal codes, and other social evils were rampant.

Specific places’ social inequality structures are not things that the Gods are responsible for, and indeed, the closer we look, the more we discover that the past’s relationship with its own evils is complex. In the Platonic tradition, evils are a phantasmic, not-really-real, parasitic occurrence caused by the extreme spatio-temporal partiality of the natural and material world. As our behaviors and social norms are parts of the natural world, the ways we venerate Gods are no exception.

The generations that created these traditions may have had very poignant insights about the divine. As our predecessors were human beings, just as we are human, it was just as easy for them to ignore heinous injustices they were habituated to accept from youth as it is for *us* to ignore the injustices of our own time. (How many of us are wearing clothes or using devices that may have been produced by human trafficking or child labor?) However, pushing back against these evils is not a new thing. The bhakti movement in South Asia had factions, still existing today, that worship Gods like Shiva, believe in the spiritual equality of men and women to the point of having no menstrual taboos, and despise casteism; this dates back at least a millennium. Women in Mediterranean Late Antiquity suffered from harsh sexism. However, in Platonic and other philosophical schools, girls were educated and could even grow up to teach, like Sosipatra and Hypatia, because Plato taught that women have the same virtues as men, and philosophers seemed to take the idea of educating their daughters seriously. There have always been resistances and fresh, pious directions for people to take because the Gods are good. They open up these ways for us even if our broader societies don’t always embrace them.

Often, people look at the past and are struck still — angry, often shocked — by it all. It’s our job to learn from this messiness to tell the narratives we want to tell and to crown our ancestors — literal, spiritual, or elsewise — through the power of our actions in the present.

When we light incense or give a libation at a household shrine, we are all equal to one another. The Gods do not discriminate based on your race, ethnicity, social class, disability status, sex, sexual orientation, gender, caste, and so on. When we pray, we are praying as souls reaching out to a God. All of us belong. Plotinus encouraged each of us to never stop working on our statue — to always be willing to be better. That is what actually matters.

As we build the rhythms of our fresh traditions, coaxing them out of the Earth like a holy plant that has just germinated, we can ground this growing relationship in trust. The way to interpret what Iamblichus said about the Gods starting these rites — in terms of us *today* — is to *genuinely* focus on the God as the starting point. Have trust in the practice and in the process. Read about the Gods, learn and apply the information about virtue and conduct in later chapters, and keep the Gods at the center of any corrections and changes you make to rituals. We can always ensure that the core keeps its integrity even if peripheral elements change — such as who in the family is considered the *paterfamilias* in a gay or lesbian marriage, whether or not it is appropriate for us to adapt a specific ancient festival to a private ceremony in our home today, and so on.

Ultimately, your practice is your practice. What you do at your shrine, as long as you are being a respectful, pious, and decent person, is just as good as anyone else’s effort. Sometimes, people who love their Gods, but who face harm from other devotees, think that they need to choose between remaining in a specific community and receiving abuse and leaving and losing the Gods. No matter how hard it is, you can always leave and bring the Gods you love with you. Your personal or family shrine is *yours*. Take responsibility for it.

## Practice

In the introduction, I recommended clearing off a shelf or small space to use for a household shrine. It is time to make use of this space.

Again, you need:

* Something for pouring liquid.
* Something to pour liquid into.
* The name of the deity you’re worshipping — either a post-it note or something fancier. (I often use popsicle sticks, and I will use colorful markers to make them look nice.)

Often, especially when we’re looking at ritual space stock photography or the spaces of people who have committed disposable income to pricier items, we see beautiful statuary and intricate spaces. This helps, but it’s not necessary — and, given the climate crisis, it makes sense to be measured about purchases instead of contributing to overconsumption. Once you have a good idea that you want to worship a God and have maintained the habit for long enough, go ahead and think about images.

The bare minimum you need for worshipping a God is their name. In antiquity, when people were pouring libations and making sacrifices on altars, the altar was marked with the name of the God or Gods. It is like having someone’s address in the *to:* field when you send an email.

For a hearth deity, I also recommend a small candle or flame representation. You can use a traditional lighter or a rechargeable electric lighter. Some people even use electric candles! There are phone apps that mimic fires and candles, too.

For a libation, any drink is fine — even water. I sometimes buy loose dried tulsi and make a concentrate that I store in the refrigerator. Whenever I want to pray, I pour some into the libation jar I use and add water. I also offer a flavored water concentrate that I like, especially to my ancestral Gods — it feels very intimate to share beverages I actually drink. Some people offer wine or other alcohols. I find that I don’t go through the bottles quickly enough to use up all of the alcohol before it goes off, and since I rarely drink, it feels odd to give a God something that isn’t part of my diet unless the deity has a symbolic relationship with alcohol.

Other types of offerings include incenses, flowers, and food. If you use incense, be careful of resins — do not burn them indoors on charcoal disks, as there is a carbon monoxide risk. Always be in a well-ventilated area. Burning resins outdoors with a fire-safe setup is fine. Stick and cone incense are great for daily indoor use, and some companies sell low-smoke incense. If you use essential oils in an oil diffuser in your offering space, please check that your oil is pet-safe if you have animals — vets have been more public in recent years about what to choose and avoid. Never use citrus oils around your cat. Be careful about flame-based oil diffusers, as they can be a fire risk.

Disposing of offerings can be done in a clean sink (for libations) or in your household trash. If you offer food or flowers, the most respectful way to put them in your waste receptacle is to wrap them in paper (like a used grocery bag from the time you forgot your reusable bags, padding paper left over from a package, or similar) and add them to the trash just before you put it out curbside. If you can compost, that is preferred, but don’t worry if you can’t — I, too, live in an apartment without that option. If you offer non-fresh goods like dried flowers or wreaths, rotating them out after six months to a year is auspicious — especially if you do it at about the time of the winter or summer solstice.

Sometimes, people eat the food offerings shortly after they are offered — the food is now blessed by the God(s), and eating it is the completion of the reciprocal relationship. Traditionally, some practices (i.e., for Gods worshipped in Egypt) have done this by default. In other areas, it has been common according to custom for the Gods’ portion to be separated from what everyone will eat. Do what seems right to you, except for underworld Gods — see the chapter on Purification for more details.

Specific scents, herbs, plants, foods, and other material objects may be sacred to a God. If you want to be sure that your prayer space has the correct ambiance, lean into those correspondences. It is very easy to Google *[name of deity]* *what to offer* and end up with creative ideas from people of all ages, experience levels, and backgrounds. I have offered Apollon bay leaves, and I usually offer frankincense incense to him when I do something more elaborate. You may also develop intuition over time that tells you a specific offering is a good one. I use an incense blend called River Path for some Gods because the incense’s name evokes the connection I aim to establish.

If you are setting up a permanent space, be respectful. Never use your shrine as a landing space for random objects and clutter. Encourage family members and/or roommates to avoid putting anything there that isn’t an offering.

Now, do you need to worry about getting the “wrong God” or “summoning” something else? People coming from modern occultism may have encountered this idea, and it is not relevant here. We are setting aside a sacred space using the names and symbols of the God, the Gods are wholly good, and daily shrine prayers are a foundational practice that people do around the world. This is normative and safe.

### Household Prayer

Hopefully, you now have a shelf or another location where you can create a pop-up or long-term prayer space. If you have purchased or gathered any items, now is the time to place them there. Clean and arrange them in an ergonomically useful way.

Before praying, I recommend washing your hands. If you are praying after your daily shower, congratulations on habit-stacking.

If you have a candle or other flame representation, light it or turn it on. Keep your elbows at your sides and hold out your forearms with your hands palm-up. Standing up is the common practice, although one can sit if necessary.

Say something like:

> I honor and acknowledge the household Gods, [insert any specific names]. I give you this offering of [whatever you’re offering].

Make the offering. If you are doing a libation, this means pouring whatever you have chosen to offer into the bowl. Sometimes, after offering most of something, a person will take a sip of the remainder. 

Take a pause and a few deep breaths.

If you are honoring specific Gods and divinities and know anything about them, this is the time to call to mind those aspects. For Nantosuelta, for example, one might think of her connection to beehives, fire, fertility, apples, and Earth — far from just being a Goddess of the home, she has many areas of affinity that are not related to the home in the slightest.

Sometimes, people will recite poems they’ve found about the deities and divinities they’re worshipping, play music, or speak from the heart about what they have going on in their lives. You could do that now if you like.

When done, say:

> Thank you, [insert any specific names or just say “household God(s)”]. May you bless me, my family, my friends, and my communities with whatever is most good, fitting, and appropriate.

Dispose of the offering in a few hours. I like to clean out my offering bowls after I’ve done dishes in the evening.


### Meditation

This meditation is based on an exercise from one of Plotinus’ *Enneads* and on something I’ve done since I was a teenager.

The passage from Plotinus’ *Enneads* is at 5.8.9, and here’s how it is translated by Gerson (note that the pronoun “he” is used for the God, but this could be any deity):

> So, let us grasp by discursive thinking this cosmos all together as one, each of its parts remaining what it is and not jumbled together, if possible, so that if any one of these should occur to us – for example, the sphere outside the periphery of the cosmos – an image of the sun follows immediately and together with it all the other stars, and earth and sea and all the living beings are seen, as if all these were in reality to be seen in a transparent sphere. Let there be formed in your soul, then, the image of a luminous sphere having all things in it, whether moving or stable, or some moving and some stable.
>
> Keeping this image, take another for yourself by abstracting the mass from it. Abstract, too, places and the semblance of the matter you have in yourself. Don’t try to take another sphere smaller than it in mass, but call on the god who made that of which you have a semblance, and pray for him to come. And he might come bearing his cosmos with all of the gods in it, being one and all of them, and each is all coming together as one, each with different powers, though all are one by that multiple single power. Rather, it is that one god who is all. For he lacks nothing, if all those gods should become what they are. They are all together and each is separate, again, in indivisible rest, having no sensible shape – for if they had, one would be in one place, and one in another, and each would not have all in himself. Nor do they have different parts in different places, nor all in the identical place, nor is each whole like a power fragmented, being quantifiable, like measured parts. It is rather all power, extending without limit, being unlimited in power. And in this way, the god is great, as the parts of it are all unlimited. For where could one say that he is not already present?

For this prayer, place a chair or cushion near your shrine to use as a meditation seat. Make a short prayer:

> I pray to the Gods and give you this offering before my meditation. May you be well disposed.

or 

> I pray to [deity] and ask for your guidance during this meditation.

If you have an offering, make it now, and then be seated.

For this meditation, start off by doing a body scan, eyes closed or open. Start the scan at the top of your head, working through parts of the body to see what is comfortable or uncomfortable. Notice the pressure of gravity and the places where you are touching the floor or chair.

Once you have finished the body scan, turn your attention to the boundary between your skin and the air. Envision your awareness expanding from your body and into the room around you. Feel the furniture and become aware of the life within your home. From there, expand your awareness steadily to every room in your home or apartment. If you are in an apartment, expand your awareness to the entire building.

From your building, steadily come to encompass the neighborhood, then the city, and finally your region. Allow your awareness to expand until you are holding the world in your mind. Examine the differences in climate and ground cover, sunlight levels and depth of night. Rest here for a moment.

When you are ready, expand it outward from the Earth to the Earth-Moon system. Grow through the void to reach the planets of the inner solar system and the Sun, then the asteroid belt and the outer planets, and finally the mass of smaller bodies that make up the frozen fringes of the solar system. Expand your awareness to the nearest star systems, then to the galaxy. Know that we are in a network of galaxies, and expand into that. Eventually, your awareness will encompass all of the honeycombed web of the universe. It is filled with voids and oases of light.

All of this has evolved in time, and it came from a point of indescribably high density. The visible universe was once about the size of a grapefruit. You are containing at least all of this within your awareness.

Now, think of all that you are holding within your mind, and call to mind what it would be without mass. Call to mind all that is, and then imagine it spaceless. Contract all that you have become aware of without giving it mass, shape, or extent in time. Beyond the spatial extent, beyond time, and beyond bodies, there is an inflection point of divinity. As Plotinus wrote so long ago, ask for the God to come.

Whatever comes to your awareness, rest with it until you judge the meditation to be finished. Thank the Gods and put back your chair or cushion.

This exercise is a bit different from what is happening in Plotinus’ *Ennead* 5.8.9, as it fuses the abstraction of his words and their beauty with an expansion into everything visible around us. However, it can still be a powerful visualization practice. If visualization isn’t right for you, I encourage you to replace this with another meditation technique.

## Time Blocking Exercise

In the above practices, you have done a ritual prayer and embarked on the opening of the way to your soul’s inner statues — a beautiful thing to be celebrated. It may feel new, different, and give you a sense of calm (at least, once the awkward feeling of newness fades) — but chances are, you figured out a time to do these exercises that fits into your daily routine.

I recommend doing prayers right after you do your shower (or whichever freshening up activity you do every day). The chapter on purification will discuss that in more depth and will give you an opportunity to create backup scenarios for when life gets hectic.

Now, though, I want you to think about your morning, afternoon, or evening routine — whichever time you think it is best to pray. And I want you to time block it.

Time blocking could involve post-it notes, notecards, or a piece of paper. You could also use a digital post-it app like Mural, a workflow diagram generator, or anything you are comfortable with.

Think of what your routine is like for the time of day you have chosen. Write down each step, including the amount of time it takes you. This is a private activity, so please do not treat yourself as your aspirational self. If you make your coffee/tea and stand there by your French press entranced by your Twitter feed for twenty minutes, or if you’re on your phone playing Candy Crush on the toilet for ten, note that down. 

Once you have a realistic image of your routine, you can think about what you want to adjust. The rituals we are discussing in *The Soul’s Inner Statues* can be as swift as two to five minutes. Can you wake up five minutes earlier, or is there time you can adjust? Are there other aspects of your routine that you’re unhappy with?

Work through your routine until you find something that is both satisfying and actionable. Transfer the information to a physical sheet of paper (one or two is ideal) and put it where you will see it at that time of day. 

Try not to change too much — for habit-building, the most lasting change is incremental. Once you have made good progress on this for a few weeks, go back to your notes about your routine and pick one other thing to shift. For example, if you want to read more, ensure that there’s a book by your coffee/tea setup instead of your phone.

As someone who prays in the morning, avoiding social media, email, and my to-do list is what works for me so I can have that extra prayer time. Because I pray for longer than five minutes, I also wake up earlier — at 6:15 AM instead of 6:45 AM. I like having time to give prayers to a variety of Gods, including Gods of the sacred day in the calendar system I learned in my early 20s, and to sit in contemplation for at least a few minutes. However, I do have that quick ritual routine in my back pocket if I oversleep. Often, I do prayer beads or a quick prayer and meditation after I brush my teeth and before I go to bed, which lasts only a few minutes unless an idea for a poem comes to me. The timing of your prayer is up to you.

