# Gods

We devoted much of the last chapter to discussing some foundational aspects of a spiritual practice for many Gods, and we ended with practices that anyone can integrate into their life: a few moments of worship at home, both prayer and contemplation. In this chapter, we will build on those practices and pick one or two more Gods to worship — for now, no more than that. Sometimes, a person may decide to pray to a collective of Gods: the Muses, for example, or the Fates, Matronae, Attendants of Frigg, Gods of Civic Discourse, Storm Gods, and so on. In my personal practice, I usually pray to the Muses as a collective. Others may devote prayers to all of the Gods in general — often using names and terminology relevant to a specific cultural grouping of Gods, such as the twelve Olympians in Plato’s *Phaedrus* or a set of major Roman, Nordic, Celtic, Gaulish, Sumerian, or other deities.

It is not necessary to worship every single God every day (that would be impossible), just as one cannot be friends with every human being in the world or every sentient being in the cosmos. Beyond worshipping the household Gods and divinities, and perhaps doing ancestor worship on auspicious days for such activities, most people only have the bandwidth for a handful of Gods and divinities before their attention is too scattered to have a deep and meaningful practice. *The Soul’s Inner Statues* is focused on breaking down the steps to work towards a manageable, meaningful practice, so this chapter approaches embarking on that in chunks through steady, sustained change.

Keeping the number of Gods limited at first helps you settle into a concise prayer routine, and it allows for mindful expansion of your practice if you judge that expanding it is important to you. Billions of people around the world pray for only a few minutes a day. The most important thing, and the hardest, is showing up.

As you read this chapter, take some notes on what comes up for you. The exercise at the end will ask you to look up one or two Gods and to pray to them.

## How Do You Pick a God?

The factors involved in choosing Gods to worship are many. In this section, we will discuss a few major ones.

**Culture and region.** For many people, this is what is done: You worship the God whose temple is down the street (or whose ruins are in your area) or Gods who are widely present in your cultural substrate, whether or not your culture writ large worships them. In the United States, specific regions, cities, and states may use the images of specific Classical Gods or Goddesses, and revering them is possible. Outside of the United States, there may be temples and cultural sites (ruins or still in use) that could inspire you.

**Following what a group does.** People raised in a specific religious group, or who join a group as an adult that honors specific deities, often do what everyone else is doing.

**Heritage.** Maintaining a connection to where we come from is important to many people, especially in the United States or other former colonies. Whether someone’s ancestors arrived in a place voluntarily or via human trafficking and abuse, it could be important for a person to explore their personal ancestry when selecting who to worship. My only word of caution is to ensure that you approach this mindfully. Especially for those of us with various European ancestries and ethnic backgrounds, a “return to the roots” can be co-opted by the far-right. Anyone can worship the Gods. Far-right rhetoric relies on exploiting feelings of disempowerment and rootlessness, and it is important to resist it. You are worshipping the Gods you worship for your reasons, and others have their own reasons — everyone has a perspective to offer, regardless of an individual’s cultural heritage and/or ancestry. Developing a practice for the Gods, being committed to learning, and approaching the practice with reverence are what matters. Let your own thing be about repair without making it creepy, and avoid groups that don’t allow people of all races and ethnic backgrounds in. In groups, what matters is respect for the Gods and coming together in service for them and one another.

**Activity.** This is exactly what it sounds like. You know what you like, what you do for work and hobbies, and who you want to be. You find Gods who have well-documented aspects in one or more of those areas and decide to worship them. Most people who worship Gods use this as a criterion for selecting someone to worship, at least in the beginning.

**Astrology.** In astrological systems, specific Gods are associated with specific signs of the Zodiac. These deities may shift slightly based on the system a writer is using. Sometimes, the position of the rising sign or which sign the moon is in matter just as much as one’s sun sign. You can explore this with some Google searches on Gods for specific signs. Keep in mind that “astrology” is a very general term, so you will see results for Western, Vedic, East Asian, and other forms of astrology. Speaking Platonically, the soul accumulates various traits (or garments) as it descends into the world of becoming, and the positions of the stars at birth have sometimes been used as signals of which Gods will be particularly prominent for a person that lifetime, although that is not the only thing that matters. Some astrologers believe that the planets *are* the Gods. While the planets are sacred to the Gods, even if a planet is associated with a God, the God transcends that planetary association.

**Divination-based.** Sometimes, especially in African Diaspora religions, the God(s) someone should worship closely are determined in divination. Divination protocols for such rituals are usually very intricate, and they require study and care for the practitioner to do them well. This book is not about those traditions, and if you are curious about them, I encourage you to do research on the ones that interest you, ideally learning from actual practitioners and leaders in those traditions. Outside of those specific religious contexts, someone could consult with divination specialists about deities. “Divination” is a broad category that encompasses far more than tarot and oracle cards, and it’s not just about predicting the future! Often, people use divination to seek advice on something that has been bothering them or gain insights into circumstances they are facing so they can make informed choices. Divination of any kind is ideally conducted in a manner that connects with the Gods via prayers, offerings, and so on.

**Experience.** In Proclus’ surviving hymns to the Gods, he makes frequent references to holy words of the wise that excite the soul towards the Gods. This divine bliss state sometimes literally happens to people. Very rarely, you’re reading something, you have a dream, or a freaky chance occurrence hits, and it sends chills down your spine. It could even send the world topsy-turvy for a few hours or days. Something feels *right* about it. You may know the name of the God, or you may just know vague things about your experience and put the pieces together later on. It’s a gift when this happens. As a word of caution, keep an eye on your mental health — brain conditions can mimic spiritual experiences, so practice self-awareness and be sure to follow up with a doctor if you suspect that something is wrong. (Generally speaking, “you are the chosen one” is something that only happens in Hollywood movies and messianic fringe groups.) Intense bliss-state experiences will dissipate after a few hours or days, perhaps with some short-term aftereffects like an increased ability to enter a meditative state or a re-evaluation of your life goals. And they don’t happen every day! “Smaller” experiences are more common — praying for a dream or an unambiguous sign is something people have done for millennia in pursuit of some milder spiritual insights.

### An Example of Choice

When I was a teenager, I decided on Apollon and the Muses because I felt that poetry was the only thing I was good at. In the American cultural reception of Apollon, he is often taken to be synonymous with music and poetry. Little did I know that, when I made that choice, things would change and expand out from there — Apollon is a harmonizing God, first revealed in the truth-bearing triad in Platonism before weaving his way through various levels of emanation from the One. I was worried when I started studying library science that I still thought of him as my God when my work had nothing to do with him, and I struggled to find ways to relate my life to what I knew about him from his epithets, what scholars had written, and the things I saw people post online about worshipping him.

For several years, I strayed away and primarily worshipped Hermes, with Athene secondary, because they are very professionally relevant to my daily work. This was naïve of me given what I know now, and as soon as I was ready to know more about Apollon, specific things in my life fell into place that landed me back worshipping him daily — everything I needed to know was rooted in the Platonists. I worship Hermes much less now, but still in a professional capacity. We’re human. How we pray, and who we pray to, evolves over time.

### What About Specific Traditions?

*The Soul’s Inner Statues* is a book about worshipping Gods at home, not about any specific religious tradition. Many of my examples draw on the Hellenic Gods because I have worshipped them for so long. (In my own non-Greek context; if you’re interested in something connected to Greek methods of worship, I encourage you to connect with Greeks.) As a follower of Plato, I also firmly believe that it is important for avoiding cultural appropriation that Platonists engage with the Gods of the tradition. (Even for Platonists who worship other Gods, a moderate engagement with Hellenic myth and context is important for doing Platonic contemplation related to the primary Gods one *does* worship, regardless of where those Gods are from.) Specific religious traditions often have guidelines that are used to help devotees select a deity … if the tradition doesn’t just choose the God for them. What happens in those traditions usually falls into one of the categories that I have named above.

Some marginalized groups are very protective of their ancestral practices, usually due to outsiders exploiting and selling their practices for the outsiders’ own financial and social gain and due to centuries of oppression and persecution from missionaries and state-sanctioned religious violence. Be mindful of this and seek to understand where others are coming from. Worshipping a God privately at home does not grant you automatic acceptance by the survivors of cultural genocide or conquest. Showing respect for their communities, being willing to learn, and committing to treating their traditions as sacred and not as commodities may go a long way, but then again, it may not. The decision is theirs.

### What About Being Chosen?

While I do believe in spiritual experiences, I *don’t* believe that being “chosen” by a God is possible. What I *do* believe is that many (or is it just us Americans?) use vocabulary from pop culture fantasy novels and Christianity because we don’t quite know how to put what we have experienced into words.

When people are saying this genuinely and not deceptively, I believe this means that they experienced the spiritual version of “friendship at first sight.” (This is a real concept in friendship research.) They saw a depiction of a God or started to learn about them and just *knew* they needed to worship that God. It can be a very magnetic pull and generate intense, difficult-to-describe emotions. The person making this claim is still the agent. They are the one who decides to offer the libation or light the incense. There can be spookier versions of this, such as jarring coincidences or dreams that always seem to point to the God; in those cases, our guardian spirit is likely trying to get our attention and let us know that worshipping this God may be fulfilling for us. It’s still not chosenness.

Sometimes, people will describe their spiritual life as a *calling*, a term that is highly associated with Great Awakenings and evangelical Christianity in America, but which has since been secularized. It’s now frequently used in America to describe people who give everything they have to their jobs because the job gives them meaning. *Calling* or *called* are simply culturally-specific words to describe that feeling of being excited about something, empowered to grow, and connected to something greater than oneself. I do not use this language. In our multicultural society, it can lead to misunderstandings when someone doesn’t have tacit cultural knowledge of the term’s origins and context.

Related to this, one will sometimes hear the term *working with [deity]* instead of *worshipping [deity]*. Some of this usage comes from magical practices, and the modern occult movement’s history is too out-of-scope to briefly trace why that usage is present. Beyond that, one will occasionally hear someone express that their upbringing in a conservative (usually Christian) sect has made them anxious about the term *worship* due to the traumatic experience. *Working with* can make the Gods seem more approachable. However, *worship* is the preferred term, even in cases when someone is doing a specific type of work, volunteer effort, or hobby to fulfill a vow made to a God. Our nature is not the same as the Gods — our role in the world is to be present to what is happening around us in the material world and to grow and change under their watchful guidance. We have agency and dignity, yes. The rites we perform, the meditations we do, and the other spiritual acts we train ourselves to do are all done to increase our harmoniousness with their providential power. They are the conductors; we are members of the orchestra. 

#### What About Transformative Experiences?

Transformative experiences of the Gods are beautiful things. These can come in the form of dreams, experiences in journey meditations, sudden illumination from wisdom tradition texts, or even an awakening to divine beauty when we see the way the sun strikes newly-opened spring flowers. In ritual, it is not unheard of for someone to be overcome with strong feelings of connection and love when praying to a God for the first time, as if a floodgate has opened. Prayers can lead to steady streams of coincidences. Divination outcomes can teach us about the parts of ourselves we need to grow or let go of, and the techniques themselves put us in contact with the God(s) to whom we have consecrated our tools.

While it is not chosenness, a deep experience might indicate your *closeness* to a God, especially if you have been praying for guidance about the best God to devote yourself to or something similar. In Platonism, the Gods have something called *providential love* (eros pronoetikos) for us — a type of care flowing without cease and without boundaries to all who are open to receiving it. Experiencing bliss or a sense of deep connection in prayer can sometimes be mistaken for chosenness or some kind of special status. Having a religious experience, cleaning oneself up, and committing to excellence can also sometimes lean on the idea of being chosen as a self-soothing mechanism — we like to believe that someone else is rooting for us *specifically*, and it’s useful to unpack why we may believe that is the case. Maybe we actually just chose a life (go us!) where we will do a specific set of activities, and a spiritual experience was the jolt that motivated us to finally get done what we had already committed to doing. The Gods are like the sun: our experiences of their rays depend on everything from weather to time of day to whether we have positioned ourselves somewhere we can be appropriately warmed.

The reason for emphasizing dangers is that we are all capable of self-deception, especially those of us who grew up in difficult environments. *After the Ecstasy, the Laundry* by Jack Kornfield describes the opportunities and pitfalls for people from a variety of religious and spiritual traditions who have experienced a sudden awakening. The biggest pitfall, according to him and others, is thinking that it’s one-and-done and that we don’t need to do work afterward. In the United States, many people have used visions of deities to prop themselves up as New Age cult leaders. Others have founded well-intentioned spiritual communities without any training — and it goes badly. Some have used a spiritual experience to quit working on themselves when they still have years of their life to live. Some engage in appropriation, spiritual materialism, and spiritual bypassing and transform the wonderful gift that was given to them by the Gods into something that causes pain and harm to others.

If a deep spiritual experience happens, approach it with humility. Take notes, do what you need to do, and follow up on your commitments. Decompress however you need. Continue to pray and explore your spiritual practice. Again, the practice evolves over time, as we are embodied souls moving through time. Learn from it.

### An Important Caveat About Gods’ Functional Roles

Many of us are initially drawn to a deity because they have a specific functional role. It establishes rapport between you and the God before you have first prayed to them, much like how reading a social media profile and learning that you have something in common with someone will prime you to treat them charitably, at least at first.

Often, someone may ask, “So, if I have *x* issue, which deity should I go to?” after they already have a foundational Gods-oriented outlook and household shrine. We are conditioned by the media to oversimplify what *divine epithets* and *spheres of influence* of a deity mean. (Again, an epithet is like “Apollon the Far-Shooter” or “Apollon the Harmonizer of All” or “Apollon of Delphi” — it marks some specific aspect of a God, and people will often use epithets to praise a deity when starting out a prayer.) Aphrodite is *only* a Goddess of Love, for example, or Eir is *only* a Goddess of Healing, according to that mindset. We are now living in an era when much of the world is alienated from Gods, and yet this is also a time with tremendous cultural transmission, diffusion, and power for change. We must learn how to see Gods in a more holistic and less utilitarian/functional way.

Starting out with the traditional symbols, images, and epithets can assist you with creating a vibe in your space that will resonate with the God and deepen the link between you and them. Once we get to know a deity, however, these functional areas start to break down, and the God expands to encompass more and more of one’s life. Apollon is most associated with poetry, music, light, and harmony, and yet I might pray to him for assistance with a family issue. I have worshipped Apollon for decades and can easily access that “I am praying to Apollon now” headspace. This deep familiarity facilitates connection even when moving into uncharted zones. When I started worshipping the Norse Goddess Eir, I understood her as a healing Goddess similar to Hygieia and Asklepios, but I now understand her as a Goddess related to healing, purification, and the actions we do here in the material world due to her activity on the battlefield as a medic and the symbolism of her coming down from the mountain where the healing Goddesses do their craft — a battlefield is a symbol of embodiment in Platonism, and generation is seen as a type of warfare. I now include her in my purification prayers. This fusion is far less traditional, but it is personally meaningful, and it is the sort of thing that happens naturally as we unfold our relationship with a God through devotional acts. More traditionally, every place where a God has historically been worshipped will have its own unique take on what that God means (or meant) to the inhabitants, with specialized rituals, iconography, and other elements. The different ways in which we worship the same God are similar to dialects of a language. In cultures that have had more myths recorded, many of the mythic cycles have multiple variants, too.

In the Platonic tradition, every God is the totality of everything (“all in all”) while preserving their own unique individuality and oneness. Gods “flow” into conversation with cultures or groups to produce unique fingerprints of how Gods operate in specific places. These “flows” impact their iconography, the items offered, the myths a people creates, how we see the God’s sex and gender role, and so on. As a side note, we project stereotypes onto the Gods based on how humans have given social meaning to human reproductive roles and functions — historically an important part of our societies, but less so in many American cultures nowadays. Gods who seem more active in generation and growth and care are often feminized, and Gods who seem authoritative or causal are often masculinized. Thus, Frigg, Hathor, Sunna, and Nantosuelta are Goddessess; Vulcan, Helios, Zao Shen, and Mani are Gods. The “fit” is never perfect — just as with humans — because nobody reflects all of the stereotypes. We can see this acutely with Goddesses like Athene and Artemis who are masculinized, even though Athene presides over women's labor production and Artemis was once involved in maturation rites for girls and brides — or Gods like Dionysos and Apollon who are feminized while simultaneously having their masculinity stressed through (for Dionysos) connections to phallic worship and (for Apollon) connections in the ancient world to older boys' adulthood rites. In many cultures, there are also Gods who symbolically hold the potential of all reproduction, like Phanes, who is depicted as gynandrous. Some types of symbolism remain important due to their theurgic function and relationship to birth-death-rebirth cycles in nature and mystery traditions, whereas others are less translatable across time, place, and culture. (For any Platonists reading this, the landmine of misconceptions about how these topics intersect with the simplicty of the Henads and their “unfolding” through the levels of the hypostases is similar to how the One, the Two, and the Three mean something different at levels of emanation from the first principle that are less proximate to matter; many people make an error here similar to the one that Aristotle makes while critiquing the Forms in his *Metaphysics*, and Syrianus’ refutation is very relevant here.)

A group may even be united by a similar view of a God when they live very far apart as long as they share a common outlook on life. These relationships between groups and the Gods evolve, progressing forward in time.

Syrianus, in critiquing Aristotle’s *Metaphysics*, Books 13-14, wrote:

> [T]he whole placing of the stars involves much supposition on our part. Thus it is that the fixed stars are arranged in one way according to the Egyptians, but according to the Chaldaeans or the Greeks in another way. (191,23-25)

Gods do not have positions in the sky, but a similar idea applies here. When we create practices surrounding the Gods, and especially when those practices become traditions and influential cultural movements, we are arranging the Gods into structures based on what we come to know about them. Each of our practices may divide up the sky differently and omit some types of stories and deities in favor of others, but the same *potentiality* of divine multitude underlies all of this.

Sometimes, the functional role a deity has traditionally occupied is very important to us long after we’ve solidified who we worship the most. I have a soft spot for solar and light-related deities, and that comes out in my practice even though I know that these Gods cannot be reduced to the material sun.

## A Chain, Unbroken

In Platonism, there is one other type of divine relationship — something that is not a choice and could never be a choice. In the Platonic tradition, every soul is in the *series* of a specific God. A *series* is a chain that begins with the God. It progresses through several levels of intermediary spirits, and the chain ultimately ends with us.

As incarnating souls, we “dip down” into various types of lives, from rational lives (think humans, orcas, or elephants) to nonrational lives (think incarnating as a cat). Above us are heroes, who have a dipping point of rational lives (so, they can’t become cats), above them daimones and angels (who do not have dipping points into material bodies, unless one posits that some daimones dip into planets and stars), and finally, the Gods themselves. Every God has a chain of these intermediaries. At the risk of sounding too spatial for something that is not demarcated by space, the God is the “trunk,” the angels are the “boughs,” and the various levels of daimones are the branches that we (nodes that produce fleeting leaves) are suspended from. Each daimon has a cluster of souls it supervises. In addition, specific lives we choose have presiding daimones.

Because being in some God’s series is an innate property of every soul, it is not special; because we are each individuals who express that individuality differently, every soul has its unique, particular way in which it is linked to the God that seeds it. This doctrine calls those of us who hold it to probe the paradox of something as ordinary as grass being so individually important.

Each soul only has *one* leader-God because its anchor point must be a unity; if the soul had many, it would not be a one. Platonism has its roots in the Ancient Mediterranean (and Greece specifically), but the leader-God does not need to be Greek — even in Late Antiquity, there were Platonic philosophers and Platonizing individuals from other polytheistic religious traditions. It is also a misconception that these Gods are limited to the twelve (or eleven, rather, because Hestia abides) discussed in Plato’s *Phaedrus*. Both Proclus 

> [Plato] defines according to the measure of the dodecad all the liberated Gods, though the multitude of them is incomprehensible, and not to be num- bered by human conceptions; and though none of those theologists that have written any thing concerning them, have been able to define their whole number, in the same manner as they have the ruling multitude or the multitude of the intellectual or intelligible Gods. Plato however, apprehended that the number of the dodecad is adapted to the liberated Gods, as being all-perfect, composed from the first numbers, and completed from things perfect; and he compre- hends in this measure all the progressions of these Gods.
>
>Proclus, *Platonic Theology,*:Book 6, Ch. 18, 85.7-16

and Hermias 

> [Plato] said in the Timaeus that the Demiurge assigned the souls to gods on the basis of kinship (*okeiotês*), saying that ‘he sowed some in the earth, some in the sun’. Here he has also talked about the nine types of life (*bios*) and also talked about the twelve gods, symbolically including the whole multitude [of them]”
>
> Hermias, *On Plato Phaedrus* v. 2, trans. Baltzly and Share, 197,7-11, brackets from the translators

push back against this idea, and Damascius mentions individual souls who are in the series of the Gods of Tartarus in his *Phaedo* commentary at §540. The core thing to pull away from the concept of leader-Gods is something from Hermias:

> For this is the soul’s happiness: to be able to imitate its own god, to the extent of each person’s power, so long as [that person] lives life here [on earth] in an uncorrupted manner.
>
> Hermias, *On Plato Phaedrus* v. 2, trans. Baltzly and Share, 198,30.

Here, “uncorrupted” is hinting at what we will be discussing in the chapter on virtue about applying measure and mindfulness to our lives so we are not completely caught up in appetites and emotions. Imitation of our leader-God does not mean imitating myths; it means contemplating who the God is and how their blessings are distributed among all of us. For Apollon, it may mean focusing on goals related to harmonization and bringing multitudes back to unity in a variety of contexts; for Brigid, it may be embracing a lifestyle where making/creating and giving back to the community are core emphases.

Proclus, who is very verbose about the topic of leader-Gods, discusses what it is like when someone has that inner knowing and can align their goals with this sense of sameness and identification with one’s leader-God.

> Even amid matters that seem difficult to understand or puzzling, the person who simply *knows* takes the easy path to divine understanding (*gnôsis*) — retracing [a path that runs via] the divinely inspired cognition (*entheos noêsis*) through which things become clear and familiar (*gnôrimos*), for all things are in the gods. The one who has antecedently comprehended all things is able to fill others with his own understanding. This is precisely what Timaeus has done here when he refers us to the authority of the Theologians and the generation of the gods celebrated by them.  
>
> Who, then, are these people and what is the understanding (*gnôsis*) that belongs to them? Well, in the first place, they are ’offspring of the gods’ and ’clearly know their own parents.’ They are offspring and children of the gods in as much as they conserve the form of the god who presides over them through their current way of life, for Apollonian souls are called ’offspring and children of Apollo’ when they choose a life that is prophetic or dedicated to mystic rites (*telestikos bios*). These souls are called ’children’ of Apollo to the extent that they belong to this god in particular and are adapted to that series down here. By contrast, they are called offspring of Apollo because their present lifestyle displays them as such. All souls are therefore children of god, but not all of them have *recognised* the gods whose children they are. Those who recognise [their leading gods] and choose a similar life are called ’children of gods.’ This is why Plato added the words ’as they say,’ for these souls [sc. those of the people to whose authority Timaeus proposes to defer] reveal the order from which they come — as in the case of the Sibyl who delivered oracles from the moment of her birth or Heracles who appeared at his birth together with Demiurgic symbols. When souls of this sort revert upon their parents, they are filled by them with divinely inspired cognition *(entheos noêsis*). Their understanding (*gnôsis*) is a matter of divine possession since they are connected to the god through the divine light and [this sort of understanding] transcends all other [kinds of] understanding — both that achieved through [reasoning through] what is likely (*di’ eikotôn*), as well as that which is demonstrative (*apodeiktikos*). The former deals with nature and the universals that are in the particulars, while the latter deals with incorporeal essence (*ousia*) and things that are objects of knowledge. But divinely inspired understanding alone is connected to the gods themselves.  
>
> Proclus, *Commentary on Plato’s Timaeus*, Book 4 (confusingly, Volume 5), trans. Baltzly et al., 159.14-160.12 — all of the things in parentheses and brackets are from Baltzly et al.

The description may sound utopian, as if no strife or suffering happens when someone knows their presiding God. Importantly, we are still living in the material world, where everything is separated out in space and time and things occasionally come into conflict with one another. Knowing one’s presiding God is more about having an inner sense of connection, agency, and empowerment in the face of these external challenges than it is about having no conflict. An inner sense of groundedness and belonging makes people more effective at handling their external situation, though.

Most of us have a lot of noise inside, and it takes a journey to figure out who that presiding God is. When it comes to embodiment, we have a big challenge: our forgetfulness and our ability to get hyper-preoccupied with what happens in specific incarnations or a series of incarnations. We sometimes pick life-patterns that align with our leader-God, and sometimes we don’t. This is one of the reasons I called each of us unique — we make traces in the realm of coming-to-be like fingerprints. Some of our journeys express the tragic beauty of our leader-Gods, or the violent and horrific ones, or the depths of disappointment; others skim the surface of generation, like a bird of prey diving into the sea to come back with sustaining nourishment. The story of Cassandra, for instance, is metaphorically about having that deep insight, wanting something else, and then turning away from a God who cannot be run from because he is already the core of her; there are just as many people given the same prophetic gifts and who are not believed, yet never turn from the source of their good.

In this context, part of the maxim γνῶθι σεαυτόν (know thyself) is that we must strive to uncover this knowledge of who we truly are when we cast away all of those garments, and we must learn how to perform our current role in the most just way possible. This will not be easy regardless of how we make that approach.

*Series* has both the technical meaning just described and a secondary, slippery one, and in its slippery sense, it refers to the God or Gods who preside over our current lifetimes, who may or may not be the same as the God we are suspended from, and Gods who are highly related to specific talents and skills that we have in this lifetime. In other words, it can be tough to figure out who our leader-God is if we approach the problem solely based on what we’re good at or the specific aspects of our daily grind.

> But we should ask which of the aforementioned six types of essential daimons they say is allotted to each person. Well then, they say that those who live according to their own essence (*kat’ousian*) – that is, as they were born to live (*pephukasi*) – have the divine daimon allotted to them, and for this reason we can see that these people are held in high esteem in whatever walk of life they pursue (*epitêdeuein*). Now [to live] ‘according to essence’ is to choose the life that befits the chain from which one is suspended: for example, [to live] the military life, if [one is suspended] from the [chain] of Ares; or the life of words and ideas (*logikos*), if from that of Hermes; or the healing or prophetic life, if from that of Apollo; or quite simply, as was said earlier, to live just as one was born to live.  
>
> But if someone sets before himself a life that is not according to his essence, but some other life that differs from this, and focuses in his undertakings on someone else’s work – they say that the intellective (*noêros*) [daimon] is allotted to this person, and for this reason, because he is doing someone else’s work, he fails to hit the mark in some [instances]. 
>
> Olympiodorus, writing on our allotted daimon, at (20.4-15) of the *Alcibiades I* commentary, all brackets from the translators

This confusion is not even a bad thing. In Ancient Greek art, there are beautiful scenes of Gods pouring libations to other Gods (Gaifman, 2018). Water is, among other things, a symbol of generation. We could view our incarnations that are lived away from our leader-Gods as libations, or gifts, for the other Gods — it is a system of mutual honor. A God pouring a libation for another God, or doing sacrifice in general for another God, is a gift of participation in a portion of their divinity to another, mediated by this weird realm of generation where so many things are possible. We are each, at our core, a one, and the flower at the core of us is always connected to the God we are suspended from; we are, at our periphery, dazzled by and participating in the amalgam of divine delights, a reflection in water of the feast that the Gods share in the *Phaedrus*. The Gods have no jealousy among them.

In generation, the beautiful divine patterns — each driven by a specific God — “freeze” out. Like a frustrated spin glass, there is no configuration of the whole system that can be utterly stable. (Spin glass is made of charged particles, with north and south poles. As with other magnets, they want to align north with south poles, but the configuration of the system prevents them from attaining that — shifting positions keeps putting them in conflict with yet another neighbor. Proclus describes this frustration in a different way in an essay on evils.) These conditions, and these phases of imperfect stability, evolve with time. We are locked in one position only to shift to another. We have that stability of who we are, but also the instability inherent to this environment. Some types of closeness with a God or Gods are driven by where we are in our life or lives; others are metastable over long periods; and only one relationship is absolutely intrinsic.

For those of us who hold that we belong to a God, we can add so much insecurity to this innate wonder of existence. Always focus on the God and be willing to evolve in how you relate to them. When we focus on the basics of prayer, ritual, and piety, we embrace the changing rhythms of our lives, which is in our nature as souls who are living a life in the material world. We allow ourselves to explore what our relationships to specific Gods mean without grasping tightly at something that will eventually fall away like sand through our fingertips.

In the last chapter, when I quoted from Plotinus before presenting the meditation exercise to you, there is a moment when Plotinus instructs us to ask for the God to come. This is the kind of contemplative practice that can guide you to who that leader-God is, if this practical Platonic section piques your interest. Repeat the meditation, or something similar to it, regularly over time, in conjunction with prayer. If you come into a state of frustration, wanting and desiring a definitive outcome or sign, sit with that feeling. Frustration often makes what we are frustrated about harder to accomplish. Check back in with the questions at the end of the Today Is Not Yesterday section of Foundations and the How Do You Pick A God methods and think about how to apply those.

If this does interest you, I end this section with these words: Close your eyes, find that stillness, and the God who is intrinsic to you is there. This is not something available to the privileged few, but directly accessible to all. Every human soul, and I do mean each and every one of us, is a prayer *continuously* without even realizing it, just as a heliotrope follows the sun.

## Appropriation, Appreciation, and Cultural Reception

The term “cultural appropriation” may already have your stomach tightening, but don’t worry: I am not going to tell you that you cannot worship a deity or set of deities. What I *am* going to say is that we all need to be aware of what, for lack of a better way of putting it, has been an extremely f—ed up past several hundred years. Appropriation is a way of discussing that power differential and the ways in which dehumanization and prejudice impact relations among people to this very day, especially where these relationships intersect with cultural “objects” and practices. (I am using quotation marks around “objects” because these items, and the Gods they honor, are seen as commodities that can be bought and sold in the spirituality industry.) The sacred is not given the respect due to what is sacred.

Talking about appropriation doesn’t always mean that you have to give something up — sometimes, it means adding to what you do so you can ensure it is more sensitive and that it respects others. When we worship a God, we want to know that we’re doing it in a way that is ethical and grounded in a sensible response to our desire to worship them. We do not want to worship with a spirit of cultural voyeurism or contribute to contemporary problems of de-sacralization and commodification of the sacred. This section uses the positive frame that *we all want to be respectful devotees*.

I have done cultural appropriation in the past. In my 20s, when worshipping Hellenic Gods, I participated in non-Greek communities that saw themselves as cultural continuations of Ancient Greek religious practices. It’s embarrassing to admit in writing, especially now that I realize how antagonistic many of those groups were to modern Greek/Hellenic organizations (based in Greece and the Greek diaspora) doing the same revivalist practices for Hellenic Gods. The truth is that I am an American without Greek ancestry, and while the Greek Gods and thematic motifs inspired by them have been part of American literature, art, and other cultural objects for centuries, our connection to these Gods is its own thing driven by *our* culture, not *theirs*. That is not bad or something worthless to be swept aside! We can look to what inspired creatives in the English-speaking world about specific Gods, myths, and stories, and we can do that without fetishizing a past that isn’t ours to take and without a toxic pursuit of the “authentic.” (The same goes for Americans interested in Vikings or ancient Germanic tribes or Egypt. Know where you’re coming from!) Some aspects of a transmission can be awful. To continue with this personal example, bad aspects of the cultural transmission from Greece include the pilfering of Greek cultural artifacts after the Greek liberation from the Ottoman Empire, the way in which Greek heritage was taken to prop up white supremacy while denigrating modern Greeks as too “ethnic” because they failed to fit that narrative, and the callous humanitarian tragedy that happened when Western European powers failed to intervene in the Greek Genocide because we were hungry for trade with the Ottoman Empire’s successor state. I can worship these Gods, but I need to ensure that I am speaking from my own context and that I am doing what I can about the bad things — activities like supporting repatriation efforts and ensuring that I am mindful of modern Hellenes’ continuity with their past. For a fair treatment of this issue from a Greek person, I recommend [an essay by Katerina Apokatanidis about her experiences of othering in professional Classics](https://everydayorientalism.wordpress.com/2021/04/27/when-greece-is-not-ancient-colonialism-eurocentrism-and-classics/).

This is where we move into “appreciation”: Behaving respectfully and aligning as much as possible with what must be done in it. To use another example, for decades, yoga has been sanitized to make it more palatable for a white, culturally Christian audience. South Asian Americans in yoga like Anusha Wijeyakumar are advocating for more cultural sensitivity and awareness. One element of that is actually diving *deeper* into yoga philosophy and adopting the actual *lifestyle* of yoga. Another element is learning about its Gods, like Shiva, and their importance to the practice. If you do yoga, investigating Gods associated with it (and ways to honor them) and engaging with South Asian teachers is a great way to move from appropriation to appreciation. You can even start learning about the philosophy! I promise, as a follower of Plato, I won’t judge you for being in a rival school! Stoicism, which is appropriated by modern society as a self-help tool, also has Gods at its core (okay, a lot of Zeus), and it should be approached in a holistic and respectful way, too. And Platonism has many Gods! The Muses, Athene, Apollon, Hermes, Zeus, Rhea, Hekate, and a few others are very important to the tradition. Only recently did scholars start to take that seriously as an intrinsic aspect of the system.

At its most basic, be respectful of Gods and spiritual practices. Those of us who are learning about something as outsiders need to understand and embrace our outsider status for what it is. Two things I’ve found helpful to read are [an article from *the Atlantic*](https://www.theatlantic.com/entertainment/archive/2015/10/the-dos-and-donts-of-cultural-appropriation/411292/) about how to mindfully and respectfully approach other cultures and [a piece on cultural appropriation from *A Beautiful Resistance*](https://abeautifulresistance.org/site/2021/6/03/plague-of-gods) that discusses how appropriation is related to the treatment of everything as if it is a commodity item.

Those of us who worship Gods of a culture we’re not from likely came across those deities through cultural reception. Cultural reception, the way I am defining it, refers to how something that originated from elsewhere is received and interpreted by a culture, and especially to how the receiving culture processes its relationship to that thing. For example, the cultural reception of ancient Mediterranean literature and philosophy in the English-speaking world has historically been tied to elite education, especially to white landholders and old money families. There is a further cultural reception at play nowadays in America where people who have historically had *less* access to the Classics are working with the material (as it was a privileged cultural corpus) and putting it in dialogue with other aspects of American culture. All of us in America, colonizers and colonized, are swimming in that unique amalgam. Something similar is happening with Latin American countries’ interest in their own histories of Classical reception, although I don’t know the details beyond a press release for an initiative that came across my social media feed in 2020 or so.

People living in the daughter cultures of the ones that produced the ancient myths we’re reading and reacting to in modern American culture may have very little knowledge about the role their ancient literature plays here, depending on how frequently (and deeply) they interact with us. Due to globalization and the Internet, there are many opportunities for this to create clashes — it’s one thing to see a news story from halfway around the world about a new art installation of Medusa and quite another thing for someone to suddenly have a crash course in American politics in the Reddit comments about said installation. In a spiritual context, the way Wiccans relate to the Goddess Hekate is very different from how a Greek American community may worship her in Astoria, New York. They are two different traditions.

### Syncretism and Eclecticism

Syncretism is what happens when you combine belief systems — and sometimes Gods — in a systematic way. To use a linguistic analogy, syncretism is a lot like what happens when speakers of multiple languages convene in a single location — at first, there are communication issues, but a way to communicate quickly starts. Eventually, a creole language is produced, with its own vocabulary, grammar, and syntax drawn from all of the components that fed into it. It’s very different from speaking multiple languages (the analogy for practicing multiple ways of worship at the same time, but keeping them separate). At some point, the new language is formalized and becomes an institution of its own.

Syncretism is often contrasted with eclecticism. Many eclectics value the relationships with each specific God and are not worried about connecting the dots in a completely fused way like syncretics are. Eclectics may be characterized as people who don’t care about systems at all, but this is rarely the case — people who respect Gods put care into how they are worshipped, but that care may take different forms depending on what someone prioritizes. It is all systematic! Eclectics are willing to tolerate ambiguity and juggle different systems; syncretics want to unite it into a whole. Most people are honestly somewhere in the middle, and others (like me) do not find this framing to be that helpful outside of theological writings. I tend to focus on whether or not a ritual framework is “all over the place” or coherent and how much respect is actually given to the Gods and the liturgical protocols. If something is not coherent or if it is disrespectful, it’s not good. I once attended a small Unitarian Universalist Church on the Sunday they were doing a Wiccan-style ritual. They did not observe the circle boundaries and chaotically combined the Chinese five elements with Celtic symbolism and deities and Tibetan singing bowls. The result was a chaotic mess. It would have needed appropriate observance of “cutting the circle” protocols (so many people had come in late and had just walked in and out during the observance!), purification protocols, and an audit of how the ritual elements were combined and whether it was too much to be respectful or appropriate — at minimum — in order to work.

Syncretic and eclectic practices are what most of us in America will end up doing — and, if not us, our children. We come from many places, with a vast array of cultural inputs, and America is a melting pot. In addition, almost everything is Americanized (to some extent) eventually. What matters most is that we stay curious about the Gods and our practice. The world is full of Gods, as Thales said. Our relationship with the Gods changes over time, as the Platonists say, because we are alive in time.

An example of a syncretic (and slightly eclectic) practice would be if someone were to map hearth Goddesses from their heritage onto physical directions and pray to them according to direction at the beginning of each major ritual. Returning to what I said about worshipping many hearth Goddesses, I could hypothetically set Frigg as East/Air, Hestia as South/Fire, Brigando as West/Water, and Nantosuelta as North/Earth. This would be a nesting doll of syncretism. First, I am looking at Goddesses from four different contexts; second, I am combining them with directional quarters that are used in modern popular Wicca; and third, I am praying to all of the Goddesses at the same time using that directional context. The unifying elements here would be that these Goddesses represent both hearth Goddesses of my maternal and paternal families, plus the Hellenic Gods that I pray to out of fondness. It would efficiently get around questions of who to pray to (and when) by praying to them all at once. This is not something that I actually do, but it is a thoughtful treatment that someone, somewhere, could respectfully do. The directions for the Goddesses are not set arbitrarily. Anyone visiting a ritual would need to be briefed on the context.

Another example of a syncretic practice would be the fusion of Belesama with Minerva in Roman Gaul. Belesama is a solar Goddess, with strong water associations; she is truth-bearing, good with words, and radiant. During that historical period, she was seen as the local version of Minerva by Roman authorities, and the worship of the two Goddesses fused together. Belesama and Minerva are distinct Goddesses. I would, based on personal contemplative experience, place Belesama in a similar conceptual space to Apollon, Aletheia, and Helios. Sulis, another Goddess who was syncretized by Romans to Minerva, was also worshipped as Minerva during the Roman occupation. She has more in common with Hygieia and Salus.

The understanding of deities as being similar is called *interpretatio*, a Roman word. It was used by the Romans to identify which local Gods of conquered peoples (or which Gods of a neighboring people) corresponded to specific Roman Gods,  often for the purpose of integration into the Empire and cohesion. Importantly, even when names are equated, people would still swear oaths by their own Gods, and many people active in theology — like Iamblichus — were against the equation of names (Parker, 2017). In many cases, even when etymologies are clear, a deity may not actually be the same. Mars and Ares, based on their iconography and how people worshipped them in antiquity, are definitely not the same! Nor are Eshu and Hermes despite the many commonalities they have as Gods who are associated with boundaries, playful trickery, and liminal spaces. We do not know the upper limit of the number of Gods. For this reason, even when it’s easy to *conceptualize* a God by relating them to a God you already know a bit about, it’s best to approach them as a distinct person unless something happens in ritual that makes it clear that they are the same. This is a very different approach from what happens in modern secular media when it *uses* mythology and deities. It is typically not being created by people with deep theological understanding of many Gods, but to sell stories based on myths that we have imported via cultural reception, and it is rarely coming from a place of respect.

The more you read about syncretism, eclecticism, and interpretatio, the more questions might arise. I advise you to worry less about this and more about cultivating your personal spiritual practice. To whom do you pray at home? Specific Gods \... and perhaps the household spirits and ancestors. However, as you learn about the Gods you have chosen to worship, you may encounter writings, videos, and podcasts that conflate deities from neighboring cultures or sources that claim that all lunar Gods are the same. The information in this section will prepare you for that and will hopefully help you evaluate what you encounter.

## Exercise: Do Some Research, Then Pray

Choose one (or more) of the methods listed above for selecting deities. Use resources available to you to do some searching. It’s OK to go on Wikipedia — check the Talk page of whichever deity’s page you land on if you see anything you’re really unsure about. The Talk page can be accessed at a link just above the page title, and it shows you what editors have been arguing about while maintaining the page.

Other options include looking up terms like *Norse pantheon list of Gods* in Google. When you search, you will see a combination of how-to articles, blogs, Tumblr posts, academic articles and pages, and so on. As you shift among different resources, note the creator’s perspective when writing the piece, especially differences between historical information and modern insights that arise from practice, political outlook, and other aspects of someone’s personality, habits, and culture.

Narrow down to one or two deities. Do another search, but just for them. You might use *-tumblr -twitter -pinterest* to remove things from the results if you’re using Google.

Here are a few questions to guide you:

-   What kinds of offerings are typically given to this deity?

-   What are their main symbols?

-   Were they worshipped in any specific regions?

-   What kinds of appearances does this God make in pop culture today?

-   Are there any surviving ancient prayers that you could recite for
    them?

Once you have done your research, write down the God’s name on a piece of paper and go to your small shrine space. After praying to the hearth Gods, pray to one of the Gods you have chosen. Greet them, say a few heartfelt words, and give an offering. The offering could be the same one that you gave to the hearth Gods or something based on your research.

If you know extemporaneous speaking isn’t for you, you’re welcome to prepare something written to read for the God during this first introductory prayer. You might give your name, the reason you are praying to this deity out of all of your other options, and provide some important information. What would you tell another person you’ve just met?

After praying, take a few moments to pause. Write some notes about the experience and do more prayers over the next few days.

The information you’ve learned about the God is also useful for contemplative practices.