# Purification

I pray after showering. For me, washing up and prayer are linked. Whenever I shower later in the day — for instance, if I’ve returned from the gym — I immediately think of the prayer beads at one of my shrines, even if I am also ravenous because I’ve worked up an appetite.

When I was just starting out with developing a solid prayer routine (after years of disorganized living during undergrad and grad school), this is how my mornings would go:

1. Wake up, feed cat, shower
2. Set the kettle on
3. Pray to the hearth Goddess and a God of the day, whom I selected at random
4. Upon the kettle ringing, I’d end the prayer and get ready for work

It was a simple routine — the kind of thing a young professional juggling many obligations and a chaotic mind could manage. New adulthood can be rough.

But why did I do the ritual after showering? I wanted to keep my purification practice as simple as possible.

*Ritual purity* can sound like a dour topic. The Gods are present everywhere, to everyone, and to everything, so why do we need to wash up if they’re already here?

As discussed in earlier chapters, when we do a prayer ritual for the Gods, we are engaging with both them and a plethora of symbols and signs that point to them. Symbolically, doing a purification is a “stripping away” of material garments and the excesses that harm our focus. We approach the Gods clean, with ritual preparation designed to get us into a focused mindset.

What you do for purification is up to you. We are all different people, and depending on our habits, you may emphasize physical or mental purification — sometimes I can get anxious and scattered, which means that mental purification is important to me, but someone with an easier time there might place less emphasis on it. In this chapter, we will go over some common techniques for both, and then we will discuss what to do in special circumstances. 

## Physical Purity

When we acknowledge the presence of the Gods, especially ones whom we hold dear, we are welcoming fond associates into our awareness. Like inviting someone over, someone might shower, put on clean clothes, and the whole works. Another person could freshen up by washing hands, putting on deodorant, and tidying their hair. Writing after the pandemic, when so many more people are experiencing fatigue and related issues as Long COVID side effects, it’s important to stress that you do what you can do. That said, you *should* shower before a structured shrine prayer/ritual if you have just had sex, if you’ve returned from a funeral or memorial observance, or if you are getting over an illness that left you bedridden. An *unstructured* prayer is one in which you just take a few breaths and pray wherever you are. It doesn’t always involve offerings; a *structured* prayer operates within the ritual framework you’ve set up.

*The Soul’s Inner Statues* is providing a generic practice, albeit one informed by the Platonists due to my bias. The principles in this chapter should give you a solid baseline for your household practice, regardless of who your hearth Goddess is and which Gods you chose to get to know in the last chapter.

Traditions that worship many Gods call for purifications in a variety of circumstances. If you decide to shift into a specific traditional practice due to fondness and inclination, you will learn techniques and protocols specific to that tradition. This usually happens during the onboarding and/or initiation practices, when you are taught what to do by a mentor or teacher.

During any purification, prayers or intentions may be voiced (e.g., “let me be pure”) to mark the action as sacred, but that is not required. This list of general methods is not exhaustive, so I encourage you to look up detailed instructions on how to do one of these things if you need to. Use YouTube if you want to see someone demonstrate how to do it, and use text-based resources online if you want a step-by-step walkthrough of one. Keep in mind that there are many ways to do each of these, so you may want to compare and contrast videos and instructional outlines from a few people.

* **Smoke cleansing.** This is common in the United States nowadays. To do smoke cleansing, you light a bundle of herbs, extinguish it to embers, and wave the smoke around the area or person(s) you want to cleanse. Sage bundles are often available in stores; however, rosemary and other herbs can also be bundled and used for this purpose. Smoke cleansing may go by other names, like *recels*, in specific cultural traditions. Please note that smoke cleansing and smudging are different. Smudging, while it comes from a term used in English for any thick purifying smoke (often, according to the Oxford English Dictionary, to ward off insects), via lexical drift, it has come to be the preferred term for the burning of dried substances in several Native American cultures’ ceremonies, and they have asked that others stop using the term for clarity.
* **Taking a shower, doing a ritual bath, or washing up.** This could be as simple as the morning shower you do before getting ready for work, a washing of the hands and face in the evening, or a fully-drawn bath. In some traditions, ritually sanctified water is poured over someone.
* **Salt water and herbs.** In this method, a dried fragrant plant (often rosemary or bay) is lit on fire and extinguished in saltwater immediately. This is then sprinkled on the person(s) participating in the prayer.
* **Salt water.** Salt is combined with water, and a prayer is said over the water to ask the Gods of purification to imbue it with cleansing power. Sometimes, the one creating the holy water asks for blessings from the sun or moon.

Remember that it is possible to modify any of the above purification techniques if need be. For any techniques that involve fire, please remember fire safety, as dried herbs can be brittle.

### A Brief Word on the Underworld Gods and Ancestors

Depending on context, deities related to the underworld — and ancestors — may need to be worshipped separately. This is strictly the case in contexts with the Hellenic Gods, when it’s important to *never* share a drink or food with underworld deities like Hades — they get all of it — and where the offering place to the underworld Gods is separate.

It’s a best practice to Google how an underworld deity is meant to be worshipped before you do it. If, during your research, you learn that the deity you are worshipping has *strict* separation (like in the Hellenic example above), I recommend using separate libation vessels and receptacles. Some traditions will allow ancestors’ photos to be placed at or near your usual household shrine; in others, it’s best to keep any ancestor shrines separate. A few years ago, when researching whether I could have my ancestors at the same shrine as my ancestral household Gods, I learned that in many ritual liturgies for Norse Gods, ancestors are toasted in the same ritual as Gods, and many practitioners put them together on shrines.

“Separation” is relative. Use a low shelf or a place on the floor that you put up and take down as needed, removing the items to a box when not in use. One could use a wood yoga block as a floor table to hold the ritual items, a cutting board with raised feet (IKEA has one), or even the storage box (if it’s sturdy enough). You could even convert a wall where you display dead family members’ photographs to an ancestor area by simply adding a small console table and a place for a candle and flowers. It’s advised to move photographs of the living elsewhere.

At my main household shrine, I do not separate out ancestors — but I use different incense burners and candles. I pray to household Goddesses and ancestors during the final few days of the lunar calendar. At a small meditation table that is low to the ground, I have a shrine for underworld Gods: I worship the Erinyes, Hades, Persephone, Hel, and Erecura. If I didn’t have a history of worshipping the Erinyes, I would just do a pop-up shrine for specific underworld Gods as needed at the end of the month and on special evenings, so don’t take me as a model on this.

The waning moon into the dark moon is an excellent time to connect with underworld Gods and ancestors, as are times of your life when you are in mourning.


## Mental Purity

Mental purification techniques are what can help center the mind and empower you to stay focused while doing ritual. It is simply *being able to focus on the ritual and on the God(s)* — nothing more, nothing less. Iamblichus, when describing Pythagorean precepts in the *Life of Pythagoras*, wrote, “In going to a temple, it is not proper to turn out of the way; for divinity should not be worshipped in a careless manner.”

Sometimes, this comes easily. Sometimes, calming one’s mind is like trying to soothe spooked horses.

There are times when I’ve imprudently checked email before my morning prayers and have been slammed with every awful thing in the world or a to-do list item that sets me into a panic. Or it can be a rainy day, or a day with horrible weather waiting for me, and I am already tense just looking outside and thinking of how on Earth I am going to get to work without slipping on ice. Rarely, arguments or bad life experiences can linger for days, even weeks. We all have things going on in our lives.

What I find useful during those charged days is to slow down. I try — sometimes unsuccessfully, but we’re all works in progress — to avoid checking the news or my email before praying so I don’t see things that make my stomach churn. I do a two-minute mindfulness meditation with an app to wind myself down.

It can be useful to have backup plans for when mental disquiet happens to you: Slowing down, you will not have as much time, which could stress you out even more if you haven’t planned ahead. We all know that things will disrupt our schedules sometimes. Strategize for the inevitable — pick a mindfulness technique to use in times of duress, and plan out different lengths of your rituals.

Non-meditation mental purification techniques I recommend are:

* **Take a social media break.** Pick one or two days each week to uninstall and block all of your social media apps — it works best if the days are always the same. Ensure that anyone who absolutely needs to speak to you has your contact information, and plan on what you will do while disconnected. If you are very online, this will not feel pleasant due to the dopamine withdrawal, so plan a few more self-care activities than you think you need. If you have a tough time following through, when I was trying to reduce my Twitter usage during the pandemic lockdown, I found great success in changing my password and putting the only record of the new password beneath an icon of Athene.
* **Write out your to-do lists or do a thought dump.** This is especially useful for anyone who wakes up with a sudden awareness of everything that needs to happen that day. Use paper or your favorite app.
* **Have some self-care techniques handy.** These can be small things like doing a mud mask, a sequence of stretches, or diving into a folder you have of heartwarming letters from friends. You could also listen to chapters from a self-care audiobook. One book I’ve appreciated so far this year is *Pause, Rest, Be* by Octavia F. Raheem.
* **Listen to music on an upbeat playlist, preferably without lyrics.** It’s harder to get earworms when you’re listening to instrumental music (and, speaking from experience, it can be very distracting to pray with a song stuck in one’s head!), and music has such power to restore mood. You can find happy and upbeat playlists that feature jazz, classical, ambient, kora, or whichever genre you love.
* **Do grounding and centering.** This is the visualization technique mentioned several dozen pages ago, and you can find recordings on YouTube and in some meditation apps. Essentially, you visualize being connected to the Earth and Sky.
* **Get enough sleep.** Sleep power-washes your brain and makes you ready for the next day. Do what you need to do to get to bed earlier.


### Exercise: What are your backup rituals?

This exercise builds on the idea of habit-bundling from previous chapters. Most of you are now worshipping the Gods in the morning or evening, with prayer added onto your other habits — like praying after you shower or after you brush your teeth.

Take out some post-it notes or pen and paper or open a digital whiteboard app like Mural. Depending on the time of day when you want to pray, write down what you tend to do at each step of your morning or evening for five scenarios:

1. You wake up late (or, for evening people, when you get home late).
2. You have lower energy than usual and need something simple.
3. You’re traveling and are in a hotel or a guest in someone else’s home.
4. People are visiting and you have to juggle hosting responsibilities.
5. You are experiencing high levels of stress or anxiety and need to focus on contemplative and de-stress techniques.

The ritual you’ve already been working on is your core ritual — the practice you can come back to as your “home base” when praying to Gods, daimones, and ancestors. Creating your backup rituals is an opportunity to embrace realism while maintaining connection.

Decide how much time you have for taking pause with the Gods in each of these scenarios. Thirty seconds? Two minutes? Five? Ten? Write down exactly what you will do and make sure your decisions are written out on notecards (or in an easily-accessed digital note-taking app) so you have them handy.

For the next four days, try each of the rituals. Make note of any adjustments.

* What feels satisfying? 
* What is dissatisfying? 
* Are you being realistic about the amount of time you have, the interruptions you may face, and elements of your life that always derail you when you’re under pressure? 
* If you’re sleepy or groggy, should you really do that meditation?
* What is the bare minimum physical purification you can commit to doing?

If you travel frequently, this is also an opportunity to set up a travel kit. Mine is simple: I found a small jar and bowl at Goodwill. I bring prayer beads for several Gods, and I have wood bookmarks of Athene and Apollon that I put in place card holders (the wood name card holders that you may have seen at weddings on the table). If I’m in a hotel, I use that. If not in a hotel, I spend a few minutes with prayer beads. One time, while staying with an acquaintance in a small apartment that had very little privacy, I prayed in the brief few minutes they were in the shower.


## The Kind of Consecration You Don’t Want

There is a concept for something in Ancient Greek Religion, *agos* and *enagēs*, that is worth mentioning here — while the concepts are culturally specific, they describe something that I would argue is universal. It may even be poignant for those of us living in places that suffered from intense violence in the past.

Conceptually, this term usually refers to someone doing something so wrong that it *consecrates them to a deity or divinity*, but in the worst way possible. The Gods are wholly Good, so they do not punish us. Behaviors that we engage in can, however, lead us down roads that will burn us because that is what is statistically likely and necessary in those circumstances. This term also has a *positive* sense in cases where it refers to the effect of swearing an oath — one swears by the God(s), and the action is consecrated to whichever God(s) were mentioned in the oath. This sets a boundary of necessity on one’s behavior.

In the negative sense, the behavior that consecrates one to a God — and badly — is the inverse of what we will cover in the chapter on virtue. I once had a coworker who told me that she was a terrible person and that I wouldn’t believe the things she’d done. I asked her if she had ever murdered or raped anyone, she said no, and that was the end of that. We often experience social shame and similar states as totalizing, catastrophic things. It is a growth process to learn to react appropriately to our own flaws. Most of us have not *personally* done truly terrible things.

I associate the negative necessity-driven consecration most strongly with the hostility of land spirits and the dead in places that have been the sites of genocide and similar blood crimes. For example, the Sullivan Campaign in Upstate New York massacred Native Americans to make more land available to Revolutionary War heroes, and the heinous act cannot be washed away. Among the Hellenic Gods, it’s usually Goddesses called the Erinyes (Alekto, Tisiphone, and Megaira) who demand appeasement once blood crimes occur. The effects of this state cannot be washed away with a simple purification; instead, cleansing demands work. Those of us taking actions to make things better — even if what we can do is small — are far better off than people embracing the outcomes of unjust acts.

>But how is it reasonable for descendants to pay the penalty for [the sins of] their forebears? Well, chiefly [because] they have inherited their estates and their gold and silver, often acquired by wrongful means, which is enough for them to incur a penalty. And then too the souls of the forbears suffer along with those of the descendants that are having a difficult time [here below]. And they [*sc.*  the descendants] do not suffer [these] punishments undeservedly, for the person who deserves to suffer such things is led into that kind of family, since providence and the divine nature and the gods who are the guides of fate transcendentally weave all things together in order and in accordance with justice.  
>
>*Hermias: On Plato Phaedrus 227A-245E*, trans. Baltzly &amp; Share, 2018, 101,10-20, all brackets theirs

Essentially, due to reincarnation, souls will choose the kinds of remedies they need to improve in their next life. Everyone who inherited difficult immoral legacies has the opportunity to improve things now. We were not put in this situation because we were bad people. We are in this situation because, when we chose this life, we trusted that we could come to do the right thing.

If you find yourself in this situation, do what you can, and make sure you’re not taking the spotlight for simply being a decent person. There are many platforms trying to lure us to warp our efforts to help into content for our “audiences” to show what great people we are, and all the while ad revenue is rolling into the platform due to our engagement. It is equally easy to overextend ourselves due to the magnitude of human suffering and horrible behavior around us.

## Guidelines for Purification in the Everyday

The guidelines below are ones that I am providing as suggestions for anyone praying to Gods. If you decide to pursue learning a specific tradition, you might find it has different protocols, and that’s okay — just have something.

* **Mourning.** Wait until the new moon to offer structured shrine rituals for non-underworld Gods. Cover shrines to non-ancestors and non-underworld Gods. You can still pray informally to any God, though. If a close relative dies, especially in the final few days of the lunar cycle, I recommend waiting a full lunar cycle and beginning again at the new moon after that. The night before you resume your ordinary prayer routine, put a photo of your new ancestor on the shrine where you keep ancestor-related items and do something meaningful for them.
* **Birth/adoption/fostering.** Take a bit of time (at least a few days) to settle in, and avoid most structured prayers and rituals during this time. After a few days (for adoptions/fostering) or weeks (make sure you’re physically recovered enough from the birth process to exert yourself), everyone showers or washes up and puts on nice clothes. Introduce the new member of the family to the household Gods. Eat whatever foods you find special and offer some of them to the Gods. For babies, this can include a naming ceremony.
* **Menstruation.** Be respectful if you are in a space where there are menstruant taboos (e.g., Kemetism, Hinduism), but otherwise, change your products before praying. Do not approach the shrine if you are experiencing debilitating pain. If you are in that much pain, you need to rest with a hot water bottle.
* **Sex:** Clean yourself up before you pray.
* **Sickness:** 
	* If you are having an acute sickness, do not do structured shrine prayers or rituals if you cannot get up to do ordinary household things. 
	* If you have a chronic illness and are having a flare-up, either refrain from praying or implement one of your backup rituals. I recommend thinking about your backup rituals in terms of having a low-energy prayer routine, medium-energy prayer routine, and high-energy prayer routine so your practice can fit the rhythm of the condition you are managing. It is OK if your lowest-energy routine is you in bed murmuring a mantra or favorite chant under your breath.
	* If you are asymptomatic or mildly symptomatic and can do normal activities, try your full or low-energy backup ritual. If something doesn’t feel right, focus on recovering. As mentioned in the bullet point above, there are ways to bring moments of reverence into your day without overextending yourself.
	* During any sickness, you may pray to healing deities, either formally or informally, or ask that someone else do so on your behalf. Just please rest.
* **Extreme stress:** Focus on your backup ritual. Make sure you do whatever is in your emotional first aid kit.

## Exercise: Pull It All Together

Do a brief meditation or grounding and centering exercise, then pray to a household God, ancestors, or one of the Gods you have picked after the previous chapter. See how taking pause impacted you. The next day, try a different type of purification exercise.

Do this for a few days while being mindful of the purification’s impact on you. Pick the one or two options that seem to work best and stick with them. You can always revisit this if need be.
