# Lifelong Learning

Throughout the first part of this book, we built up the foundations of ritual practice. In many chapters, I provided thought prompts and mentioned opportunities for follow-up research, but we didn’t dwell on them then — we focused on establishing a solid daily practice.

Ritual practices, like all routines, will iterate. You will go through seasons of your life when five minutes *is* all you have and other seasons when you can, and want, to do more. There will be days when showing up at shrine will be the last thing on your mind — maybe you’re anxious over an unexpected bill, you’ve lost a job, or someone in your family is going through a hard time — and other times when you feel the abundant presence of the universe all around you.

In music, it often happens that the composer or improvisational performer will select specific melodies to linger over — something to weave in and out as the music continues, a melodic thread that you can rely on for the unity of the piece. Think of lifelong learning like that: we don’t have the time or ability to follow up on everything, so we select what makes sense for us to explore.

For some people, these emphases may include engaging with learning material and/or joining formal or informal groups. Learning happens in all of these places, and as social animals, we all need some combination of this — but for now, we will focus on personal learning and how to develop a learning trajectory.

If you are completely good with your five minutes, the suggestions in this chapter can be adapted to any kind of adult learning — whether you are deepening your knowledge of the Python programming language or trying out mathematical crochet.

Many reading this book may already be thinking of ways to supplement their core prayer practice. This is the first part of three covering what to do now that you have set down some foundations. After this, we will talk about virtue and groups.

Practicing daily rituals and cultivating a conscious connection to the Gods is slightly different from studying something like religion, theology, or philosophy. These oceans are vast, and it is important to have a map. This chapter focuses on crafting that trajectory.

Let’s start by thinking about what we want to study.

In your notes on this book, and in your practice thus far, you may have jotted down questions, or the same thoughts may be cycling through your head over and over. Here are some examples:

* Why is Kaye talking about Platonism? Didn’t Plato just write political philosophy? How does this match what I learned in school?
* While praying to Ptah, I came across hymns that used terms unknown to me. What do these mean in Egyptian traditional religion, and how can I build up my knowledge so I understand what I’m reading?
* Stoicism talks about Zeus a lot. Is there a theistic way to approach Stoicism that is different from Silicon Valley self-help?
* Kaye mentioned a quotation from Proclus about seasons. What are my options for seasonal prayers to specific Gods?
* This book has been very heavy on the Hellenic Gods due to Kaye’s background. How do these concepts translate to the Gods *I* want to worship? If some concepts are less appropriate, why? What could I investigate instead?
* That’s a good point about needing to consider honoring Gods associated with yoga. What are some next steps that I need to take for my practice so I am doing responsible and ethical cultural reception?

Creating a learning plan is an important skill that is rarely ever taught. Before I got really into a Platonizing practice, I had heard from someone that everything I needed to know about the Hellenic Gods is contained within Plato. The first dialogue I read after hearing that, Plato’s *Symposium*, was astonishingly different from the scant excerpts assigned in school — it was *fun* — and I wanted to read more. I was so angry about having been deceived by inadequate educational exposure to Plato! Still, without a committed study habit and with a lot changing in my twenties as I finished school and started working, it was hard to read *anything* for fun, let alone Plato. The hours I spent on social media didn’t help. It wasn’t until my late twenties when I left Facebook that I started to rediscover my focus and mental energy.

## Content Is Written By People

Generally speaking, there are two types of content you will encounter when you are trying to learn more: academic content and practitioner content. Some academics also worship many Gods (and sometimes the Gods they study), but due to pressures in academia, it can be hard to figure out who they are unless you start talking to people. Be mindful of the tone used in academic publications — are the authors being respectful? Are they punching down on their research topic? This can provide a clue.

Academic content is most frequently released in the form of journal articles, books (jargon term: *scholarly monographs*), or gray literature (think PowerPoint slides, reports, and conference talk notes — often on faculty websites, Academia.edu, or preprint archives). Practitioner content may be in the form of social media posts, blog pieces and short manuals, and published books. Both academics and practitioners will post lectures to YouTube and other platforms of varying degrees of accuracy.

It’s important to be open to diverse perspectives and to not dismiss people because of their specific views. Use critical thinking when you engage with someone’s content. In order to make informed decisions about where to direct your attention, it can be helpful to do some research on authors and organizations. This might include looking up the author or organization’s name online, reading their free material, and examining criticism of their work. There are some lists online that claim they can reduce this work or that offer specific lists of “red-flag” terms, but don’t rely on these — many people, including myself, are sometimes clueless about word usage subtext and lexical drift. We live in a very politically-charged, polarized atmosphere, and online interactions can make these divisions seem sharper. Getting hyper-anxious about organizations, authors, and bloggers is not productive or useful when you are doing research on the range of practitioner perspectives about a Goddess or digging into protocols for cleansing a new home. I read plenty of people with whom I disagree on a variety of issues because some of their perspectives on praxis are pious and valuable, even if I sometimes find the person irritating or challenging.

However, there are some specific problems in the present century. Content on Nordic Gods, for example, is divided between far-right white supremacist groups on the one hand and very progressive material on the other. Proceeds from purchasing extreme right-wing materials put money into the pockets of people who are harming nonwhite American citizens (among others). The extremely progressive material may assume that you are only one awakening away from becoming a Marxist-anarchist, but it’s a more ethically sound purchase choice. Most moderates in American society accept the realities of cultural, ethnic, and racial diversity. In Norse polytheism, those who are not in the far right are encouraged by their communities to swing farther left because it’s seen as important for amplifying the message that extremism isn’t welcome in the religion.

Another challenge is the tendency for individuals to be pressured to monetize content in order to get by and make rent, especially with today’s wealth inequalities — often before a person has enough mastery of the material to be ready to provide a spiritual service to others. The Internet is filled with people who got into something 10 months ago and are trying to make money off of it. We always need to put the spiritual wellness and integrity of the ones we are teaching *first* in any learning environment, as being in an teacher/student relationship means that the recipient of a teaching has invested care of their soul’s development in *us*. It’s not to be taken lightly or carelessly.

Experience itself is multifaceted — someone may have a PhD in a topic related to the Gods or initiatory training in a specific tradition, and another person may have spent 20-30 years experimentally working through a non-initiatory practice on their own (although, truth be told, nothing happens in a vacuum). In library science, we call this “authority is constructed and contextual” (an information literacy frame as put out by American College and Research Libraries, also known as ACRL). It’s on us to discern which experts we want to trust, regardless of how that person acquired their expertise.

If you are engaging with informal content (like a blog), be sure to check the person’s About page and their blog’s first few posts. Usually, bloggers will write an origin story at some point to talk about where they are starting from, and even if that origin story is a decade old on their Wordpress (meaning you don’t know how it compares to who the person is now without reading their bio for their more recent activities), it gives you valuable information about them. For example, I used to call myself a “Hellenic polytheist” and write from a lens that I no longer agree with. I’ve changed how I present myself significantly over the past few years due to an increased awareness of and desire to respect modern Hellenes/Greeks. I have zero expertise in how a Greek person mediates their Hellenic identity, whichever God or Gods they worship, or what worshipping Gods means to them as individuals or as a community, and I now endeavor to make it clear where I am coming from. I am building up what a theistic cultural reception of the Hellenic Gods can look like in America (hopefully in a tactful way), so that’s where I focus my attention. That’s in my bio. The first post on my blog is something I wrote in my mid-to-late 20s about my values and practice, which looked very different at the time.

## Using the Library

Libraries can be accessed at the local, state, and national levels. You may also have access to the library of the institution where you work or study, or you may have a private library membership. Your state library will license resources for the entire state to use remotely — it’s worth knowing what those resources are. The same goes for your local library. All of this can be found on the library website.

When you visit your library’s website, check their policies on interlibrary loan and item delivery between libraries in the same state system. Interlibrary loan is often no-fee at academic institutions, but some local and state libraries will apply a fee to using it to offset the costs. Similarly, item delivery between locations may either be free or have a nominal fee.

Library databases contain a variety of content. Some databases blend newspaper, magazine, and scholarly materials together; others separate them. Scholarly resources are often *peer-reviewed*, which means that the paper someone submitted to the journal was read and scrutinized by other experts to ensure it was on the right track. This is why it can take some time for new research to appear — papers can be kept in peer review for months or years. Dissertations, while not peer-reviewed, are evaluated before a PhD candidate is allowed to graduate. They usually describe very innovative research and are wonderful to read, especially for research topics that are less well-discussed. They have very extensive bibliographies.

As a librarian, I can give you a few tips for using online databases, regardless of which ones you have access to:

* Find the documentation (or help files) for the database and read the sections in it on advanced searching.
* While many databases are moving to a single search box to remind users of Google, databases are still structured information resources that allow you to query specific fields. On either the database main page or in the advanced search, take a look at your options in the drop-down menus beside the search box. You may be able to limit by publication title, author, region, and other facets. I like searching in ProQuest or Ebsco databases for everything * except*  the full text unless I’m searching for information on an obscure Goddess. In those cases, I want any anecdotal reference I can find anywhere in the full text.
* When interacting with search results, do not forget the filters on the left-hand side! Try to filter to scholarly/peer-reviewed resources, magazines, and so on — just to see how the resources you are finding differ.
* Use a reference management tool like Zotero to organize the resources you find and prevent yourself from having to log in to repeat searches and find information again. Zotero has a built-in PDF annotation tool, and it supports note-taking.
* Pay attention to the keywords that the databases assign to items that you find useful. These are jargon terms that may be submitted by the publisher/author, or they could be subject classifications assigned by the database provider. Regardless, they can help you standardize your vocabulary and “think like a machine” to identify other relevant works.
* Click on any text that is hyperlinked in the item records to see what happens. Authors, keywords, you name it! This is how digital serendipity works.

Keywords, Library of Congress subject terms, and other helpful information are also available in the main library catalog. Whenever you find a book that is helpful to you, look in your local library catalog or on WorldCat for the item. Jot down notes of what terms are applied to the book and use those search terms next time you are looking things up.

Google Scholar behaves similarly to a library database, but it is a search engine, and it uses automated scraping with no human quality control. This means that Google Scholar contains a lot of information, but it can misidentify some items as scholarly when they are not, and it sometimes grabs the wrong information about an article. Still, if you are outside of academia, it lets you know what scholars are producing. The documentation on how to use advanced searching is essential for getting what you need.

As an example search, if you wanted to search for Belesama with both name spelling variants, but wanted to exclude mentions of Britain, this is the advanced Google (or Google Scholar) search you would do:

~~~
(Belesama OR Belisama) AND Goddess -Britain
~~~

The same search would work in a scholarly database, but the word *NOT* may be used instead of the minus sign to exclude terms. Some of my examples will use multiple words in quotation marks to mark a phrase, but you can also use quotation marks around a single word to keep Google from *stemming* the word, or searching for variants. I sometimes use quotation marks around the word “Gods” so Google is forced to find the plural. Databases, on the other hand, frequently make you explicitly mark that you want stemming to occur by using an asterisk or question mark — *God\**, for example, will match *God*, *Goddess*, *Gods*, *Goddesses*, *Godfrey*, and so on. *Wom?n* will match *woman*, *women*, *womxn*, and other variants. There may be some variation, though — check the help files.

If I wanted to do a slightly more complicated search, this time for Apollon’s worship (note: the term cult/cultus is a neutral archaeological term) in Asia Minor:

~~~
(Apollo OR Apollon) AND (cult OR cultus OR worship) AND "Asia Minor"
~~~

If you don’t have access to an article directly, this is when you use interlibrary loan, check the author’s website for a repository version of the article (more and more common due to the increase in open access), or ask the author directly. Books are easiest to find via interlibrary loan or a library purchase request, and especially for small publishers, going through official channels to acquire the book makes a huge difference to the publishing house and authors.

### Do You Have Alum JSTOR Access?

At least in the United States, many people who have graduated from college have graduated from institutions that provide alum access to JSTOR. Look at your alum website, and if you can’t find anything about that, contact the library. This will broaden what you can do on your own without interlibrary loan.

### Using AI Output

ChatGPT was released on November 30, 2022, and this is a last-minute addition in early February 2023 to the book to reflect the sea change ahead of us with how people do research. AI-based research and writing tools can be helpful for answering questions, but they should always be used in conjunction with fact-checking tools and books written by experts. AI “eats” a corpus of texts — often a very large one — that it then uses as its basis for the output it gives. It has no judgment capacity for telling what is correct and what isn’t, and the risk of using it is highest among those who are asking important questions about a topic they are less skilled in.

The best way to integrate AI into research on spirituality-related topics is to figure out vocabulary and brainstorm next steps. AI is great at being a sounding board so you can prioritize the books, blog posts, and podcast interviews/episodes that will give you grounded information from people. Text-based AI like ChatGPT can also help you create a manageable research routine based on the constraints you give it. (Example: “I have an hour each weekday evening before my kids come home to focus on my goals. Give me a 45-minute routine for prayer and spiritual study that will help me meet x, y, and z goals.”) What I have noticed about AI is that it is very confused about Platonism, and its confusion likely extends to other philosophical schools. It will also frequently include incorrect information in lists and then say “yes, I was wrong, I did not give you what you asked for” when you tell it so. Use AI for what it is good at — generating output that doesn’t require a ton of thought and as a space to do more interactive freewriting — and do not outsource thinking to it.

## Finding Book Reviews

If you Google an author’s name or a book title with the phrase “book review” (with the quotes around “book review”), you will find reviews that Google has indexed beyond just what’s on Amazon. If you don’t have ideas for a specific book, just put in a topic (such as divination, worshipping Kemetic Gods, Shiva in yoga, prayers for Gods):

~~~
"book review" AND Kemetism AND beginners

"book review" AND (Kemetism OR "Egyptian Polytheism" 
AND beginners

"review" AND polytheism AND theology site:goodreads.com

"book review" AND beginners AND ("Norse paganism"" OR "Norse polytheism") -site:amazon.com
~~~

Many of the books in the Google results will be worth reading, although it’s good to know an author’s perspective before you jump into their work.

## My Plan for Plato

This is the advice that, after several years studying Platonism-related topics, I would give to someone embarking on an in-depth study. What I hope you take away from the example is how important flexibility is, yes, but I also want to convey that we don’t all have it completely figured out immediately. It’s okay to do something when you’re not totally sure where it’s going.

If one has heard that Platonists were spiritual sages in antiquity — say, from Linda Johnsen’s *Lost Masters: Sages of Ancient Greece*, one may attempt to dive directly into Plotinus like I did when I was in my early 20s and have a disorienting and discouraging experience. No matter how exciting an author seems, starting with the fundamentals is crucial to understanding what is going on at all. I had only read the *Symposium*, *Ion*, and a few other Platonic dialogues at that point. While I had read Sallust’s *On the Gods and the World*, it hadn’t been framed to me at the age of 20 as a Platonic text, so I thought it was simply amazing polytheistic theology without knowing where it came from.

The made me realize that I needed to have read more Plato. So. I bought one of those giant books with every work by Plato and started reading.

That was also a mistake.

The breakthrough happened when I learned that there was such a thing as a dialogue reading order (Rowe, 2015). There is a modern, which-one-did-he-write-when order (which I don’t recommend), and there are several systematic treatments that were used in the ancient world when reading Plato — one with a lot of dialogues and another with a selection. The selection of dialogues is the Iamblichean reading order, named for Iamblichus, a Syrian Platonist who was instrumental for reinvigorating traditional religious practice through the careful application of Platonic doctrine. He assigned twelve dialogues: *Alcibiades I*, *Gorgias*, *Phaedo*, *Cratylus*, *Theaetetus*, *Sophist*, *Statesman*, *Phaedrus*, *Symposium*, *Philebus*, *Timaeus*, and *Parmenides*.

At first, I read the dialogues on their own, and I reached the *Symposium* with that method. I picked up one of the Platonic commentaries (the one by Hermias on Syrianus’ *Phaedrus* lectures) by happenstance and discovered that its exegesis of the material was extremely useful and groundbreaking. However, when I read the *Parmenides* commentary, I felt like the rug had been pulled out from under me because my understanding of the rungs on the ladder from the One to Matter was almost nonexistent in any meaningful way. I continued reading Platonic texts and found some helpful modern scholars’ work at good price points that helped me understand the metaphysics a bit more. Then, I started listening to the *Secret History of Western Esotericism* podcast (despite not identifying as an esotericist) because its episodes on Plato were very helpful. A few people on social media were extremely helpful and generous with their time in explaining some concepts when I had questions. I read the *Parmenides* before the *Timaeus* and only read the *Timaeus* after the *Republic* and *Laws*, which I added due to never having read them. At about that time, I realized that there was no one correct reading order for the commentaries and that swallowing them down as simultaneously as possible would give me the best rough outline. The pandemic happened all of a sudden (when I was reading the *Laws* and finishing up reading some of Proclus’ essays on the *Republic*, which had been translated into French); spiritual Platonists started posting content to YouTube — Tim Addey, Mindy Mandell — and I found other content from Pierre Grimes. The combination of reading, audio, and visual content was extremely helpful, as was the lockdown isolation. I learn very fast when in immersion environments, which I figured out in college, and because I have a prayer practice, I was able to cross-reference the mystical parts of Platonism against my own experiences. I eventually found some virtual groups to engage with, all based on Zoom. I continued — and continue — swallowing down commentaries and other Platonic writings.

### My Advice on Reading Platonic Texts for Others

What I would encourage, based on my experience, is to read *Alcibiades I*, *Gorgias*, and the *Phaedo*. Then, stop reading those and pick up Radek Chlup’s *Proclus: An Introduction*, which introduces key elements of the system in a manageable way. Take note of the tables included in that book — they are very useful. Read the *Anonymous Prolegomena to Platonic Philosophy*, an ancient text that introduces how Plato is read in the Platonic curriculum. Several articles by Danielle Layne (see bibliography) contain useful tables for understanding how Platonists read dialogues, and [Edward Butler wrote an article for a general audience on the polycentricity of the Gods](https://www.academia.edu/30296722/_Polycentric_Polytheism_pp._37-40_in_Witches_and_Pagans_32_June_2016) that can be used to drive those concepts home. Deviate from this to read Iamblichus’ *On the Mysteries/De Mysteriis*, which will help to ground all of the cerebral in practical prayer and attentiveness to the Gods. Ensuring that one maintains an active prayer practice while learning is absolutely crucial to gaining insights.

Read the *Alcibiades I* again, this time in conjunction with one of the commentaries (remember: interlibrary loan) — Proclus and Olympiodorus both wrote on it. Read Tim Addey’s *The Unfolding Wings*, Sallust’s *On the Gods and the World*, and Mindy Mandell’s *Discovering the Beauty of Wisdom*. For podcasts, listen to the *Secret History of Western Esotericism* from the beginning, *The History of Philosophy Without Any Gaps*’ early episodes, and look up any podcast interviews with Gregory Shaw or Edward Butler. From there, read the *Gorgias* and its commentary, the *Phaedo* and its commentaries, and continue in that fashion for the dialogues that Iamblichus recommended until you finish the *Philebus*. For the Parmenides, first read Aristotle’s *Metaphysics* and Syrianus’ response to it (two volumes, one on *Metaphysics 3-4* and another on *Metaphysics 13-14*), then read the *Parmenides* alongside Proclus’ commentary. While reading the commentaries, cycle to treatises from Plotinus as they are mentioned in footnotes and endnotes. Read the *Republic* and *Laws*. Read the *Timaeus* and its commentary. The *Elements of Theology* and *Platonic Theology* are useful to approach now, as are any other texts by Aristotle you may be interested in (or not). Read Plotinus’ *Enneads* and any of Proclus’ essays or Damascius’ other works. It’s all an iterative process, and once one has the trunk fairly solid, the branches may grow where they take you closer to the light.

If you’re only curious about the philosophical system and do not want the deep details, reading something like *Discovering the Beauty of Wisdom* alongside the *Alcibiades I*, *Phaedo*, *Apology*, and *Phaedrus* will get you a decent idea. I recommend that anyone read Iamblichus’ *On the Mysteries*, though, and the *Anonymous Prolegomena to Platonic Philosophy* is a very good read. To be perfectly frank, whenever I got discouraged writing this primer on worshipping Gods because it seemed daunting or I doubted my relevance, skill, or capacity, I just thought back to Iamblichus to anchor and guide me. Almost everything we need to know about honoring the Gods is in Iamblichus or Proclus.

## Creating Your Plan

The above may have been overwhelming. For one, Platonism involves reading a lot of scholarly monographs (which I didn’t really even discuss) — someone studying Norse concepts of the soul or divination or modern devotional poetry will skew their reading more towards practitioners’ publications. If you are studying Stoicism, the modern popularization has made it very easy to find writings about Stoic philosophy, but there is less available on the open web about its spiritual aspects.

Here is what I hope you took away from the prior section on getting more familiar with Platonism:

* Choose multiple formats. Audio, video, and writing are all represented above.
* While starting out with a survey book of a topic may be ideal, you do actually need a sense of the material itself. In the example above, my advice to read a few dialogues before getting into other types of content is based on that premise.
* You don’t need to have it figured out all at once. You can use the works cited by someone to build out and adjust your reading list.
* Learning can be overwhelming, as it pushes us outside of our comfort zones. That’s why it’s learning. During the lowest points, do what you can to ease the discomfort and remember why you’re doing this.
* Put your audiobook and ebook apps on your phone’s home screen and hide everything that isn’t reading material. Ensure that books you need to read are located within arm’s reach on the couch.

Above all, keep your plan sensible. If you have half an hour a day to study between when you put your kids to bed and when you want to spend time with your spouse — or if you know that your only alone time at home will be when you wash the dishes with headphones in — do not choose a plan that is unrealistic about the formats you need or the reading speed you have.

If you have a condition that impacts your focus or stamina, put your health first and seek out advice from others with similar conditions about how they build time for learning and personal enrichment into their lives. For example, magazines like *ADDitude* (for people with ADHD) or *Momentum Magazine* (for people with multiple sclerosis) are good choices for getting the support you need, as they synthesize information from medical experts and community members. Typically, you can find such publications via Google or in resources lists on nonprofit websites.

If you frequently use social media, it’s likely that your attention span will have deteriorated from when you were younger. Consider doing a social media fast for a few days while you start up your new study habit. If you frequently binge-watch shows, reducing your screen time to 1-2 episodes per day can improve you experience of the show and give you some much-needed reading time, as research shows binge-watching can reduce the amount of enjoyment we get out of savoring new episodes.

Here are some guidelines for getting the most out of your learning plan:

* While you read, take notes. Keep a notebook or write in the margins so you can roll around in the text and react to what you’re reading. If you are using ebooks, export the notes when you are done so you can review them.
* Never underestimate exercise. I’ve found that doing some exercise in the early evening helps me bounce back from mental fatigue — something as simple as a walk or a few sun salutations.
* Build on what you’re learning. Start writing essays about things that interest you. You’re not being graded. *Not being graded is magical.*
* Celebrate small wins. When you have finished something tricky, do something nice for yourself — put on your favorite song, dance, give yourself a hug, or say something good about yourself in the mirror.

While you are studying, you will likely come across courses (free and paid), reading groups, and other ways to learn from experts. Take advantage of the opportunities that are affordable to you, and don’t assume that a higher cost equals a better learning experience. Be wary about becoming a “groupie” for a specific expert — direct your devotion at the Gods, not at human beings, and always be aware that the ones you are learning from are humans with merits and flaws. If someone is trying to induce the fear of missing out (FOMO) in their marketing materials, or if they’re positioning themselves as the only safe harbor, be suspicious. They probably don’t have the exclusive knowledge they’re claiming to possess.

## Exercise: Create A Content List

Brainstorm a topic that you want to know more about, ideally related to worshipping Gods. Identify content items that you can engage with to learn more about it. They could be books, videos, podcasts, courses — you name it. Look up reviews for the books and learn more about the podcast, video, and book creators. Narrow the resources down to five.

Then, find learning time in your schedule — one or two blocks of time per week. Use that time to engage with the materials you have selected.


