# Virtue

>Virtue might be described as the perfection of the soul and proper balance of its life and as the highest and purest activity of reason and intellect and discursive intelligence. Let the acts of virtue be taken, above all, as being boniform, excellently fine, intellectual, noble, full of moderation, participant in appropriateness, promoting moral advancement, aiming at the best end, and graceful.  
>
>Iamblichus, Letter 16: To Sopater, “On Virtue,” trans. Dillon and Polleichtner

Cultivating virtue and adhering to an ethical system are absolutely essential for engaging with other people, and many philosophical and theological systems place a heavy emphasis on developing a healthy relationship between ourselves, other people, and the broader world. If we define virtue as the excellence by which we are perfectly realizing our soul’s capacity, becoming more virtuous is also an offering that we can give to the Gods, an intangible method of connecting our own partial existence to their expansive, limitless oneness. This chapter approaches virtue from a summarizing, introductory standpoint, with plenty of links. The goal is not to sell you on a specific system of virtue and ethics, but to familiarize you with the terrain and what you might look into on your own.

Many of us do not think about virtue, morality, or ethics constantly, at least until we are wronged by others or we need to make a hard decision between doing what is convenient and doing what is right. In Proclus’ *Ten Problems Concerning Providence*, he writes (in alignment with Platonic teachings found in its texts like the *Phaedrus* and *Phaedo*) that virtue, and what we develop inwardly, remains with us through even the most extreme misfortunes. We are often thwarted from achieving external delights, he says, but we can always turn inward to develop our inner core. In *On Providence*, Proclus expresses admiration for the teachings of Epictetus, especially the one letting go of what we cannot control. Plato himself in the *Phaedo* had Socrates say, “For the soul goes into Hades with nothing else except her education and nurture, which things are said to be of the greatest benefit or harm to the one who’s met their end — right from the beginning of their journey There” (107d). We carry our upbringing and what we learn with us as habitual and experiential imprints. Like a spiritual form of “you are what you eat,” our goal is to develop frameworks, using the virtues as templates, for improving our inner state and bringing it in alignment with the Good.

We often think of virtue in terms of self-denial, with an image of a celibate monk or nun or other renunciate in our minds. Some of us think of something more sinister: the many horror movies set in Puritan-era New England or the exposés on unhealthy cults and the way that they obsessively control their members. The tension between embracing embodiment and fleeing from external pleasures has always existed, both in spiritual and secular philosophies and lifestyles. The guest-house metaphor I used for thinking about ancestry many chapters ago can also be used here as a bridge between this self-denying perspective and a perspective that embraces embodiment. Many virtue systems focus on correct behavior and action because we are acting out roles, and like actors in a play, taking too much of the role into ourselves can be destructive, especially if something happens that jars our most extreme negative emotions. In addition, without limits, we easily succumb to addictions and unhealthy patterns that we convince ourselves are freedoms, but which are actually ropes that bind us to specific pleasure-driven behaviors. We all occasionally struggle with negative self-talk and disappointment when we fail to live up to our best, and rather than punishing ourselves, we can use those moments as learning opportunities to inform how we behave in the future. Platonists like Damascius, Proclus, and Olympiodorus point out that many of the vices we have are coping mechanisms and “shortcuts” that we incorrectly assess will bring us happiness. Here is an example passage from Olympiodorus:

> And the pleasure-lover longs for divine ease, about which it has been said, ‘the gods who live at ease’ – that is the kind of idea that this person has in mind, but since he is unable to attain it, he fights over shadows (*skiamakhein*), the reflections and expressions of this [higher idea]. And the money-lover longs for fulfilment and self-sufficiency, because self-sufficiency and fulfilment are divine – and so he desires this; but since he is unable to attain [the real thing], he grasps after it by loving money. And again, the reputation-lover longs for the god who is sufficient and freely giving, even if he is unable to attain this. (But being fulfilled (*teleion*) and being sufficient (*hikanon*) are not identical; for fulfilment is just needing nothing from another, whereas sufficiency is a matter not only of having no needs, but also being able to give freely to others.
> 
> Olympiodorus on Plato’s First Alcibiades, trans. Michael Griffin, from 42-43 of lecture 5, all brackets from the translator

Here, what is interesting is the way Olympiodorus likens specific types of desires to our misapprehension that they will make us more like the Gods — in imitation of them, we reach for what is *not* them, and this leads us to a frustrating condition that in current times is known as hedonic adaptation. We will always be frustrated in our attempts to gain money, power, and pleasure, and we will always desire more; cultivating virtue and interrogating why we want what we want reduces the amount of suffering we experience. It is like cutting off the heads of a hydra and thinking it’s all taken care of only to see more grow instead of mindfully cauterizing the neck’s stump.

Ethical guidance to follow may include things like the Delphic Maxims, Solon’s Tenets, guidance within the Hávamál, Kemetic teachings on Ma’at, the Pythagorean Golden Verses, Stoic writings, Aristotle, the yamas and niyamas of yoga, and so on. There are often commentaries on these guidelines written by practitioners and academics. I encourage you to read as many systems as you need and to think about how they relate to your own life — many date back to ancient times, society has changed, and it can be useful to examine what has remained the same and what is different. The Delphic Maxims, as one example, include one that reads “rule your wife.” Contextual to the culture at the time, men often married women much younger than them, most women did not enjoy vast personal freedoms, and the same stereotype existed about women being overindulgent spendthrifts that exists today in many parts of the world. The maxim is actually about ruling the parts of us that are less seasoned and more prone to desire, all bundled in a metaphor that many women have issues with when we read it.

In many cases, people will choose a system that is related to Gods they worship, especially since we have been habituated by the prevailing circumstances in America to view ethics as something given by religious tenets. At other times, it is more driven by philosophical school, regardless of the specific Gods someone worships. Once someone starts looking for other like-minded people, it is common for them to study a specific text or way of life together. In spiritual and religious organizations, learning a set of values may be part of the onboarding process.

One can even examine secular ethical and virtue writings, alone or in community, to tease apart the best elements of a virtuous life. This is especially true nowadays, as many philosophers, scholars, and public speakers who focus on virtue, ethics, and morality are writing from a nonreligious standpoint, albeit one that is often informed by Christianity. This secular writing can be very helpful for reflecting on the values we learned as children in our society. Often, we pick up things without thinking deeply about them, and it’s the process of reflection — on the sacred or the secular — that can truly help us become more excellent to one another.

## A Continuous Process

Many people were taught in their childhood that missteps and incorrect behavior were shameful, often in ways that made them feel powerless to change how others had judged them. Some were even taught a particularly toxic form of either/or thinking — you are either virtuous and saved or twisted and damned. It is equally easy for people to react to an ethical system robotically, as if we are executing a computer program. First, we are not robots. Second, we must approach virtue and ethics from a growth mindset. We all start somewhere, and we all have aspects of our lives that we nail and other parts of our lives where we need to put in more work. This is true regardless of how embarrassed or ashamed we feel in the moments after we do something misguided or something awful happens to us. Gray areas will always challenge us to find solutions and stretch our abilities. While sometimes painful, we learn valuable lessons.

A growth mindset is adequately described in this passage from Plotinus:

>If you do not yet see yourself as beautiful, then be like a sculptor who, making a statue that is supposed to be beautiful, removes a part here and polishes a part there so that he makes the latter smooth and the former just right until he has given the statue a beautiful face. In the same way, you should remove superfluities and straighten things that are crooked, work on the things that are dark, making them bright, and not stop ‘working on your statue’ until the divine splendour of virtue shines in you, until you see ‘Self-Control enthroned on the holy seat”
>
>Plotinus, Ennead 1.6.9, trans. Gerson et al.

In the above passage, we are encouraged to actually work on the parts of ourselves that seem daunting. From a practical standpoint, we can ask ourselves:

* What are my unhealthy habits?
* What do I lie to myself about?
* What have I been avoiding?
* Last time I had a conflict with someone, what went wrong? Is there anything I need to learn for the next time I am in a similar situation?
* In the past, what has worked for me when changing behavior? What hasn’t worked?
* What are my strengths?
* How am I going to build self-care and self-compassion into my personal growth process?

The above questions may cause some distress, especially if we have been ignoring something for a long time. Look at pictures of cute animals, listen to relaxing music, and take care of yourself. Moral self-image stress can cause a lot of internal friction.

On a personal note, James Clear’s *Atomic Habits*, Cal Newport’s *Digital Minimalism*, the Fabulous App (see your device’s app store), the *Daily Calm* meditation app, and the interpersonal trainings on LinkedIn Learning have all been immensely useful to me over the years. James Clear wrote, “You do not rise to the level of your goals. You fall to the level of your systems” (2018). This has proven true for me, and it’s one of the principles I used when describing how to start a prayer routine. The Fabulous App has helped me with procrastination and avoidance, two things I know I struggle with, by building better habits.

If you are experiencing mental health struggles, I encourage you to see a therapist. Talking through elements of our life with someone else can be a very valuable experience, especially for those of us who had rough childhoods and who developed toxic shame early in our lives. If your life feels overwhelming and you are considering an exit, please call the National Suicide Prevention Hotline (USA) at 800-273-8255.

### Platonic Virtue

On a functional level, one of the reasons we have so many issues — at least in Platonism — is due to the operation of our three-part (tripartite) soul. As Plato’s Socrates describes in the *Republic*, we have an appetitive soul (the seat of desire), described as many-headed; a spirited soul (the seat of emotional reactions), described as a lion; and the rational soul (the seat of our logical thinking), what makes us human. In embodiment, the soul’s rational faculties are driven this way and that by the two layers of our irrational soul (appetitive and spirited). Many issues in life are due to not having a good handle on our impulses. The virtue that restrains the appetitive soul is temperance; the spirited soul, courage; and the rational soul, prudence. When everything is working together properly, the soul can manifest justice and its highest potential. Mishaps and brief falls are inevitable during our embodiment. If you fall off the bike, you get back on.

Platonism incorporates some elements from Aristotelian and Stoic teachings to classify levels of virtue according to nature, habitude (also called ethical), civic society, purificatory, contemplative, paradigmatic, and hieratic. Most people do not aim for the contemplative, paradigmatic, and hieratic virtues in their lives; to be functional members of society, we need to have everything up to the civic virtues nailed on a routine basis. The purificatory virtues signal a turn from that outer life to our own interior, culminating in the hieratic, which backflows outward from us and towards others through ritual action and care for the community. Tim Addey’s *Unfolding Wings* discusses this in greater detail (Chapter 4), as does Mindy Mandell’s *Discovering the Beauty of Wisdom* (Chapter 4). A good overview from an ancient commentator is Proclus’ Essay 7 on the *Republic*, available in Volume II of a translated collection from Baltzly et al. Proclus and Olympiodorus also focus on virtue in their commentaries on *Alcibiades I*. [The translator of Olympidorus’ commentary on *Alcibiades I* did a video presentation on the Platonic ladder of virtue](https://www.academia.edu/44622434/The_Neoplatonic_Scale_of_Virtues_in_Olympiodorus_Body_and_Soul). Mindy Mandell’s YouTube channel about Platonism includes several videos that walk through her teaching lineage’s position on limiting beliefs and how to overcome them, including the videos “All About Platonism: Purification” and “The Philosopher’s Journey” [on a playlist of practical advice](https://www.youtube.com/playlist?list=PLoPggAqEExYbxQktPv8XGWm2bnPXUnuZw).

Usually, the things we want to work on are bad habits. Occasionally, we have errors in our civic judgments — our sense of what is politically right and wrong may be off. Sometimes, we cannot handle our cognitive dissonance because it gives us pain. If we gather our courage, confront that dissonance, and overcome it, we may reactively seek out the first ideology that seems “correct” and that soothes our feelings of pain about our past judgment mistakes. This perpetuates the cycle of ignorance. It is better to explore *what* was wrong about our old beliefs and to critically interrogate every system we approach — to think for ourselves. We want to catch a glimpse of Justice Itself, and we want to see how the Form of Justice breaks upon the bodies of the worlds to en-form what is around us. This is the only way to make our civic and political environment better. Tim Addey wrote, strikingly, that “conflicting temperaments are often harmonized and reconciled by communal forces [at the habitual level], and [they] only reemerge during the breakdown of civil order” (2011, p. 67). I often think about that when I look at the major political upheavals we experience today and how chaotically people react to them.

Virtue has a direct connection to our capacity to receive the Gods when we pray. Working on it calms the discord within our heads. It pulls the soul back from the many desires and passions into unity. It soothes those constant inner voices and feelings and the whirlpool of anxieties we feel. It teaches us the difference between what we must accept and what we can act on. When we are calm inside, we can more easily focus when we pray, and we are not wasting valuable cognitive energy, so we can be more effective people. In the *Laws*, Plato writes:

>[T]he finest and truest of all principles, in my view — which is that for the good person, in the natural order of things, sacrifice to the gods, contact with them by means of prayers and offerings, and religious observance of every kind is at all times finest and best, the most likely to result in a happy life, and far and away the most appropriate thing for [them].
>
>Laws, 716d, with some gender-neutral modifications

## Exercise: Self-Compassion Meditation

Self-compassion meditations are everywhere. As someone who does not teach meditation, this exercise has two components:

1. Locate a self-compassion meditation.
2. Do the meditation.
3. If you like the meditation, do it for a few weeks — pick the date, time, and place you will do this. If you don’t like the meditation, try another kind of self-compassion meditation until you find one that works for you.

When thinking about where we fall short of an ideal, all too often, we judge ourselves with more harshness than we deserve. Some of us may even shut down and think, “Well, if I’m not perfect, or with the background I have, what is even the point?” Cultivating self-compassion blunts the impact of these feelings and helps us remain grounded in our inner goodness and potential to be better people.

When you locate a compassion meditation, try to figure out what the meditation is asking you to do. Compassion meditations that ask me to think of a nice thing I have done for someone else make me confused and worried. The first time I tried it, I failed to think of anything, so I looked online to see what people meant. It turned out that many people classify behaviors as “nice” that I was taught were basic courtesy. Even at work, my job is focused on helping people find what they need, so giving a stranger my time and attention is part of a normal day. I have more success with the type of compassion meditation in which one imagines feelings of goodwill and loving-kindness towards others. Some meditations ask us to visualize receiving love from someone who cares about us. I usually think of a God during those segments.

If you use Headspace, there is a self-compassion course in the app by Dora Kamau; she also has a website and [a presence on Insight Timer](https://insighttimer.com/dorakamau). The Headspace course uses my favorite type of compassion exercise. Other meditation apps (such as Calm) will show you what is available after doing a keyword search. Dr. Kristin Neff, a researcher who does significant work on self-compassion, has [free downloadable meditations on her website](https://self-compassion.org/guided-self-compassion-meditations-mp3-2/). 

## Exercise: Contemplate Ethical Guidance

During this contemplation exercise, find some time when you will not be disturbed for a few minutes. Find a pen and paper to write down any thoughts that come up.

Begin this exercise with a prayer to the God(s) of your choice. Then, read aloud the following:

>Put more trust in nobility of character than in an oath. Never tell a lie. Pursue worthy aims. Do not be rash to make friends and, when once they are made, do not drop them. Learn to obey before you command. In giving advice seek to help, not to please, your friend. Be led by reason. Shun evil company. Honour the gods, reverence parents.
>
>[*Lives of the Eminent Philosophers*](https://en.wikisource.org/wiki/Lives_of_the_Eminent_Philosophers/Book_I#Tenets_of_Solon), Tenets of Solon, Diogenes Laertius

Taking each sentence on its own, what comes up for you? Where in your life do you display the value expressed in this tenet? Where could you invest more work, and how?

Do this for each of the elements in turn. When done, thank the God(s) and use the document you have created to create actionable plans for self-development. Feel free to move on to investigate other ethical texts and repeat this exercise. Usually, you will want to reflect on a small chunk of the material.


