# Navigating Groups

A *group* is any collection of people, whether it has convened informally or formally. It could be your family, a collection of people you’ve met online, or a few people in town with whom you get drinks and catch up. It could also be your team at work, the members of an organization, or those on the membership rolls of a specific religion or who attend events associated with a spiritual group.

In this chapter, we will discuss groups, both in a general sense and in terms of what you need to check on to avoid cults and toxic people. What I have to say in this chapter is informed by the realities of the social media era, a time in which we are more connected than we have ever been in human history, yet feel more alone and isolated (Jarzyna, 2021). Having a supportive, solid group of people to bounce ideas off of and who can come together for rituals, virtual or in-person, is a wonderful thing that can supplement one’s at-home practice.

*Homo sapiens sapiens* is a species that evolved to be most at ease in tribal bands of 50-200 people. We need other people for psychological safety, well-being, and a sense of belonging. We have trouble with groups larger than that because our brains struggle with depersonalizing others. Even the most introverted person wants to feel a sense of respect and care from people in their immediate community. In a spiritual sense, it can be good to have family and friends to decompress with about spiritual issues and with whom you can celebrate larger holidays, and it is vital for checks and balances to have level-headed elders and friends who can give both critical and supportive feedback.

Jean-Paul Sartre wrote that [Hell is other people](https://www.vox.com/2014/11/17/7229547/philosophy-quotes-misunderstood-wittgenstein-sartre-descartes), and to a certain extent, that is true. In the piece I just cited, the writer explains that it’s not because people irritate us and we have painful interpersonal drama, but because we are judged and judge in social situations. We can be both the victims of cruelty and the ones who mete it out.

Now, in the context of many Gods, there is no hell that directly corresponds to the Christian one — for example, the closest in the belief system I follow would be Tartarus, which is where souls that have made many bad decisions in their most recent life are purified. (Imagine if you were put in a room with a firm, yet compassionate, therapist-judge and couldn’t leave until you’d worked through all you had going on in your last life. To call that *rough* is an understatement.) Other belief systems have similar states of being. The point, however, is that we can be awful to one another. Sometimes this awfulness arises out of ignorance or oblivousness. At other times, someone wants to gain status and is willing to lie to get it. We can also get so caught up in the storylines of our embodied lives that we become unwilling to budge; on the flip side, we can challenge unhealthy dynamics, ideas, or behaviors and have what we thought were steady relationships blow up in our faces.

This chapter focuses on groups and spiritual friendships in a broad sense. *Out-of-scope* is any group that is centered around a temple for one or more Gods. Those groups are service-oriented — in this practice, a community comes into being around a God and expresses its spiritual development through the commitment of time, resources, (usually) permanent property reserved for the God(s), and festivals. This formal spiritual service involves a lot of ego sacrifice and cultivation of self-discipline. What I have written about avoiding toxic groups, modern cults, and harmful leaders still applies, but since the focus is on the community and its rituals for the God(s), some of what I say about prioritizing yourself and your own practice applies less. You should still check its articles of incorporation and rules to ensure that the God is prioritized over the leaders.

## Family

I am very lucky in that I grew up praying to mother Goddesses in the backwoods. I was with my family and in a very loose community. We went to a Unitarian Society many Sundays, although the religious education program for kids was often more miss than hit, but the true joys were when we convened every six weeks at some family friends’ rural property and were able to process to a sacred place, do ritual, and have a potluck in community afterward. We celebrated the seasons, the elements, a God, and a Goddess.

My parents never required that my sisters and I participate, and we rarely did family rituals at home, but they were very open that we *could* participate. I am a self-directed, “okay, let’s do this” person when it comes to spirituality, and I always have been. The Christian denominations we were in when I was a very young child made no sense, and when we apostatized, I was relieved because the framework of many Gods felt right, and I was happy we had ended up in something that made more logical sense. Later on, when I became interested in theology, my feelings became grounded in something more. My youngest sister rebelled against the family by getting interested in very conservative Christianity as a teen, although that didn’t last. My middle sister felt that she wasn’t included in the family rituals and that it was “our thing” — for our parents and me. I only learned this after we were all adults and when she discussed wanting to go deeper into the practice. It made me feel awful that I hadn’t been there for her.

Based on comparing our childhood experiences, I do recommend involving your kids — if you can — in revering many Gods. Let them *know* that they’re welcome, explain why you pray to the Gods you pray to and that they can to pray to whomever they like, and be open to their participation in your daily rituals if they want that. If they say no, have them participate in holidays, but don’t force them to do more. If they want a sacred space in their rooms, help them. I started using candles in my room when I was twelve, at about the same age I started doing my family’s laundry and much of the weeknight cooking. You know your children and their maturity level. Depending on your kids and their engagement with large media franchises, you may have to explain how worshipping Greek deities is different from Percy Jackson (the “chosenness” thing can be particularly tricky for kids; I remember encountering a bunch of teens once who thought they were demigod children of deities because they’d fallen into that extreme escapist belief online) or how the Marvel characters named for Norse Gods are just imaginative interpretations of myth created by screenwriters who are mostly atheists.

Make sure that, to the extent possible, any shared family ritual time is a device-free zone. It’s OK to use eReaders, computers, or phones to access texts, show sacred images, or use a playlist. Just make sure that any device is silenced or in airplane mode and that only the apps you need are open.

Sometimes, a person starts following many Gods after a period of significant trauma in their early religious life, such as those who left cults. Emphasizing participation in spirituality or even teaching a child ethics can bring up feelings about what happened when the parent was younger. Keep in mind that your child may have no idea, or only a vague idea, of what happened to you. Shield them from your experience by modeling the values that you want them to have when they grow up. Emphasize ethics, but be sure to focus on a growth mindset in which we as individuals are continuously learning to be better people, not one in which small mistakes are damning. If you can, consider seeing an individual or family therapist.

Finally, involving your kid comes with some important safety tips. To be blunt, your child will go online — either with your permission or in secret. What you want is for your child to have a firm foundation in reality so they don’t end up joining a cult or some fringe group that believes it is channeling new physics from aliens on a planet orbiting Zeta Reticuli. Critical thinking skills are an absolute must. Teach your kids how to distinguish among religion, mystical/esoteric practices, New Age, and the occult. New Age is where many of the fringe beliefs are, but fringe can spill over into the other communities I just mentioned — and, when we think of modern conspiracy phenomena, it is very clear that no segment of the population is wholly immune. Developing a firm foundation can be challenging for children who have a score of four or higher on ACE (Adverse Child Experiences) tests, which correlates with higher chances of self-soothing escapism and failure to thrive as adults. I have an ACE score of four, and I held some embarrassing beliefs in my late teens that developed as coping mechanisms. It wasn’t until going to therapy in my late 20s and graduating from therapy after getting very into Platonism and learning growth-based frames for thinking about myself and my life experiences that I started to feel steady.

Even when something a child encounters online is sound, there is so much overlap online among pagans, polytheists, and indigenous traditions, on the one hand, and the occult and witchcraft on the other, that it becomes easy to confuse these communities. Online, we are all exposed to new ideas from people with backgrounds that are completely unfamiliar to us, good and bad. *The Soul’s Inner Statues* is emphasizing a theistic, many-Gods approach. It is not connected to witchcraft or the occult — and if the approach that I am presenting is what you are most comfortable with, keep the “we worship many Gods” identity at your heart when you and your kids go online. If you want to do magic or occult practices, be clear to your child what is your core spiritual practice and what you’re doing in addition to it. If they grow up and enjoy praying a bit, but don’t like magic, this helps them make good decisions about what to include or exclude from their spiritual practice without thinking that it’s an all-or-nothing situation.

Kids don’t need to be watched every second they’re connected to the web, but they do need structure, critical thinking, and parents who care about their spiritual lives. They need to be taught what boundaries are. They can be given greater and greater responsibility over their own spiritual growth as they develop from babies to teens to adults.

## Partners and Roommates

If you have other adults in your living space, like a spouse or roommate, involving them in your religion could take several forms. If the other adult also worships many Gods (likely different ones), holidays in your respective traditions are opportunities to share food and stories and pray together. If your spouse or roommates are not religious, they may also be perfectly fine with sharing a special meal for holidays — most nonreligious people and atheists are not antireligious even if YouTube comments and online trolls indicate otherwise.

If your spouse or roommate is antireligious, you will likely experience substantial friction. Members of exclusivist monotheistic faiths who are progressive may also be willing to have meals with you, but more conservative ones will likely have issues with you and call you an idolater. I know someone whose spouse believes she is consorting with demons, and it’s psychologically hard for her as someone who is drawn to worshipping other Gods to have her spouse be that hostile.

## Finding People

This section relies on three words for nonromantic, non-kin interpersonal relationships: parasociality, acquaintanceship, and friendship. In the United States, many people will not distinguish between acquaintances and friends, but I find that this is a crucial frame to help me calibrate my social obligations towards others, especially as someone who was not trained to have good empathic boundaries as a child.

*Parasocial* is a term developed in the mid-1950s to describe the relationship between TV personalities and their audiences (Hoffner, 2022). In the early days of the social media era, Influencers began using it to describe their relationships with the massive numbers of people who interact with them. More recently, it has begun to refer to interactions among people who really don’t know each other online — you follow their content, they follow yours, but you two do not interact as either acquaintances or friends. In a parasocial relationship, we typically have one-sided information about someone. Online, we share carefully-curated details about our lives, so much so that others feel they know and trust us when they may have only a vague idea of who we even are, if any idea at all. It plays with the follower’s emotions and may lead to feelings of devotion, allegiance, goodwill, betrayal, moral outrage, and social rejection, as mercurial as a stormy sea, based on what someone posts. While most of us do not have a huge online reach, Influencers and celebrities do, and they experience the downsides of parasocial relationships more intensely than the rest of us.

*Acquaintanceship* is a mutual state in which you vaguely know someone, but may not be on the same page about who both of you are. More distant acquaintances are people who see each other and say hi at the gym, while catching transit, or when chatting on discussion fora or chat servers. Close acquaintances are people who have decided that they care about each other in a vague social sense, enough to have genuine interest in how things are going. Perhaps they learn the names of one another’s pets or children or even share phone numbers or start emailing. The mutuality is key here — whereas in a parasocial relationship, you are engaging with someone’s broadcasted content, in an acquaintanceship, you are actually getting to know each other. Many acquaintances are perfectly happy not to have a deeper level of engagement. Aristotle, while he had a dubious understanding of the Platonic Forms and an irritating lack of respect for women, has a lot of really useful perspective in the *Nichomachean Ethics* (chapters 8 and 9) for thinking about friendship. He describes something called a “friendship based on utility” that “belongs to the marketplace” (1158a, 21-23). Utilitarian friendships, in my opinion, are professional, collegial, or logistical close acquaintanceships.

The pathway from acquaintanceship to friendship involves gradual steps, usually in the form of mutual experiences. People seeking to make friends will also start to disclose more information, gradually testing the waters to see if the feelings of affinity are reciprocated and if the other party can be trusted.

*Friendship*, like acquaintanceship, comes in layers. Casual friends care about one another, take interest in one another’s lives, and may have some shared values in common. They may also be members of a social cluster who are more peripheral to each other than to others in the group, or they may have become friends due to shared professional or personal experiences. Friendship of this nature is also friendship between those who are prepared to be mutual and who see one another at (roughly) the same level — as equals — even if there are differences in age, social class, or cultural background. The “purification of correction” (a concept that the ancient Platonists sometimes discuss), or the mutual checks friends offer one another, is possible at this level of interaction because friends generally want what is best for one another and care enough to allow the other to be imperfect, and friends care enough about one another to do this tactfully.

Aristotle writes that “a wish for friendship arises swiftly, but friendship itself does not” (1156b, 30). This is true in both the transition of acquaintances to friends and about the transition from casual to close friends. While in a casual friendship, one might censor oneself and keep some things private, *close* friends generally share much more of themselves with one another. Aristotle calls this form of friendship *complete friendship* (1156b, 5) — the two of you have similar gasps of virtue and enough similarity in outlook that you can know and accept one another’s character. A person cannot sustain many of these relationships at once.

Friendship is where ethical imperatives towards one’s associates appear in full force — Solon’s ethical tenets instruct us to be slow in making friends, but not to abandon them once we have solidified our friendship. That makes the most sense when applied to friends who are at middle to total levels of closeness. Aristotle provides guidance on this, too, in the *Nicomachean Ethics*, saying that corruptions of virtue and outlook among our close friends must be approached with care for their character, not out of interest in their public persona or property or the utilitarian benefits of the friendship. Even when a friendship cannot be maintained, he writes that “on account of their prior friendship, [we must] render something to those who were once friends, when its dissolution was not due to excessive corruption” (1165b, 35). Ending a close friendship is a last resort. And trust me: If one of your friends, medium-close or close, gets cancelled or doxxed by parasocials, you will feel the heat from this, and the parasocials will assume you have no moral backbone and are willing to just chuck your friend to the curb at the drop of a hat. Come to a decision about the friendship on your own.

While in a parasocial relationship, the feelings of betrayal have no actual basis in mutual care, feelings of betrayal and hurt when something bad happens in a casual-to-close friendship are based on a real, intangible connection. They can often be resolved by actually talking it out with the friend. Unlike with children, irreversible fallouts rarely happen at the drop of a hat. You can be more of your whole self with close friends without fearing that they will turn on you or that their care is conditional. Often, those of us who have spent some time on social media can harbor a lot of anxiety about being fully open and vulnerable around friends, as we see so much toxic behavior. In my experience, the toxic behavior is most likely to happen with acquaintances and friends who are seeking social status and validation and who have done this to others before. We can rationalize seeing them do this and assume it will never happen to us, but this is a red flag. Many of us also tend to learn ethical frameworks fairly late in childhood or young adulthood, so we may have associations with people that are misguided or situations that we were never mentored to navigate by our elders. If you need to exit any associations like that, do have compassion for yourself and the other party or parties. Do not cling to bitter things from chapters of your life that have concluded.

I started this section with an overview of friendships for one key reason: **Just because others worship Gods, and even the same Gods as you, doesn’t mean you’ll all get along.** This is a painful life lesson. Our personalities are all unique, no matter how we try to bin them into categories with Myers-Briggs, astrology, or anything else. One might think that being in the series of the same God, if two people were to be blessed with confident insight into that, would make them instant friends. Even in that case, since a God is everything in a unique way, and as each of us is a particular soul that expresses a unique fingerprint of that uniqueness, devotees express the full range of what that God is.

Ideally, when looking for people to approach about your mutual interest in the Gods, your goal is to identify candidates for close acquaintances and casual friends. Rarely, you will develop new close friends.

### Local Organizations

Depending on the size and demographics of your local area, there may be people nearby with preexisting groups that you can join. Shops that sell “alternative” religious materials (like incense, deity statues, and so on) often have good inventories of the groups that exist nearby. You can also use Meetup and check for groups on social media that are local. Many will have some public events even if their core activities are private and members-only.

If you are worshipping deities that have temples or shrines in your metro area, learn more about the organizations around you and contact them to ask if it is possible for you to pray there. Generally speaking, they will have volunteers and other people who would be happy to show a respectful outsider how to engage with the Gods in a tactful manner.

### Social Media

To find friends in the 2020s, most people start on social media platforms, Influencer-related Discord or Slack servers, and Internet forums. There are some important pitfalls, and I advise you to use social media strategically to identify people you actually want to talk to. Once you have that, get out. Especially in private Discords that are run by Influencer personalities (which I recommend avoiding), things can quickly go south into cult-land. Discord servers that are *not* related to an Influencer, that have clear rules about cults of personality, and that host level-headed discussion among equals are less of an issue — they’re more like going to your local pub or coffeehouse.

The reason I encourage you to have an exit game is that the psychological impacts of heavy social media use are similar to other high-risk addictive behaviors. Once you feel parasocially obligated to be online and post to a large audience, you will also likely be “trapped” on whatever platform you’re using. Studies show that people who are primarily active on social media for their social interaction face higher rates of anxiety and depression, as social media doses us with dopamine using algorithms similar to casino slot machines. Parasocial validation cannot functionally replace getting to know people privately. Unfortunately, many of us are also lonely and lack robust in-person networks, so social media is used as a stand-in (Jarzyna, 2021; Valkenburg, 2022; Meshi, 2021).

While you are on social media, be it TikTok, Facebook, Twitter, or the latest and greatest new platform, do not feel pressure to follow back or friend anyone. Your update feed is your space. Look at the person’s profile and decide if you find their updates parasocially relevant. If so, follow. If not, don’t. When I was very active on social media, I rarely followed back immediately — and it often took me weeks, months, or years to do so. Most people I followed were writing content that I found useful or whose updates I’d be looking up using the search function. In private social media spaces, I only let people see my content if I feel comfortable having them see it. Occasionally, I follow people back when I already know them (distant to close acquaintances). One rarely knows why someone is following the people they follow. Knowing a stranger’s habits that well is a bit creepy.

Facebook groups and Instagram hashtags about the Gods are also filled with what I like to call aesthetic posts — people posing with animal skins, horns, period clothing, and other items. It is materialistic and annoying for people who are actually there for content that helps them grow spiritually. It can also trigger our acquisitive instincts due to the human instinct to conform to group norms. Even when people post shrine photos, it can prompt a materialistic impulse for people whose setups are simpler and less expensive. Unless you know someone, you have no idea if they’ve been practicing for 20 years and have built their shrine items up over that amount of time or if they went into debt buying all of those items two months ago. Shrine photos are fine, though, when they give you ideas for what you can do with the space that you have.

Social media rewards oversharing, negative content, and a lack of personal filter/boundaries. For this reason, spiritual bypassing, out-of-the-norm experiences, and misinformation are all rewarded by the algorithms. Rather than sit with a private experience for a while, many people instantly share what they think happened with strangers online. Sharing personal experiences is best done first in a private journal, then among people one actually knows and trusts. Because many of us are lonely and lack close friends, social media oversharing becomes even more seductive. We are all more likely to post when we are feeling strong emotions, too, like when online misinformation pushes our buttons. We all slip up.

If you are on social media for personal or professional reasons, remember that when fights happen on social media, most people in the conversations are fighting with shadows created by their own fears, not with you. This is why people can get so vindictive — the depersonalization involved in online interactions combines with whatever is going on in their mental and emotional landscape to make a bad situation even worse. If you have learned techniques from difficult conversations trainings (my workplace has these all the time), now is the time to use them. Over the years, I have learned that it is impossible to deescalate everything, even with training. Some fires are just not containable.

## The Mechanics of Group Ritual

Once you find one or more people to do ritual with, it’s time to look at your longer ritual outlines. Typically, whether you do a ritual in-person or on a digital platform like Zoom, you will need to share the ritual outline ahead of time. If everyone involved worships many Gods, there may be edits and amendments based on elements of practice that others want to include. Google Docs or another multi-person editing tool is great for this.

Collaboratively assign people roles. When I was growing up, we knew that the hosts who owned the property would be managing the overall ritual, but they took volunteers for invoking the elements and the ritual’s deities. This happened when people were gathering in the processional area about ten minutes before the ritual started. If you know who will attend your rituals beforehand, in Google Drive or another collaboration tool, let people pick which sections of the ritual they want to take charge of.

If running a ritual on Zoom or another videoconferencing platform, be sure that someone is taking the role of Zoom host — this person can spotlight the person doing each part of the ritual. Chanting isn’t as easy on Zoom as it is in person, so you may want to mute everyone except the chant leader. Be clear with everyone whether you are all doing the ritual simultaneously together (with similar offerings and space setups) or if one person will show the ritual setup and make the offerings. If it’s the latter, the designated ritual space provider should be spotlighted even when others are speaking.

Some groups will do a debrief of the entire ritual immediately before the ritual takes place, which can be tedious for those who came prepared. I recommend doing this offline and setting an expectation that everyone is reading through the materials in advance. If new people are present who are unfamiliar, do not assign them anything, but make sure you or another person welcomes them and is available to answer any questions after the ritual.

Most often, people will use their own homes for rituals and trust that guests will follow rules of hospitality. They may also secure permits to do rituals in public spaces like parks if the ritual is large enough; if it’s only a few people, they might just go to the park, depending on local regulations. Less frequently, groups may rent a space (a Unitarian Universalist Church is great for that), which can help establish trust among people who don’t know one another well enough to feel okay sharing their home address for future rituals. Within traditions that worship many Gods, there are sometimes physical locations that are supported by the community, either temples or land.

## Joining Groups

So, let’s say that you decide you like a group — online or offline — and want to be a joiner. Congratulations on having taken such a big step! You’re going to learn a lot, and I hope that this primer has been helpful.

When you are making your decision, here are some things to look for, but this is not a checklist — the most important things are that the group encourages mutual respect and spiritual growth.

1. Does the group have a nondiscrimination policy? How is it enforced? Is training mandatory for officers? Many are quick to sign statements about inclusivity, but few are willing to put in the work to ensure that leaders are actually prepared to handle conflict situations.
2. Is the group centered around a single person? If it is centered around one person, is it because they have the highest level of training in the tradition? Who trained them? Is there an accountability structure that applies to people with their level of training at the regional, national, or international level? How are officers and leaders of the group chosen?
3. Has the group appeared in the news associated with any cult scandals? Have former members written any exposés? What did they say, and how did the group respond?
4. If the group is claiming to be a revival of a tradition from a region, are people who are descendants of the group(s) living in that region represented in leadership positions — and not just in a tokenizing fashion? Thinking back to the cultural appropriation content earlier in this book, is the group engaging in any red flags? What do members of the group say about the tradition’s living descendants in general? Is the group open to growth and change, or does it fall under “reenactment”?
5. If you have children, is the group child-friendly? Are there some rituals that are fine for the whole family and others that are restricted to teens and adults? Is there childcare? If nobody has kids, this isn’t an issue, but it may become one.
6. What are the educational development opportunities for members?
7. Is the group legally incorporated? This isn’t a dealbreaker, but groups that have legally incorporated are often more stable than ones that are not. Decentralized continuous traditions may not be incorporated, so this question does not apply to them.

Using these questions to frame your research, you should be prepared to sift through the organization’s website and ask questions of members of the group if you attend a few rituals and want to know more about them. I was once in a group where long-term members repeatedly described, in an elated way, how they thought outsiders would go after them if they were successful and how they were prepared for the worst. Red flags like that will likely not be on the website — you have to get to know people.

Once you have found a group, sign up for its listservs, forums, and other online presence locations. Try to make at least a few of their in-person or online meetups when possible. When I first joined one group, I lurked for a long time, but it meant that I didn’t get a feel for what other people in the group were like until I was eligible for leadership positions, and I came to know that we did not have compatible values.

### When Leaders Go Bad

Throughout our youths, we come to know that the authority figures in our lives — our parents, other adults, religious teachers, and so on — are just as human and fallible as we are. The first time I saw someone I considered a spiritual leader behave in a toxic way online, I was in my early 20s. Nowadays, with the way social media is designed, I imagine people have this shock at a much younger age. When I saw what I saw, I was only *witnessing* what was happening, and I still had to process extreme disappointment.

Unfortunately, that experience is mild in comparison with what happens to many other people. Cults, sexual abuse, and similar horrors are rampant in interpersonal spaces, spiritual or secular. These things may be centered around a specific person, or they may take place within the context of a group’s organizational structure.

When it comes to individuals, we can draw some understanding from the commentary that Edwin F. Bryant made on Patañjali’s *Yoga Sūtras*. In a chapter on meditative absorption, Bryant translates I.15 as, “Dispassion is the controlled consciousness of one who is without craving for sense objects, whether these are actually perceived or described” (52). He cites two prior commentators on the same passage of the *Yoga Sūtras*: dispassion is “indifference to objects even when these are available” (Vācaspati Miśra) and includes “members of the opposite sex, food, drink, and power” (Vyāsa). This echoes things said in Platonism about control of the passions of the appetitive and spirited parts of the human soul, which — when they are left unchecked because someone has not properly brought them into alignment — lead to disasters great and small. “The wise,” Bryant continues, “strive for detachment and the eternal experience of the soul rather than the never-ending pursuit of ephemeral pleasure” (53).

It is that detachment that allows someone to lead a group without being corrupted by power — and, crucially, even when someone starts out holy, they can backslide. Spiritual teachers are honestly some of the most vulnerable people to lies, tyrannical downfalls, vice, and abuse, partially because people trust them, and we are less likely to hold people we admire accountable. The goal of being a guide for others is to positively impact others’ minds and souls, and those others then open up and become vulnerable. Socrates gets into how devastating spiritual abuse can be at *Phaedo* 89d-e, as it hardens people against any spirituality or truth-seeking at all — the wound leaves them jaded. A spiritual teacher needs a group of peers and friends to hold them accountable, people who are not afraid to say the hard things.

In the same commentary on the *Yoga Sūtras*, at I.14 (”practice becomes firmly established when it has been cultivated uninterruptedly and with devotion over a prolonged period of time,” 49), Bryant takes what Patañjali has written to comment on the recent stream of abuse scandals in yoga. According to him, the practice must be cultivated continuously, like a garden. Otherwise, disaster may happen:

>As an aside, many Hindu gurus and yogīs have been embroiled in scandals that have brought disrepute to the transplantation of yoga and other Indic spiritual systems to the West. This sūtra provides a mechanism of interpreting such occurrences. If one reads the early hagiographies of many Hindu gurus whose integrity was later found compromised, one is struck by the intensity, devotedness, and accomplishments of their initial practices. Nonetheless, however accomplished a yogī may become, if he or she abandons the practice of yoga under the notion of being enlightened or of having arrived at a point beyond the need of practice, it may be only a matter of time before past saṁskāras, including those of past sensual indulgences, now unimpeded by practice, begin to surface. The result is scandal and traumatized disciples. There is no flower bed, however perfected, that can counteract the relentless emergence of weeds if left unattended. As Patañjali will discuss later in the text, as long as one is embodied, saṁskāras remain latent, and therefore potential, in the citta [mind]. Hence one can read this sūtra as indicating that since the practices of yoga must be uninterrupted, one would be wise to politely avoid yogīs or gurus who claim to have attained a state of enlightenment such that they have transcended the need for the practice and renunciation presented by Patañjali here.  
>
>*Yoga Sūtras*, trans. Bryant, p. 51

This passage could apply to any spiritual community: The leaders cannot, for the sake of those following them, fall prey to power. Sometimes, people go into leadership positions because they feel a lack that they believe only power over others can provide, and they spend the remainder of their lives hiding skeletons in their closets and using their current followers as a replacement for real self-improvement. Leadership often ends badly for them. In any case, the fallout impacts the entire group. It is negligence at its best, calculated indifference to the welfare of others at its worst. All teachers need training and accountability. All teachers need to demonstrate care towards the souls of others, imitating the Gods, as the Gods are wholly good. If an asteroid impacted Earth tomorrow and wiped our species out, does being the leader of a group matter as much as helping others get started with their own relationship with the Gods? We cannot take awards or good reviews with us. We are seeded from a variety of Gods, with diverse dispositions, and the personal, private practices we cultivate for ourselves are what is most vital.

Beyond leaders and teachers, toxic groups scare people with what will happen to them. They ostracize someone who criticizes a group policy instead of inviting discussion, explanations, and (perhaps) change. They terrorize people if they make simple human mistakes. They judge and punish if a member likes the wrong books, buys food out-of-line with the group’s norms, or displays negative emotions (Montell, 2021). Meanwhile, they puff up followers with the idea that they are members of a special, awakened elite. You cannot be compassionate or cultivate civic virtue if you internalize us/them exclusivity rhetoric.

Often, those drawn into a cult are people who are motivated to do good in the world — just as Plato teaches, people always want to do what they think is best, even if they are in error. Their strong motivation to do good is manipulated through love-bombing and the fear of ostracism and hatred from the people they respect. Us/them thinking and “we’re the only good people and you must believe these specific doctrines, and these alone” rhetoric is extremely prevalent in online New Religious Movement communities in the 2020s, on the right and the left. Do not trust people who try to cut you off from different ideas while threatening to ostracize you if you disobey.

Paradoxically, the language of “we’re a niche” is also used in a less intense way in nontoxic systems. In Platonism, for example, theurgic and philosophical incarnation choices are prioritized for achieving henosis and a providential exit from the current cosmic cycle. But it encourages critical thinking at the same time — you are supposed to question, to work through the dialogues, to understand that even the holiest people incarnated were human beings. Exegesis is a torch relay. When people try to misapply Platonism for spiritual bypassing or to gain power, they will often be overly literal in interpreting texts and/or fuse Platonism with a prevailing political current or zeitgeist, and they will miss the interpretive mark.

Be wary of leaders who try to twist your embodiment anxiety and desire for transcendence into something toxic to your soul. Be wary of leaders who plaster their faces everywhere — while dead holy people are honored with libations and appropriate commemorative well-wishes, human beings, dead or alive, should not be revered as if they are of the same status as the Gods — and those who scare you into silence with the threat of ostracism if you question anything or have slightly different beliefs than they do.

The Gods are the wellsprings of human happiness, as per Iamblichus. Humans swim in an ocean of transient pleasures and pains. Follow the Gods, and they will lead you up the mountain to touch the sky. Follow humans uncritically, and they may very well lead you to the bottom of an ocean trench.


## Exercise: Know What You Want

Research groups, either tradition-specific or not, based on who you worship and what you are looking for in a community. Use the questions above and narrow down to one or two (if possible) to learn more about. Try attending one of the group’s open events if you can.

Meanwhile, identify what you want in online or in-person spiritual friends. What are the values you are looking for in someone else? Your dealbreakers? Where do you plan to meet people? If you plan to use social media, what rules do you want to set around using the platform?

These questions are ideal for answering in a journal or text file, and you can refer back to them over the next few months. I recommend checking in about your social media habits at least monthly to ensure that you are not succumbing to overuse.


