# Acknowledgments and Further Reading

## Acknowledgments

When I started praying to Bast at the age of nine, and at ten when my parents first brought me to Circle, the world was very different. As a kid, my dad would take me to the mall. I would usually end up in Waldenbooks, where I perused the spirituality section (all four shelves) and the discount books on display at the front of the store. My mother would take me to the Opened Book in Hannibal, MO, where I purchased ritual supplies and pagan books.

As most children do, I acquired most of those early items by pleading; when I was 15 and able to work, I used my pocket money. The community in the Hannibal, MO, area was the best thing that happened to me as a child, a bright star. I dearly hope that everyone who knew me as a child, teen, and young adult forgives my embarrassing flaws and accepts my gratitude. I am extremely thankful for the communities of affinity I have fallen into over the past few years — while many have lamented the pandemic for a lack of closeness, Zoom has brought me to so many amazing people and meaningful discussions. Co-reading Platonic texts with other people is such a world-changing experience. You know who you are if you are reading this. I also acknowledge my more recent interlocutors on the blogosphere and other text-based online venues — we are all taking a journey together, as parasocial as it may be, regardless of how well we know each other. Growth by fire. I also thank those who read the earlier online version and gave me feedback and anyone who has heard me rant and ramble about anything related to praxis and theology, in any context. You have helped to make this so, so much better, and I hope the changes have improved the work’s accessibility, accuracy, and relevance to readers.

Outside of family and community, I have the authors of the books I have devoured over the course of my life to thank. Most of these books are long gone, decluttered when I downsized to move to my current city. The items below are the best I have to offer by way of a reference list. I also added some footnote links in the *Soul’s Inner Statues* itself — often to apps and pages. What is linked in footnotes or referenced below represent what was most on my mind while I was writing. The foundations and scaffolding of the *Soul’s Inner Statues* came from blog posts published on KALLISTI and its predecessor (also named KALLISTI) between 2009 and 2022. Link rot is real, so if any of the links in either the Further Reading or Bibliography go somewhere else, please use the Internet Archive’s Wayback Machine at [https://archive.org](https://archive.org).

Inclusion of works in the references, or indeed mentioning them at all, is not meant as endorsement of a particular author’s viewpoints in the past, present, or future. Citation is an acknowledgment of the influence of concepts and an important part of maintaining integrity, avoiding false speech, and refraining from plagiarism. Inclusion on the Further Reading list is a positive recommendation.

## Further Reading

In library science, we do something called ”reader’s advisory” — a jargon term for connecting readers to books they want. The list below includes resources from the bibliography above that are useful for further reading for a newcomer, in addition to some things that I have *not* read that seem like they would be a helpful next step for someone beginning a ritual practice. These include books, websites, and some video media.

Addey, Tim. *The Unfolding Wings: The Way of Perfection in the Platonic Tradition*. Westbury: Prometheus Trust, 2011.

Bernstein, Frances. *Classical Living: A Month to Month Guide to Ancient Rituals for Heart and Home*. 1st edition. San Francisco: HarperOne, 2000.

Epstein, Nadine, and Rosita Arvigo. *Spiritual Bathing: Healing Rituals and Traditions from Around the World*. Reprint, Revised ed. Echo Point Books & Media, 2018.

Heidi. ”Smoke Cleansing Around the World.” *Mountain Rose Herbs* (blog), July 26, 2021. [https://blog.mountainroseherbs.com/smoke-cleansing](https://blog.mountainroseherbs.com/smoke-cleansing)

“Household Deity.” In *Wikipedia*, July 9, 2022. [https://en.wikipedia.org/w/index.php?title=Household_deity&oldid=1097197400](https://en.wikipedia.org/w/index.php?title=Household_deity&oldid=1097197400)

Johnsen, Linda. *Lost Masters: Sages of Ancient Greece*. Honesdale, PA: Himalayan Institute Press, 2007.

Mandell, Mindy. *Discovering the Beauty of Wisdom*. Prometheus Trust, 2020.

Nolan, Barbara. *A Year of Pagan Prayer: A Sourcebook of Poems, Hymns, and Invocations from Four Thousand Years of Pagan History*. Woodbury, Minnesota: Llewellyn Publications, 2021.

Nordvig, Mathias. *Ásatrú for Beginners: A Modern Heathen’s Guide to the Ancient Northern Way*. Emeryville, CA: Rockridge Press, 2020.

Pennick, Nigel. *The Pagan Book of Days: A Guide to the Festivals, Traditions, and Sacred Days of the Year*. Revised edition. Rochester, VT: Destiny Books, 2001.

Raheem, Octavia F. *Pause, Rest, Be: Stillness Practices for Courage in Times of Change*. Boulder, Colorado: Shambhala, 2022.

Omland, Correne. *Smoke Cleansing: What It Is and How to Perform It*, 2021. [https://www.youtube.com/watch?v=_oFzD2ByB4o](https://www.youtube.com/watch?v=_oFzD2ByB4o)

Solstice. *The Earth Spirit Hearth and Home: A Seasonal Guide for a Nature-Based Home*. Grove City: Earth Spirit Press, 2022.

Temperance, Elani. ”Khernips [Purification] Masterpost.” *Baring the Aegis* (blog), May 2016. [http://baringtheaegis.blogspot.com/2016/05/khernips-masterpost.html](http://baringtheaegis.blogspot.com/2016/05/khernips-masterpost.html)

Wijeyakumar, Anusha. *Meditation with Intention: Quick & Easy Ways to Create Lasting Peace*. Woodbury, Minnesota: Llewellyn Publications, 2021.

## Bibliography

ACRL. “Framework for Information Literacy for Higher Education.” Text. Association of College & Research Libraries (ACRL), February 9, 2015. [https://www.ala.org/acrl/standards/ilframework](https://www.ala.org/acrl/standards/ilframework)

Addey, Tim. *The Seven Myths of the Soul*. Westbury: Prometheus Trust, 2011.

———. *The Unfolding Wings: The Way of Perfection in the Platonic Tradition*. Westbury: Prometheus Trust, 2011.

Anonymous. *Anonymous Prolegomena to Platonic Philosophy*. Translated by L. G. Westerink. Westbury: Prometheus Trust, 1994. [https://kindredstarbooks.com/products/anonymous-prolegomena-to-platonic-philosophy](https://kindredstarbooks.com/products/anonymous-prolegomena-to-platonic-philosophy)

Anonymous. *The Orphic Hymns*. Translated by Apostolos N. Athanassakis and Benjamin M. Wolkow. Johns Hopkins University Press, 2014.

Aristotle. *Aristotle’s Nicomachean Ethics*. University of Chicago Press, 2012.

Avins, Jenni. “The Dos and Don’ts of Cultural Appropriation.” *The Atlantic* (blog), October 20, 2015. [https://www.theatlantic.com/entertainment/archive/2015/10/the-dos-and-donts-of-cultural-appropriation/411292/](https://www.theatlantic.com/entertainment/archive/2015/10/the-dos-and-donts-of-cultural-appropriation/411292/)

Bernstein, Frances. *Classical Living: A Month to Month Guide to Ancient Rituals for Heart and Home*. 1st edition. San Francisco: HarperOne, 2000.

Bryant, Edwin F. *Yoga Sutras of Patañjali*. First edition. New York: North Point Press, 2009.

Butler, Edward P. “Noēseis Archives.” *Polytheist.Com: Noēsis* (blog). Accessed March 8, 2022. [http://polytheist.com/noeseis/](http://polytheist.com/noeseis/)

——— “On Gods ‘Behaving Badly.’” *Endymion’s Bower* (blog), May 10, 2019. [https://endymions-bower.dreamwidth.org/57262.html](https://endymions-bower.dreamwidth.org/57262.html)

———. “Polycentric Polytheism.” In *Witches & Pagans*, 32. June 2016, 37-40.

———. *The Way of the Gods: Polytheism(s) Around the World*, Notion Press, 2022.

Chart, David. *Shinto Practice for Non-Japanese*, volume 5, *Mimusubi Essays on Shinto*, 2020.

Clear, James. *Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones*. Illustrated edition. New York: Avery, 2018.

Gaifman, Milette. *The Art of Libation in Classical Athens*. Illustrated edition. New Haven Connecticut: Yale University Press, 2018.

Harland, Philip A. “Graffito for Apollo by the Boreikian Society (ca. 300 BCE).” *Associations in the Greco-Roman World: An Expanding Collection of Inscriptions, Papyri, and Other Sources in Translation* (blog). Accessed July 16, 2022. [http://philipharland.com/greco-roman-associations/dedication-to-bios-life-by-the-boreikian-society-300-bce/](http://philipharland.com/greco-roman-associations/dedication-to-bios-life-by-the-boreikian-society-300-bce/)

Hermias. *Hermias: On Plato Phaedrus 227A–245E*. Translated by Michael Share and Dirk Baltzly.* Ancient Commentators on Aristotle*, edited by Richard Sorabji and Michael Griffin. New York: Bloomsbury Academic, 2018.

———. *Hermias: On Plato Phaedrus 245E-257C*. Translated by Michael Share and Dirk Baltzly. *Ancient Commentators on Aristotle*, edited by Richard Sorabji and Michael Griffin. New York: Bloomsbury Academic, 2022. 

Hoffner, Cynthia A., and Bradley J. Bond. “Parasocial Relationships, Social Media, & Well-Being.” *Current Opinion in Psychology* 45 (June 1, 2022): 101306. [https://doi.org/10.1016/j.copsyc.2022.101306](https://doi.org/10.1016/j.copsyc.2022.101306)

Iamblichus. *Iamblichus of Chalcis: The Letters*. Translated by John M. Dillon and Wolfgang Polleichtner. Atlanta: Society of Biblical Literature, 2009.

———. *Iamblichus’ Life of Pythagoras, or Pythagoric Life Accompanied by Fragments of the Ethical Writings of Certain Pythagoreans in the Doric Dialect; and a Collection of Pythagoric Sentences from Stobaeus and Others, Which Are Omitted by Gale in His Opuscula Mythologica, and Have Not Been Noticed by Any Editor*. Translated by Thomas Taylor, 2020. [https://www.gutenberg.org/ebooks/63300](https://www.gutenberg.org/ebooks/63300)

———. *Iamblichus: On the Mysteries*. Bilingual edition translated by Emma C. Clarke, John M. Dillon, and Jackson P. Hershbell. Atlanta: Society of Biblical Literature, 2003.

Jarzyna, Carol Laurent. “Parasocial Interaction, the COVID-19 Quarantine, and Digital Age Media.” *Human Arenas* 4, no. 3 (September 1, 2021): 413–29. [https://doi.org/10.1007/s42087-020-00156-0](https://www.gutenberg.org/ebooks/63300)

Johnsen, Linda. *Lost Masters: Sages of Ancient Greece*. Honesdale, PA: Himalayan Institute Press, 2007.

Kornfield, Jack. *After the Ecstasy, the Laundry: How the Heart Grows Wise on the Spiritual Path*. New York: Bantam, 2001.

Laërtius, Diogenes. “Lives of the Eminent Philosophers.” Translated by Robert Drew Hicks, 1925. Wikisource.

Krasskova, Galina (Dec. 2017). Public Service Announcement. *Gangleri’s Grove* (blog), December 5, 2017. [https://krasskova.wordpress.com/2017/12/05/public- service-announcement/](https://krasskova.wordpress.com/2017/12/05/public- service-announcement/)

Laërtius, Diogenes. *Lives of the Eminent Philosophers*. Translated by Robert Drew Hicks. Wikisource, 1925. [https://en.wikisource.org/wiki/Lives_of_the_Eminent_Philosophers](https://en.wikisource.org/wiki/Lives_of_the_Eminent_Philosophers)

Layne, Danielle A. “The Anonymous Prolegomena to Platonic Philosophy.” *Brill’s Companion to the Reception of Plato in Antiquity*, October 11, 2017, 533–54. [https://doi.org/10.1163/9789004355385_031](https://www.gutenberg.org/ebooks/63300)

Layne, Danielle A. “The Character of Socrates and the Good of Dialogue Form: Neoplatonic Hermeneutics.” In *The Neoplatonic Socrates*, edited by Harold Tarrant and Danielle A Layne, 80–96. University of Pennsylvania Press, 2014.

Majercik, Ruth. *The Chaldean Oracles: Text, Translation and Commentary*. 2nd Edition. Westbury: Prometheus Trust, 2013.

Mandell, Mindy. *Discovering the Beauty of Wisdom*. Westbury, Prometheus Trust, 2020.

Meshi, Dar, and Morgan E. Ellithorpe. “Problematic Social Media Use and Social Support Received in Real-Life versus on Social Media: Associations with Depression, Anxiety and Social Isolation.” *Addictive Behaviors* 119 (August 1, 2021): 106949. [https://doi.org/10.1016/j.addbeh.2021.106949](https://www.gutenberg.org/ebooks/63300)

Montell, Amanda. Cultish: The Language of Fanaticism. New York, NY: Harper Wave, 2021.

Moore, Meido. *Hidden Zen: Practices for Sudden Awakening and Embodied Realization*. Boulder, Colorado: Shambhala, 2020.

Nabarz, Payam. *Stellar Magic: A Practical Guide to the Rites of the Moon, Planets, Stars and Constellations*. London: Avalonia, 2009.

Newport, Cal. *Digital Minimalism: Choosing a Focused Life in a Noisy World*. New York: Portfolio, 2019.

Nordvig, Mathias. *Ásatrú for Beginners: A Modern Heathen’s Guide to the Ancient Northern Way*. Emeryville, CA: Rockridge Press, 2020.

Nowakowski, David (n.d.). “Meditation.” (website) [https://davidnowakowski.net/meditation/](https://davidnowakowski.net/meditation/)

Olympiodorus. *Olympiodorus: Life of Plato and On Plato First Alcibiades 1-9*. Edited by Richard Sorabji and Michael Griffin. Translated by Michael Griffin. *Ancient Commentators on Aristotle*. London: Bloomsbury Academic, 2015. [https://doi.org/10.5040/9781474220286](https://doi.org/10.5040/9781474220286)

Petrovic, Andrej, and Ivana Petrovic. *Inner Purity and Pollution in Greek Religion: Volume I: Early Greek Religion*. Oxford: Oxford University Press, 2016. [https://doi.org/10.1093/acprof:oso/9780198768043.001.0001](https://doi.org/10.5040/9781474220286)

Plato. *Complete Works*. Edited by John M. Cooper and D. S. Hutchinson. Indianapolis: Hackett Publishing, 1997.

———. *Plato: Laws*. Edited by Malcolm Schofield. Translated by Tom Griffith. First Edition. Cambridge, United Kingdom; New York: Cambridge University Press, 2016.

Plotinus. *The Enneads*. Translated by Lloyd P. Gerson, George Boys-Stones, John M. Dillon, R. A. H. King, Andrew Smith, and James Wilberding. New York: Cambridge University Press, 2018.

Proclus. *On the Existence of Evils*. Translated by Jan Opsomer and Carlos G. Steel. Ithaca: Cornell University Press, 2003.

———. *Proclus: Commentary on Plato’s Republic*. Translated by Dirk Baltzly, John F. Finamore, and Graeme Miles. Volume 1. Cambridge University Press, 2018.

———. *Proclus: Commentary on Plato’s Timaeus: Volume 5, Book 4*. Translated by Dirk Baltzly. Cambridge University Press, 2013.

———. *The Six Books of Proclus, the Platonic Successor, on the Theology of Plato*. Translated by Thomas Taylor. Frome, Somerset, UK: Prometheus Trust, 1995. [https://kindredstarbooks.com/products/proclus-theology-of-plato-thomas-taylor-series-volume-viii](https://kindredstarbooks.com/products/proclus-theology-of-plato-thomas-taylor-series-volume-viii)

———. *Ten Problems Concerning Providence*. Translated by Jan Opsomer and Carlos G. Steel. London: Bristol Classical Press, 2012. [https://doi.org/10.5040/9781472552143](https://doi.org/10.5040/9781472552143)

———. *On Providence*. Translated by Carlos G. Steel Ithaca, N.Y.: Cornell University Press, 2007. [http://books.google.com/books?id=ZV8EAQAAIAAJ](http://books.google.com/books?id=ZV8EAQAAIAAJ)

Raheem, Octavia F. *Pause, Rest, Be: Stillness Practices for Courage in Times of Change*. Boulder, Colorado: Shambhala, 2022.

Rowe, Christopher. “Methodologies for Reading Plato”. In: *The Oxford Handbook of Topics in Philosophy.* Oxford University Press, February 2015. [https://dx.doi.org/10.1093/oxfordhb/9780199935314.013.28](https://dx.doi.org/10.1093/oxfordhb/9780199935314.013.28)

Rumi, Jalaluddin. “The Guest House by Jalaluddin Rumi.” *Scottish Poetry Library* (blog). Accessed July 16, 2022. [https://www.scottishpoetrylibrary.org.uk/poem/guest-house/](https://www.scottishpoetrylibrary.org.uk/poem/guest-house/)

Rugnetta, Mike and Kornhaber Brown. *Hell Is Quoting Other People | Idea Channel | PBS Digital Studios*, 2014. [https://www.youtube.com/watch?v=JzYPUP6LR5Y](https://www.youtube.com/watch?v=JzYPUP6LR5Y)

Sallust. *Sallustius On the Gods and the World*. Translated by Thomas Taylor, 1793. Wikisource.

Simplicius. *On Epictetus Handbook 27-53. Translated by Charles Brittain and Tad Brennan. In *Ancient Commentators on Aristotle*, edited by Richard Sorabji. London: Bloomsbury Academic, 2014.

Syrianus. *Syrianus: On Aristotle Metaphysics 13-14*. In *Ancient Commentators on Aristotle*, edited by Richard Sorabji. Translated by John Dillon. London: Bristol Classical Press, 2007.

Upadhyaya, Nidhi. “Young Hindus Get Creative with Home Temples in Cramped Apartments.” *Religion News Service* (blog), October 13, 2021. [https://religionnews.com/2021/10/13/millennial-hindus-get-creative-with-home-temples-in-cramped-apartments/](https://religionnews.com/2021/10/13/millennial-hindus-get-creative-with-home-temples-in-cramped-apartments/)

Valkenburg, Patti M. “Social Media Use and Well-Being: What We Know and What We Need to Know.” *Current Opinion in Psychology* 45 (June 1, 2022): 101294. [https://doi.org/10.1016/j.copsyc.2021.12.006](https://doi.org/10.1016/j.copsyc.2021.12.006)

Wijeyakumar, Anusha. *Meditation with Intention: Quick & Easy Ways to Create Lasting Peace*. Woodbury, Minnesota: Llewellyn Publications, 2021.

Wildermuth, Rhyd. “A Plague of Gods: Cultural Appropriation and the Resurgent Left Sacred.” *A Beautiful Resistance* (blog), June 3, 2021. [https://abeautifulresistance.org/site/2021/6/03/plague-of-gods](https://abeautifulresistance.org/site/2021/6/03/plague-of-gods)

